- jkube-kit/parent/pom.xml
- kubernetes-maven-plugin/pom.xml
- openshift-maven-plugin/pom.xml
- pom.xml
Updated Jackson to 2.10.0
Updated commons-compress to v1.19
> Updated commons-compress to v1.19 & jackson to 2.10.0

- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojo.java
> fix: Docker builds are supported in oc-maven-plugin

- .github/workflows/integration-tests.yml
Signed-off-by: Marc Nuri <marc@marcnuri.com>
> fix: Report consolidation/artifact generation in GitHub Actions

- MIGRATION-GUIDE.md
> Added Migration guide for Fabric8 Maven Plugin users

- .github/workflows/integration-tests.yml
Signed-off-by: Marc Nuri <marc@marcnuri.com>
> test: fix not enough resources when running tests in oc 3.11

- CHANGELOG.md
- scripts/extract-changelog-for-version.sh
Simple script to extract changelog excerpts for a specific version and create GitHub compatible links.
Usage:
```
./scripts/extract-changelog-for-version.sh 0.1.1
```
> ci: Script to extract changelog portions and build links for notifications

- .github/workflows/integration-tests.yml
- CHANGELOG.md
This is an port of PR https://github.com/eclipse/jkube/pull/40. Contributer
didn't sign Eclipse Contributor agreement.
> Github Actions checkout v2

- .circleci/config.yml
- pom.xml
> chore: JaCoCo coverage gets picked up by Sonar

- quickstarts/maven/quarkus/README.md
- quickstarts/maven/quarkus/pom.xml
- quickstarts/maven/quarkus/src/main/java/org/eclipse/jkube/quickstart/quarkus/rest/CoolApplication.java
Updated Quarkus Quickstart and added checked native example instructions.
Relates to #30
> doc: Quarkus Native Quickstart

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/PushMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
Fix #92 
Looks like `AuthConfigFactory` wasn't getting initialized properly.
> Fix #92: NullPointerException in AuthConfigFactory

- CHANGELOG.md
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/FileDataSecretEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java
Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1792
>  Added NullCheck in FileDataSecretEnricher

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
- quickstarts/maven/external-resources/pom.xml
- quickstarts/maven/hello-world/pom.xml
- quickstarts/maven/ibm-javaee8-webprofile-liberty/javaee8-webprofile-liberty-app-it/pom.xml
- quickstarts/maven/ibm-javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/pom.xml
- quickstarts/maven/ibm-javaee8-webprofile-liberty/pom.xml
- quickstarts/maven/openliberty/pom.xml
- quickstarts/maven/quarkus/pom.xml
- quickstarts/maven/spring-boot-dekorate/pom.xml
- quickstarts/maven/spring-boot/pom.xml
- quickstarts/maven/thorntail/pom.xml
- quickstarts/maven/vertx/pom.xml
- quickstarts/maven/webapp-jetty/pom.xml
- quickstarts/maven/webapp/pom.xml
- quickstarts/maven/xml-config/pom.xml
- quickstarts/maven/yaml-only/pom.xml
- quickstarts/maven/zero-config/pom.xml
I noticed this while running hello-world sample when some
user pinged us on gitter that it's broken. The user seemed to be
using an older version but we're facing NullPointerException on v0.2.0
> Fix NullPointerException in DockerAssemblyManager

- CHANGELOG.md
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1802
> Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1802

- README.md
Signed-off-by: Rodney <rdruss@gmail.com>
> Fix PascalCase for OpenShift

- README.md
Links to kubernetes and openshift plugin documentation updated.
> k8s & openshift plugin link updated

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/JKubeTarArchiver.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/FileUtilTest.java
Fix #112 
Fix Windows specific path parsing error
> Fix #112: Quarkus Error while trying to build the image: Unexpected internal error near index 1

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmMojo.java
> feature: helm support for OpenShift

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManagerTest.java
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MavenUtil.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
> Fix #88: Resolve unreachable statement in DockerAssemblyManager#ensureThatArtifactFileIsSet

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ServiceAccountConfig.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ServiceAccountEnricherTest.java
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_access.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_compatibility.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_java_exec.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-apply.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-debug.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-log.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-watch.adoc
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
- openshift-maven-plugin/doc/src/main/asciidoc/inc/_access.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/generator/_java_exec.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-apply.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-debug.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-log.adoc
- openshift-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-watch.adoc
- openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
Fix #75 
Updated docs as per existing codebase
> Fix #75: Configuration mismatch between docs and code

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
- quickstarts/maven/spring-boot/pom.xml
> fix: dependency version convergence error

- jkube-kit/parent/pom.xml
Signed-off-by: anandkrsingh <ansingh@redhat.com>
This PR updates k8s-client to latest version i.e 4.9.0
> updated k8s-client version to latest

- CHANGELOG.md
- jkube-kit/resource/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java
- jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojo.java
> Fix #152: Namespace ignored during debug goal

- CHANGELOG.md
- jkube-kit/parent/pom.xml
Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1810
> Update Fabric8 Base Images to latest version

- jkube-kit/doc/src/main/asciidoc/inc/diagrams/module-overview.puml
> doc: #90 Updated module overview diagram to current status

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/ConfigHelper.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/generator/GeneratorManager.java
- quickstarts/maven/docker-file-provided/README.md
- quickstarts/maven/docker-file-provided/pom.xml
- quickstarts/maven/docker-file-provided/src/main/docker-context-dir/Dockerfile
- quickstarts/maven/docker-file-provided/src/main/docker-context-dir/other/file/DockerfileWithChangedFileName
- quickstarts/maven/docker-file-provided/src/main/docker/Dockerfile
- quickstarts/maven/docker-file-provided/src/main/docker/subdir/Dockerfile
> doc: Updated external Dockerfile quick start example to showcase all options

- CHANGELOG.md
- jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java
> Fix #167: Add CMD argument for Wilfly based applications

- CHANGELOG.md
- jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java
- quickstarts/maven/webapp-wildfly/README.md
- quickstarts/maven/webapp-wildfly/pom.xml
- quickstarts/maven/webapp-wildfly/src/main/webapp/index.html
+ Change wildfly CMD command in WildflyAppServerHandler
+ Add Webapp Wildfly Sample
> Fix #167: Change Wildfly CMD to allow allow external requests

- pom.xml
Signed-off-by: anandrkskd <anandrkskd@gmail.com>
This PR updates Junit to version 4.13
CQ : https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22098 :heavy_check_mark:
> Update junit to 4.13

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultNamespaceEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/DeploymentConfigEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ProjectEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ImageEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/MavenProjectEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/RevisionHistoryEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java
- jkube-kit/parent/pom.xml
- jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojo.java
> chore: bump kubernetes-client from 4.9.1 to 4.10.1

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
Signed-off-by: anandrkskd <anandrkskd@gmail.com>
This PR moved from cascading to PropagationPolicy, as cascading is now marked  as deprecated.
> moved from cascading to PropagationPolicy

- CHANGELOG.md
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
Fix #222 
Signed-off-by: James Carman <jwcarman@gmail.com>
> Fix #221: Role Resources Not Supported by Kubernetes Cluster Configurations

- quickstarts/kit/docker-image/pom.xml
- quickstarts/kit/docker-image/src/main/java/org/eclipse/jkube/quickstart/kit/docker/Main.java
- quickstarts/kit/docker-image/static/hello-docker.txt
Updated quickstart to include static files in Docker build
> doc: Updated quickstart to include static files in Docker build

- CHANGELOG.md
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/RevisionHistoryEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/DeploymentConfigEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/DeploymentConfigEnricherTest.java
- jkube-kit/parent/pom.xml
> Upgrade Kubernetes Client to v4.10.2

- .github/workflows/e2e-tests.yml
- CHANGELOG.md
Upgrade Minikube version to 1.18.3
> ci: Upgrade E2E Minikube to 1.18.3

- .github/workflows/e2e-tests.yml
ci: updated e2e workflow to enable dockerfile tests
> ci: updated e2e workflow to enable dockerfile tests

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/service/MigrateService.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/XMLUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/service/MigrateServiceTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/XMLUtilTest.java
- jkube-kit/common/src/test/resources/test-project-profile/pom.xml
- jkube-kit/common/src/test/resources/test-project/pom.xml
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/MigrateMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/OpenShiftMigrateMojo.java
> Fix #195: Added MigrateMojo for migrating projects from FMP

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
> unit tests for jkube-kit/common dir

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
- jkube-kit/common/src/test/resources/util/spring-boot-application.properties
> unit test for sprintbootutil added

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/OpenshiftHelperTest.java
Increase coverage for OpenShiftHelper in scope of #207
> Unit test for Openshifthelper

- .github/pull_request_template.md
Update PR template to add new "Chore" choice
Type of change is used to calculate semver2 version and should **never** be omitted.
> chore: Update PR template to add new "Chore" choice

- .github/ISSUE_TEMPLATE.md
> Chore: Add Issue template for Github issues

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtilsTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/service/MigrateServiceTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/FileUtilTest.java
[jkube-kit/common](https://github.com/eclipse/jkube/tree/master/jkube-kit/common) unit [tests](https://github.com/eclipse/jkube/tree/master/jkube-kit/common/src/test) run on windows platform
> test: fix kit-common unit tests run on windows platform

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerFileUtil.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/JKubeDockerfileInterpolator.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerFileUtilTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/JKubeDockerfileInterpolatorTest.java
- jkube-kit/build/service/docker/src/test/resources/interpolate/Dockerfile_1.expected
- jkube-kit/build/service/docker/src/test/resources/interpolate/at/Dockerfile_1
- jkube-kit/build/service/docker/src/test/resources/interpolate/at/Dockerfile_1.expected
- jkube-kit/build/service/docker/src/test/resources/interpolate/none/Dockerfile_1
- jkube-kit/build/service/docker/src/test/resources/interpolate/none/Dockerfile_1.expected
- jkube-kit/build/service/docker/src/test/resources/interpolate/var/Dockerfile_1
- jkube-kit/build/service/docker/src/test/resources/interpolate/var/Dockerfile_1.expected
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
- quickstarts/maven/docker-file-provided/pom.xml
- quickstarts/maven/docker-file-provided/src/main/docker/subdir/Dockerfile
> Fix #246: Dockerfile custom interpolation is broken

- CHANGELOG.md
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-apply.adoc
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftResourceMojo.java
> Fix #259: Cleanup Unused properties inside Mojos

- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerFileUtilTest.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenConfigurationExtractorTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ConfigsTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/AsciiDocParserTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ClassUtilTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/CommandlineTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtil.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/model/KindAndNameTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtilTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/InitContainerHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ConfigMapEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DependencyEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/PortNameEnricherTest.java
- jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricher.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/PrometheusEnricherTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/AbstractPortsExtractorTest.java
- jkube-kit/profile/src/test/java/org/eclipse/jkube/kit/profile/ProfileUtilTest.java
This PR addresses various code smells inside tests mostly related to assertions wherever possible.
> Chore: Fix Sonar code smells in tests

- .github/workflows/license.yml
- pom.xml
- quickstarts/kit/docker-image/static/hello-docker.txt
- quickstarts/maven/docker-file-simple/static-dir-in-project-root/my-file.txt
> Fix #281: Add license header check

- .github/workflows/e2e-tests.yml
- CHANGELOG.md
chore: Update GH workflow dependencies + add missing changelog line
> chore: Update GH workflow dependencies + add missing changelog line

- quickstarts/maven/zero-config/pom.xml
I think we forgot to update our samples after we updated
our base images to JDK11
deployed Pod was crashing with this error:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.boot.autoconfigure.web.ServerProperties org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.properties; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverProperties' defined in class path resource [org/springframework/boot/autoconfigure/web/ServerPropertiesAutoConfiguration.class]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
at org.springframework.beans.factory.annotation.AutowiredAnnotation …
```
> Fix Zero Config Sample

- quickstarts/maven/thorntail/pom.xml
fix: Maven Thorntail Quickstart works on OpenShift and Kubernetes (JIB too)
> fix: Maven Thorntail Quickstart works on OpenShift and Kubernetes (JIB too)

- CHANGELOG.md
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageConfiguration.java
Refactor ImageConfiguration, fix #286.
> fix: Refactor ImageConfiguration

- quickstarts/maven/quarkus-customized-image/pom.xml
fix: Quarkus custom image assembly config up to date
> fix: Quarkus custom image assembly config up to date

- quickstarts/maven/external-resources/pom.xml
- quickstarts/maven/spring-boot-helm/pom.xml
external-resources+spring-boot-helm examples have complete ConfigChange trigger for DeploymentConfig
> fix: external-resources+spring-boot-helm examples have complete ConfigChange trigger for DeploymentConfig

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ProjectClassLoadersTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java
Signed-off-by: anandrkskd <anandrkskd@gmail.com>
Fixes #207 
> Unit test added for UserConfiguration and ProjectClassLoader

- README.md
chore: Update readme to align description with the website one
- Added links for Katacoda scenarios
[Badge source](https://img.shields.io/badge/--%233b434b?logoWidth=70&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAAAVCAYAAACwnEswAAAN6ElEQVRoQ+1ZeVRUR9b/ve7XDTQNyK7Q0AoIIi2bQMSYERXiCipqxiXGJY7J+E1QXI7yJToRjHEUV8Yh0ShMYjAZYyJKMICCgYkKrQKNAWRRkE22Bmy2pun35tQL7bQEt+R8/3zHOqfPqVd169Z9v9+9t269pvD0xtu8NWrDv06fSbt/v+LnZ8jqpikA7HPKvhQbhAAB74nt9FdffZ517IPlPuERcB/nLQ+fP2+BUqmsedKCd97586qDB/d/IhKJhgHoeYn2iyPwVELa29tV6lgvsQENfKlQY9j8vbCwts2ZOWP6TAK4hYWF2GLECImft7f3e+vWrVUUFkx+44+LWUtLS0LIwxc35+WKpxFC1dfXaw0/DaTev6jCW36GGDdciI+usdjyZT5bVlZGZWRk4K4iF+lX89HQ0IBAmTOSM69BIBCou7q6lHl5N+Xz5oUufhktz+9oTyXk7t27WnHCFGpvVhe6NQzWTjCCi6UA2fd6ca2aRUxmI04skOB …
> chore: Update readme to align description with the website one

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceTest.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
- jkube-kit/parent/pom.xml
> Chore: Bump Fabric8 Kubernetes Client to v4.10.3

- README.md
- jkube-kit/README.md
- jkube-kit/doc/src/main/asciidoc/inc/diagrams/module-overview.puml
Diagram will be revisited in #330
> Remove outdated jkube-kit diagram from readme

- quickstarts/maven/spring-boot/README.md
Fixed some typos and updated "Minishift/Minikube" to match the order illustrating in readme
Signed-off-by: Cary Wu <cary205@gmail.com>
> update Spring Boot Sample readme

- CHANGELOG.md
- quickstarts/maven/spring-boot-camel-complete/README.md
- quickstarts/maven/spring-boot-camel-complete/pom.xml
- quickstarts/maven/spring-boot-camel-complete/src/main/java/org/eclipse/jkube/quickstart/springboot/camel/log/Application.java
- quickstarts/maven/spring-boot-camel-complete/src/main/java/org/eclipse/jkube/quickstart/springboot/camel/log/CamelRouteBuilder.java
- quickstarts/maven/spring-boot-camel-complete/src/main/java/org/eclipse/jkube/quickstart/springboot/camel/log/CamelServletConfiguration.java
- quickstarts/maven/spring-boot-camel-complete/src/main/java/org/eclipse/jkube/quickstart/springboot/camel/log/OrderGenerator.java
- quickstarts/maven/spring-boot-camel-complete/src/main/resources/application.properties
- quickstarts/maven/spring-boot-camel-complete/src/main/resources/data/order1.xml
- quickstarts/maven/spring-boot-camel-complete/src/main/resources/data/order2.xml
- quickstarts/maven/spring-boot-camel-complete/src/main/resources/data/order3.xml
- quickstarts/maven/spring-boot-camel-complete/src/main/resources/data/order4.xml
- quickstarts/maven/spring-boot-camel-complete/src/main/resources/data/order5.xml
Maven Quickstart for Spring-Boot with complete Camel integration
> fix: Maven Quickstart for Spring-Boot with complete Camel integration

- CHANGELOG.md
- jkube-kit/build/service/jib/pom.xml
- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java
fix: pull from insecure registries and pull registry authentication for JIB
Fix #336 
> fix: pull from insecure registries and pull registry authentication for JIB

- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_access.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_authentication.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/build/_configuration.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/build/_overview.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/_goals.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-build.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/image/_configuration.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/image/_example.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/image/_naming.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/push/_overview.adoc
+ Removed parameters: healthChecks, loadNameParameters, portPropertyFile since they are not referenced in code
+ Remove `<run>` and `<external>` from Image Configuration docs
+ Added missing ImageName configuration section. We don't need to add Container Names
and Name Patterns since image builds don't really work with patterns and we don't
manipulate individual containers while doing a hot reload during watch(we're updating
image which triggers a rolling update).
> Fix #260: Add/remove missing/outdated documentation from DMP

- quickstarts/README.md
- quickstarts/kit/docker-image/pom.xml
- quickstarts/maven/docker-file-provided/pom.xml
- quickstarts/maven/docker-file-simple/pom.xml
- quickstarts/maven/external-resources/pom.xml
- quickstarts/maven/hello-world/pom.xml
- quickstarts/maven/ibm-javaee8-webprofile-liberty/javaee8-webprofile-liberty-app-it/pom.xml
- quickstarts/maven/ibm-javaee8-webprofile-liberty/javaee8-webprofile-liberty-app/pom.xml
- quickstarts/maven/ibm-javaee8-webprofile-liberty/pom.xml
- quickstarts/maven/karaf-camel-log/pom.xml
- quickstarts/maven/openliberty/pom.xml
- quickstarts/maven/quarkus-customized-image/pom.xml
- quickstarts/maven/quarkus/pom.xml
- quickstarts/maven/spring-boot-camel-complete/pom.xml
- quickstarts/maven/spring-boot-crd/pom.xml
- quickstarts/maven/spring-boot-dekorate/pom.xml
- quickstarts/maven/spring-boot-helm/pom.xml
- quickstarts/maven/spring-boot-watch/pom.xml
- quickstarts/maven/spring-boot-with-jib/pom.xml
- quickstarts/maven/spring-boot/pom.xml
- quickstarts/maven/thorntail/pom.xml
- quickstarts/maven/vertx/pom.xml
- quickstarts/maven/webapp-jetty/pom.xml
- quickstarts/maven/webapp/pom.xml
- quickstarts/maven/wildfly-jar/pom.xml
- quickstarts/maven/xml-config/pom.xml
- quickstarts/maven/yaml-only/pom.xml
- quickstarts/maven/zero-config/pom.xml
- scripts/quickstarts.sh
feat: quickstart JKube version can be set with `jkube.version` property
> feat: quickstart JKube version can be set with `jkube.version` property

- quickstarts/kit/docker-image/pom.xml
- quickstarts/maven/docker-file-provided/README.md
- quickstarts/maven/docker-file-provided/pom.xml
- quickstarts/maven/docker-file-simple/pom.xml
- quickstarts/maven/external-resources/pom.xml
- quickstarts/maven/hello-world/README.md
- quickstarts/maven/hello-world/pom.xml
- quickstarts/maven/ibm-javaee8-webprofile-liberty/pom.xml
- quickstarts/maven/karaf-camel-log/pom.xml
- quickstarts/maven/openliberty/pom.xml
- quickstarts/maven/openliberty/src/test/java/org/eclipse/jkube/itests/SampleIT.java
- quickstarts/maven/quarkus-customized-image/pom.xml
- quickstarts/maven/quarkus/README.md
- quickstarts/maven/quarkus/pom.xml
- quickstarts/maven/spring-boot-camel-complete/pom.xml
- quickstarts/maven/spring-boot-crd/pom.xml
- quickstarts/maven/spring-boot-dekorate/pom.xml
- quickstarts/maven/spring-boot-helm/pom.xml
- quickstarts/maven/spring-boot-watch/pom.xml
- quickstarts/maven/spring-boot-with-jib/pom.xml
- quickstarts/maven/spring-boot/pom.xml
- quickstarts/maven/thorntail/pom.xml
- quickstarts/maven/vertx/pom.xml
- quickstarts/maven/webapp-jetty/pom.xml
- quickstarts/maven/webapp-wildfly/pom.xml
- quickstarts/maven/webapp/pom.xml
- quickstarts/maven/wildfly-jar/pom.xml
- quickstarts/maven/xml-config/pom.xml
- quickstarts/maven/yaml-only/pom.xml
- quickstarts/maven/zero-config/pom.xml
fix: Added descriptions to every quickstart project
> fix: Added descriptions to every quickstart project

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojoTest.java
Signed-off-by: Danipiario <daniele.pirola@icteam.it>
see #407 
> settings recreate flag in ApplyService

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MavenUtil.java
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MojoExecutionService.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
> Fix #365: jkube.watch.postGoal property/parameter/configuration is ignored

- quickstarts/kit/dynamic-docker-image-file-multi-layer/README.md
- quickstarts/kit/dynamic-docker-image-file-multi-layer/pom.xml
- quickstarts/kit/dynamic-docker-image-file-multi-layer/src/main/java/org/eclipse/jkube/quickstart/kit/docker/dynamic/DynamicDockerfileGenerator.java
- quickstarts/kit/dynamic-docker-image-file-multi-layer/src/main/java/org/eclipse/jkube/quickstart/kit/docker/dynamic/Main.java
- quickstarts/kit/dynamic-docker-image-file-multi-layer/src/main/other-directory/some-resource.txt
- quickstarts/kit/dynamic-docker-image-file-multi-layer/src/main/static/hello-docker-other.txt
- quickstarts/kit/dynamic-docker-image-file-multi-layer/src/main/static/hello-docker.txt
Quickstart showing how to use JKube kit to dynamically generate a multilayered Docker image
CC: @alvarosanchez
> doc: Quickstart showing how to use JKube kit to dynamically generate a multilayered Docker image

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/GavLabel.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/watch/WatchContext.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/TimeUtil.java
- jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
fix: Remove Sonar warnings after #400 + add link to new Issue
> fix: Remove Sonar warnings after #400 + add link to new Issue

- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-helm.adoc
fix #363: Improved helm docs for multi-module projects
cc: @hlavki
> fix: Improved helm docs for multi-module projects

- CHANGELOG.md
- quickstarts/maven/micronaut-customized-image/README.md
- quickstarts/maven/micronaut-customized-image/pom.xml
- quickstarts/maven/micronaut-customized-image/src/main/java/org/eclipse/jkube/quickstart/micronaut/custom/Application.java
- quickstarts/maven/micronaut-customized-image/src/main/java/org/eclipse/jkube/quickstart/micronaut/custom/Resource.java
- quickstarts/maven/micronaut-customized-image/src/main/jkube/deployment.yml
- quickstarts/maven/micronaut-customized-image/src/main/resources/application.yml
- quickstarts/maven/micronaut-customized-image/src/main/resources/logback.xml
fix: Added quickstart for Micronaut framework
cc: @alvarosanchez this should be the foundation for a future https://github.com/micronaut-projects/micronaut-starter PR follow-up
> fix: Added quickstart for Micronaut framework

- .github/workflows/e2e-tests.yml
`master` branch was renamed in https://github.com/jkubeio/jkube-integration-tests.
Updated references in E2E test workflows
> fix: eclipse/jkube#275 Eradicating problematic language

- quickstarts/maven/wildfly-jar/pom.xml
Signed-off-by: JF Denise jdenise@redhat.com
Upgrade dependencies, remove env variables that are added by the generator starting JKube 1.0.1
> Fix for Issue #441, Upgrade quickstart to use WildFly JAR 2 Final release

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java
Replacing anonymous Runnables with lambdas in WatchService.java, as of Java 8 we have Lambdas in place. Tried to replace anonymous runnable.
Fixes https://github.com/eclipse/jkube/issues/370
> Replacing anonymous Runnables with lambdas in WatchService

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/ContainerTracker.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerCreateConfig.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerHostConfig.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/OpenshiftHelper.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java
- jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/MainClassDetector.java
closes [https://github.com/eclipse/jkube/issues/462](https://github.com/eclipse/jkube/issues/462)
> Refactor occurrences across codebase to use isEmpty()

- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/AnsiLogger.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ClassUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PluginServiceFactory.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamService.java
Signed-off-by: dengliming <liming.d.pro@gmail.com>
closes [https://github.com/eclipse/jkube/issues/470](https://github.com/eclipse/jkube/issues/470)
> Replace the type specification in this constructor call with the diamond operator (`<>`) across codebase

- pom.xml
> chore: maven-surefire-plugin 3.0.0-M5

- jkube-kit/common/src/main/resources/META-INF/jkube/kind-filename-type-mapping-default.adoc
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/kind-filename-type-mapping-default.adoc
- openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/kind-filename-type-mapping-default.adoc
Signed-off-by: David Marsden <david.marsden@inacta.ch>
> adds typo fix. changes persitemtvolumeclaim to persistentvolumeclaim

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerCreateConfig.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerHostConfig.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/PortMapping.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/ExternalConfigHandler.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
Partial fix for [https://github.com/eclipse/jkube/issues/471](https://github.com/eclipse/jkube/issues/471)
> Remove the declaration of thrown runtime exceptions across codebase.

- jkube-kit/parent/pom.xml
> fix: "TestEngine with id 'junit-vintage' failed to discover tests" after dependency upgrades

- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
- jkube-kit/parent/pom.xml
Fix #270: Update Jib Core to v0.16.0
> Fix #270: Update Jib Core to v0.16.0

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtilTest.java
Signed-off-by: dengliming <liming.d.pro@gmail.com>
closes [https://github.com/eclipse/jkube/issues/461](https://github.com/eclipse/jkube/issues/461)
> Simplify assertions in GoTimeUtilTest

- CHANGELOG.md
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java
- jkube-kit/build/api/src/test/resources/interpolate/Dockerfile_with_params
> Fix #485: Filter with placeholders in Dockerfile is broken

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PodLogService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
- jkube-kit/enricher/api/src/test/resources/jkube/network-v1-ingress.yml
- jkube-kit/parent/pom.xml
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojo.java
Fix #387
+ Updated Kubernetes Client to v4.13.0
+ Added a test to verify `networking.k8s.io/v1` `Ingress` is loaded
CQs:
> Update Kubernetes Client to v4.13.0

- CHANGELOG.md
- jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
- jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
fix #473: Debug goals work with QuarkusGenerator generated container images
> fix: Debug goals work with QuarkusGenerator generated container images

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ClassUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ClassUtilTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PodLogService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/PatchServiceTest.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
- jkube-kit/parent/pom.xml
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojo.java
- quickstarts/kit/custom-istio-enricher/pom.xml
> Update Fabric8 Kubernetes Client to v5.0.0-beta-1

- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/KeyStoreUtilLoadPrivateKeyTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/KeyStoreUtilTest.java
Signed-off-by: Alejandro Martínez <alex1983bcn@gmail.com>
closes: #472 
> Fix: Refactor tests in `KeyStoreUtilTest` to avoid duplication (#472)

- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MavenUtil.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
Fix #146: ApplyMojo now uses ApplyService from JKubeServiceHub
+ Moved applyEntities logic as static methods in ApplyService in order to make ApplyMojo slim
> Fix #146: ApplyMojo should use ApplyService in JKubeServiceHub

- CHANGELOG.md
- jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricher.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricherTest.java
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_service_discovery.adoc
fix: follow-up of ServiceDiscoveryEnricher from FMP (#509)
cc: @rnetuka 
> fix: follow-up of ServiceDiscoveryEnricher from FMP (#509)

- CHANGELOG.md
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/BuildConfigurationTest.java
fix: #521 follow-up -> tests + changelog entry
> fix: #521 follow-up -> tests + changelog entry

- jkube-kit/parent/pom.xml
> Update Fabric8 Kubernetes Client to v5.0.0

- jkube-kit/jkube-kit-thorntail-v2/src/test/java/org/eclipse/jkube/thorntail/v2/enricher/ThorntailV2HealthCheckEnricherTest.java
fix test issue with JDK 11 (required for #562)
> test: fixed compatibility with JDK > 8

- quickstarts/maven/docker-file-simple/README.md
- quickstarts/maven/spring-boot-with-jib/README.md
This fix/improves doc for `docker-file-simple` and `spring-boot-with-jib` quickstarts:
- Add `package` goal before mvn k8s:build to ensure JAR is present before creating the container
- Use `https://index.docker.io/v1` instead of `docker.io` in `settings.xml`
> Update READMEs for better user experience

- .github/workflows/e2e-tests.yml
ci: openshift workflow runs on Ubuntu 18.04
- bumped Minikube version + Kubernetes
> ci: openshift workflow runs on Ubuntu 18.04

- CHANGELOG.md
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/parent/pom.xml
+ Bump Fabric8 Kubernetes Client to v5.2.1
CQs:
> Chore: Update Fabric8 Kubernetes Client to v5.2.1

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ExposeEnricher.java
~~According to docs https://www.eclipse.org/jkube/docs/openshift-maven-plugin#resource-route-generation, Openshift services should be exposed by default. Only when you add expose=false label, no routes will be generated.~~
ExposeEnricher should propagate expose: true label to RouteEnricher for services exposed by default (running on port 80 etc.) Routes should be generated for such services.
Actual behavior:
~~If no expose label is provided, the check _isExposedService(serviceMetadata)_ returns false and no route is created.~~
ExposeEnricher doesn't propagate expose: true label to RouteEnricher. The check _isExposedService(serviceMetadata)_ returns false and no route is created.
Fix proposal:
~~If no expose label is provided, add it by default to expose=true~~
Propagate expose: true label …
> Make expose labels created by ExposeEnricher persistent

- CHANGELOG.md
- jkube-kit/common/src/main/resources/META-INF/jkube/kind-filename-type-mapping-default.adoc
- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceVersioning.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
- jkube-kit/enricher/api/src/test/resources/jkube/networking-v1-np.yml
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/kind-filename-type-mapping-default.adoc
- openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/kind-filename-type-mapping-default.adoc
Supersedes and closes #620
cc: @marespane (I had to open a new PR because I can't add more commits to yours)
>  Add deployment of NetworkPolicy to kubernetes-maven-plugin (reviewed)

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogDispatcher.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/compose/DockerComposeServiceWrapper.java
- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/AbstractPortsExtractor.java
Fixes #634 
Replace occurences of keySet() with entrySet() when value are needed
> Replace occurences of keySet() with entrySet() when value are needed

- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmRepository.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojoTest.java
fix: Maven properties override/complement XML configuration for HelmPushMojo
> fix: Maven properties override/complement XML configuration for HelmPushMojo

- .circleci/config.yml
- CHANGELOG.md
Resolves #682 
This is a brand new Ubuntu-based image designed to install the very bare minimum. All of the next-generation convenience images that we will be releasing in the coming weeks are based on this image.
✔️ Faster spin-up time
✔️ Improved reliability and stability
> Update CircleCI image to new version

- CHANGELOG.md
- jkube-kit/generator/karaf/src/main/java/org/eclipse/jkube/generator/karaf/KarafGenerator.java
- jkube-kit/generator/karaf/src/test/java/org/eclipse/jkube/generator/karaf/KarafGeneratorTest.java
> KarafGenerator misses jolokia port 8778 #677

- CHANGELOG.md
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_karaf.adoc
Resolves #622
Updated **`jkube-healthcheck-karaf`** from `jkube.healthcheck-karaf` in the documentation.
> chore: Corrected jkube-healthcheck-karaf in doc

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerCreateConfig.java
- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/DefaultImageLookup.java
- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/AbstractPortsExtractor.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmDependencyTest.java
Remove some of the most recent bugs reported by Sonatype
> chore: Remove blocker bugs introduced in recent commits

- CHANGELOG.md
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/UndeployService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftUndeployService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftUndeployServiceTest.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultNamespaceEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultNamespaceEnricherTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojoTest.java
Fix #671 
Refactor ApplyService to consider namespace in resource metadata over the default namespace to enable applying resources in multiple namespaces
+ When no namespace is configured via XML or property, namespace gets picked from clusterAccess.getNamespace
+ When no namespace is configured via XML or property, but namespace is set in resource fragments, that particular namespace would be picked for those specific resources. Other resources would have clusterAccess.getNamespace namespace picked
+ When user provides namespace via `jkube.namespace` property. ALL resources are applied into namespace specified via `jkube.namespace`  property
> Fix #671: ApplyMojo not considering namespace configured from XML configuration

- quickstarts/maven/quarkus/README.md
- quickstarts/maven/quarkus/pom.xml
doc: Updated Quarkus quickstart
This PR updates the quickstart to take advantage of the new configuration inference features introduced in JKube 1.3.0.
> doc: Updated Quarkus quickstart

- CHANGELOG.md
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java
> fix: JIB assembly works on Windows

- CHANGELOG.md
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java
- jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/templates/kubernetes.yaml
- jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/values.yaml
- jkube-kit/resource/helm/src/test/resources/it/expected/openshift/values.yaml
- jkube-kit/resource/helm/src/test/resources/it/sources/global-template.yml
- jkube-kit/resource/helm/src/test/resources/it/sources/kubernetes/kubernetes.yml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/helm/templates/helm-and-fragments-deployment.yaml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/helm/values.yaml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/deployment.yml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/template.yml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/verify.groovy
- quickstarts/maven/spring-boot-helm/README.md
- quickstarts/maven/spring-boot-helm/pom.xml
- quickstarts/maven/spring-boot-helm/src/main/jkube/deployment.yml
- quickstarts/maven/spring-boot-helm/src/main/jkube/template.yaml
feat: Helm support for Golang expressions
- Allows the usage of Golang expressions in Helm variables
- Just like the rest of Helm placeholders can be used in fields which are deserialized into String variables of a given Kubernetes POJO type (e.g. won't work for Deployment.spec.replicas)
- An expression such as `{{ .Values.field | default "a value" }}` because of the extra quotes that will have trouble when deserializing the generated Helm charts
To use the new feature:
**template.yml**
```yaml
kind: Template
parameters:
- name: value_to_process
value: I'll be processed
- name: golang_expression
value: "{{ .Values.value_to_process | upper | quote }}"
```
**deployment.yml**
```yaml
metadata:
annotations:
test: ${golang_expression}
```
Will produce a **templates/artifactId-deployment.yml** …
> feat: Helm support for Golang expressions

- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-helm-push.adoc
doc: fix typo on `k8s:helm-push` goal title
> doc: fix typo on k8s:helm-push goal title

- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/SystemPropertyRegistryAuthHandlerTest.java
Assertions changed: Junit -> AssertJ
> assertion: junit -> assertj

- CHANGELOG.md
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/build/_assembly.adoc
doc: Add documentation for new multi-layer support
Follow-up of #724 
Related to #425
> doc: Add documentation for new multi-layer support

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/KeyStoreUtil.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/compose/ComposeUtils.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/DeepCopy.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerPathUtil.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/LocalSocketUtil.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/RequestUtil.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/VolumeBindingUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Base64Util.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ClassUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/CommandLine.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/IoUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompare.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ValidationUtil.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/Constants.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/SecretConstants.java
- jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/Constants.java
> Fixes issue #741. Private constructor added to Utility classes.

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/ConfigKey.java
- pom.xml
> Fixed SonarCloud vulnerability

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogRequestor.java
This PR is fixing issue #762 
(fix #762)
> LogRequestor.java: Add the missing @Override annotation

- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
ISSUE NO. #746 
SIMPLE FIELD TYPES Changed To Private!
> SIMPLE-FIELD-TYPES Changed To Private

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
Fix #784 
Replacing hamcrest with AssertJ
> RamananR : FIX #784 :  Replacing hamcrest with AssertJ

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/util/AbstractNativeSocketFactory.java
> reordered access modifier and visibility of constructor

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
refactor: Follow-up on #798, Resource Mojo resolves Image configuration from utils
> refactor: Follow-up on #798, Resource Mojo resolves Image configuration from utils

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/JKubeBuildTarArchiver.java
> Fixed issue #773: deleting unused imports

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTaskTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java
- quickstarts/gradle/docker-file-provided-context-and-assembly/build.gradle
- quickstarts/gradle/docker-file-provided-context-and-file/build.gradle
- quickstarts/gradle/docker-file-provided-context-dir/build.gradle
- quickstarts/gradle/docker-file-simple/build.gradle
- quickstarts/gradle/spring-boot/build.gradle
refactor: follow-up changes after Dockerfile build implementation (#810)
> refactor: follow-up changes after Dockerfile build implementation

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GroovyUtil.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GroovyUtilTest.java
feat: gradle config can have nested closures as maps
> feat: gradle config can have nested closures as maps

- gradle-plugin/it/src/it/extension-configuration/build.gradle
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/KubernetesExtensionIT.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GroovyUtil.java
feat: gradle config can have GStrings
> feat: gradle config can have GStrings

- CHANGELOG.md
- quickstarts/maven/spring-boot-camel-complete/pom.xml
- quickstarts/maven/spring-boot-crd/pom.xml
- quickstarts/maven/spring-boot-dekorate/pom.xml
- quickstarts/maven/spring-boot-watch/pom.xml
- quickstarts/maven/spring-boot-with-jib/pom.xml
- quickstarts/maven/spring-boot/pom.xml
> Update Spring Boot Quickstarts to latest version

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/JKubeBuildTarArchiver.java
- jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherManager.java
> Removed unused imports

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/TemplateUtilTest.java
> TemplateUtilTest use Parameterized test with AssertJ

- gradle-plugin/it/src/it/extension-configuration/build.gradle
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/KubernetesExtensionIT.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtension.java
Relates to #835
Add configuration options to KubernetesExtension required for
KubernetesResourceTask
> Fix #835: KubernetesResourceTask: KubernetesExtension has required configuration options

- gradle-plugin/it/src/it/extension-configuration/build.gradle
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/KubernetesExtensionIT.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTask.java
- gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
- gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
Fix #835 
Add missing configuration left in #852
- Create a profiles-default.yml file in `gradle-plugin/openshift/src/main/resources/META-INF/jkube` with the same content found in the OpenShiftMavenPlugin equivalent
- Create a profiles-default.yml file in `gradle-plugin/kubernets/src/main/resources/META-INF/jkube` with the same content found in the KubernetesMavenPlugin equivalent
- KubernetesResourceTask overrides initJKubeServiceHubBuilder to provide a resourceService configuration
> Fix #835: (follow-up) Add missing configuration required for KubernetesResourceTask

- gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
- gradle-plugin/doc/src/main/asciidoc/inc/tasks/develop/_jkube-log.adoc
- gradle-plugin/doc/src/main/asciidoc/inc/tasks/develop/_tasks.adoc
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesPlugin.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTaskTest.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtension.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
Fix #851 
Add KubernetesLogTask to Kubernetes Gradle Plugin
> Fix #851: Add KubernetesLogTask to Kubernetes Gradle Plugin

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompare.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java
> Fix #844: UserConfigurationCompare.java: Use the built-in formatting to construct this argument

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JKubeFileInterpolator.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JKubeFileInterpolatorTest.java
Prerequisite for #837 
+ Rename JKubeDockerfileInterpolator -> JKubeFileInterpolator
+ DockerfileUtil file interpolation method moved to JKubeFileInterpolator
+ Move JKubeFileInterpolator to jkube-kit/common
> Pre-Requisite for #837: Move JKubeDockerfileInterpolator to jkube-kit/common

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ServiceConfig.java
> Removed unused import

- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/KubernetesExtensionIT.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/AbstractJKubePlugin.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesJKubeTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftBuildTask.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftJKubeTask.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftBuildTaskTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorTest.java
- quickstarts/gradle/quarkus-customized-image/README.md
- quickstarts/gradle/quarkus-customized-image/build.gradle
Misc. refactors and clean ups
Closes: #849
> Misc. refactors and clean ups

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DependencyEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DependencyEnricherTest.java
> Fix#469: replaced Java.net.URL with Java.net.URI

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java
This change addresses Issue #878. Changed try block to try-with-resources. Also replaced anonymous implementation with lambda
[Issue](https://github.com/eclipse/jkube/issues/878)
> Fix for try with resources issue #878

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyFiles.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManager.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/BuildDirs.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/BuildUtil.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/model/Container.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyConfigurationSourceTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/PathTestUtil.java
> Fix some typos in jkube-kit/build/api module

- quickstarts/maven/micronaut/pom.xml
- quickstarts/maven/micronaut/src/test/java/org/eclipse/jkube/quickstart/micronaut/custom/SimpleClient.java
- quickstarts/maven/micronaut/src/test/java/org/eclipse/jkube/quickstart/micronaut/custom/SimpleTest.java
Micronaut 2.1.0 -> Micronaut 3.0.0
https://docs.micronaut.io/3.0.0/guide/
> chore: quickstart Micronaut 3.0.0

- CHANGELOG.md
- jkube-kit/common/pom.xml
- jkube-kit/parent/pom.xml
- pom.xml
- quickstarts/kit/custom-istio-enricher/app/pom.xml
- quickstarts/kit/custom-istio-enricher/pom.xml
Fix #832 
deps: Bump jib-core to 0.20.0
> deps: Bump jib-core to 0.20.0

- gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
- gradle-plugin/doc/src/main/asciidoc/inc/tasks/build/_jkube-apply.adoc
- gradle-plugin/doc/src/main/asciidoc/inc/tasks/build/_tasks.adoc
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTaskTest.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtension.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java
Fix #881 
- Implement k8s:apply  maven equivalent funtionality for Kubernetes Gradle Plugin
- Documentation for KubernetesApplyTask and configuration options
Requires #884  to be merged first
> Fix #881: Add KubernetesApplyTask to kubernetes gradle plugin

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTaskTest.java
test: added coverage for KubernetesApplyTask
> test: added coverage for KubernetesApplyTask

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JKubeFileInterpolator.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtils.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/AsciiDocParser.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/OpenshiftHelper.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PluginServiceFactory.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ProcessUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompare.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java
> Fix some typos in jkube-kit/common module 

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
Fix some typos in kubernetes-maven-plugin
> Fix some typos in kubernetes-maven-plugin

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java
> InterruptedException handled

- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ITGradleRunner.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleLogger.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesJKubeTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTaskTest.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtension.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftApplyTask.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftBuildTask.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftJKubeTask.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftPushTask.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTask.java
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/AnsiLogger.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/AnsiLoggerTest.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/AnsiUtil.java
- quickstarts/gradle/spring-boot/build.gradle
fix #867: Ansi logging works on Gradle
> fix: Ansi logging works on Gradle

- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
> Updated file as per Issue #967

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuthConfig.java
> Removed redundant semi-colon

- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/NetworkConfig.java
> Remove redundant semi-colon

- gradle-plugin/doc/src/main/asciidoc/inc/tasks/_index.adoc
- gradle-plugin/doc/src/main/asciidoc/inc/tasks/build/_index.adoc
- gradle-plugin/doc/src/main/asciidoc/inc/tasks/build/_jkube-helm-push.adoc
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesPlugin.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginRegisterTaskTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTaskTest.java
Fix #1075
Port HelmPushMojo from maven plugins to KubernetesHelmPushTask
> Fix #1075: Implement `k8sHelmPush` task in Kubernetes Gradle Plugin

- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmPushTask.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginRegisterTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmPushTaskTest.java
Fix #1076 
(Should be merged once #1079 is merged)
Add `oc:helm-push` gradle equivalent `ocHelmPush` task to OpenShift Gradle Plugin. 
Ported OpenShiftHelmPushMojo to OpenShiftHelmPushTask in OpenShift Gradle Plugin.
> Fix #1076: Add `ocHelmPushTask` to OpenShift Gradle Plugin

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/ConfigHelper.java
in Dockerfile mode, print the Dockerfile path used for the build
Fix https://github.com/eclipse/jkube/issues/1054
Dockerfile provided in configuration:
Auto detected Dockerfile:
> feat: in Dockerfile mode, print the Dockerfile path used for the build

- scripts/quickstarts.sh
feat: Improve Quickstart scripts to include Gradle projects
> feat: Improve Quickstart scripts to include Gradle projects

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JKubeConfigurationTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JKubeFileInterpolatorTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtilsProcessAssemblyFileSetTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/BuildReferenceDateUtilTest.java
test: jkube-kit-common tests pass on Windows
> test: jkube-kit-common tests pass on Windows

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/PropertyConfigHandler.java
> Refactored boolean condition

- .circleci/config.yml
ci: chore: clear cache
There seems to be an issue with the current cache for the sonar job.
Clear the cache following: https://support.circleci.com/hc/en-us/articles/115015426888-Clear-project-dependency-cache
https://app.circleci.com/pipelines/github/eclipse/jkube/2263/workflows/de750fa4-775f-4797-8971-33e5b0b5557b/jobs/11684
> ci: chore: clear cache

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/portforward/PortForwardTask.java
Fix #966
Signed-off-by: attyuttam <attyuttam@gmail.com>
> added re-interrupt mechanism for issue 966

- CHANGELOG.md
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskEnvironment.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskEnvironment.java
> fix: Fix #1136 ConcurrentModificationException when running gradle k8sBuild on Quarkus sample

- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java
> WildflyJARGeneratorTest: Replace Collections.EMPTY_LIST with Collections.emptyList() first-timers-only good first issue . Good First Issue #1095

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ProcessorConfig.java
> added fix for 1091

- CHANGELOG.md
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ResourceUtilTest.java
- jkube-kit/common/src/test/resources/util/resource-util/list-with-standard-template-and-cr-resources.yml
- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceVersioning.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
- kubernetes-maven-plugin/it/src/it/fragments/expected/kubernetes.yml
- kubernetes-maven-plugin/it/src/it/fragments/src/main/jkube/customer-resource-definition-crd.yml
Fix #1167 
Replace apiextensions.k8s.io/v1beta1 by  apiextensions.k8s.io/v1 for CustomResourceDefinition
When running `mvn verify had to ignore the following tests because it was failing on file assertions due to absolute/relative path resolution issue. It does not seem to be related to the fix :
* AssemblyFileSetUtilsProcessAssemblyFileSetTest
* AssemblyManagerCreateDockerTarArchiveTest
* JibBuildServiceBuildIntegrationTest
> Fix #1167 : Replace apiextensions.k8s.io/v1beta1 by  apiextensions.k8s.io/v1

- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftBuildMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftWatchMojo.java
Fixed some typos in openshift-maven-plugin module
> Fixed some typos in openshift-maven-plugin module

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricherTest.java
> Resolve Issue#1161

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/Timestamp.java
> make static field final

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/GitEnricher.java
> make field final

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java
part of https://github.com/eclipse/jkube/issues/1142
> feat(gradle-plugin): log informative message when gradle jkube tasks are skipped #1142

- CHANGELOG.md
Closes #1142
Depends on #1198 and #1193 
> chore(changelog): Adding changelog for issue #1142 Log informative message whenever a goal/task is skipped

- jkube-kit/parent/pom.xml
- pom.xml
Bump lombok from 1.18.12 to 1.18.22
and 
maven-lombok-plugin from 1.18.12.0 to 1.18.20.0
Allowing compilation of JKube with java 17
> chore: Bump lombok from 1.18.12 to 1.18.22

- .gitignore
- CHANGELOG.md
- gradle-plugin/doc/src/main/asciidoc/inc/build/_configuration.adoc
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/DockerServiceHub.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RegistryService.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/BuildOptions.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/CreateImageOptions.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/DockerAccess.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/UrlBuilder.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClientMockitoTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClientTest.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/build/_configuration.adoc
- quickstarts/maven/xml-config/pom.xml
> feat: enable Create Image (pull) HTTP API options

- quickstarts/maven/micronaut-customized-image/pom.xml
- quickstarts/maven/micronaut/pom.xml
Fix #1227 
+ Update `jkube.image.version` property in micronaut-customized-image
quickstart
+ Remove unused property `jkube.image.version` in micronaut quickstart
> chore (quickstarts/maven) : Update `jkube.image.version` property in Micronaut maven quickstarts (#1227)

- gradle-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
- gradle-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_configmap_file.adoc
- gradle-plugin/doc/src/main/asciidoc/index.adoc
- gradle-plugin/it/src/it/configmap/build.gradle
- gradle-plugin/it/src/it/configmap/expected/kubernetes.yml
- gradle-plugin/it/src/it/configmap/expected/openshift.yml
- gradle-plugin/it/src/it/configmap/src/main/java/zero/Application.java
- gradle-plugin/it/src/it/configmap/src/main/java/zero/HelloController.java
- gradle-plugin/it/src/it/configmap/src/main/jkube/jkube-annotation-directory-configmap.yml
- gradle-plugin/it/src/it/configmap/src/main/jkube/jkube-annotation-file-configmap.yml
- gradle-plugin/it/src/it/configmap/src/test/resources/entries/first.properties
- gradle-plugin/it/src/it/configmap/src/test/resources/entries/second.properties
- gradle-plugin/it/src/it/configmap/src/test/resources/test-configmap.properties
- gradle-plugin/it/src/it/configmap/src/test/resources/test-jkube-configmap-annotation.properties
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ConfigMapIT.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ConfigMapEnricher.java
Fix #1210 
+ Add an integration test for ConfigMap resource generation in `gradle-plugin/it`
+ Add Documentation for ConfigMapEnricher
+ Refactor ConfigMapEnricher to rename methods with `**XMLConfiguration` names + change default opinionated configmap name to `jkubeconfig` from `xmlconfig`
I've created https://github.com/eclipse/jkube/issues/1252 for Enricher API documentation
> test (gradle-plugin) : Add ConfigMapIT gradle integration test for for verifying ConfigMap resource generation (#1210)

- CHANGELOG.md
- gradle-plugin/it/src/it/metadata/build.gradle
- gradle-plugin/it/src/it/metadata/expected/kubernetes-replicaset-controller.yml
- gradle-plugin/it/src/it/metadata/expected/kubernetes.yml
- gradle-plugin/it/src/it/metadata/expected/openshift.yml
- gradle-plugin/it/src/it/metadata/gradle.properties
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/DefaultMetadataIT.java
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/metadata/_jkube_metadata.adoc
Fix #1237 
+ Add integration test in `gradle-plugin/it` for default metadata
generation and labels/annotations configured from Groovy DSL
configuration.
+ Refactor asciidoc documentation for Gradle Plugins
> test (gradle-plugin) : Add gradle project intergration test for DefaultMetadataEnricher (#1237)

- CHANGELOG.md
- gradle-plugin/it/src/it/debug-mode/build.gradle
- gradle-plugin/it/src/it/debug-mode/expected/kubernetes.yml
- gradle-plugin/it/src/it/debug-mode/expected/openshift.yml
- gradle-plugin/it/src/it/debug-mode/gradle.properties
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/DebugModeIT.java
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/debug/_jkube_debug.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/debug/gradle/_debug_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/debug/maven/_debug_configuration.adoc
Fix #1214 #1271 
+ Add DebugModeIT for verifying `jkube.debug.enabled` property
+ Add documentation for DebugEnricher in Gradle Plugin Asciidocs
> test (gradle-plugin) : Add Integration test to verify `jkube.debug.enabled` flag works as expected (#1214)

- CHANGELOG.md
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/dependency/_jkube_dependency.adoc
Fix #1240
Add documentation for DependencyEnricher and related configuration
options.
> doc (jkube-kit/doc) : Add documentation for DependencyEnricher (#1240)

- CHANGELOG.md
- gradle-plugin/it/src/it/namespace/build.gradle
- gradle-plugin/it/src/it/namespace/expected/create-and-set-different-namespace/kubernetes.yml
- gradle-plugin/it/src/it/namespace/expected/create-and-set-different-namespace/openshift.yml
- gradle-plugin/it/src/it/namespace/expected/create-and-set-namespace/kubernetes.yml
- gradle-plugin/it/src/it/namespace/expected/create-and-set-namespace/openshift.yml
- gradle-plugin/it/src/it/namespace/expected/create-namespace/kubernetes.yml
- gradle-plugin/it/src/it/namespace/expected/create-namespace/openshift.yml
- gradle-plugin/it/src/it/namespace/expected/default/kubernetes.yml
- gradle-plugin/it/src/it/namespace/expected/default/openshift.yml
- gradle-plugin/it/src/it/namespace/expected/set-namespace/kubernetes.yml
- gradle-plugin/it/src/it/namespace/expected/set-namespace/openshift.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/NamespaceIT.java
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/namespace/_jkube_namespace.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/namespace/gradle/_namespace_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/namespace/maven/_namespace_configuration.adoc
Fix #1238
+ Port namespace integration test in kubernetes-maven-plugin/it to
`gradle-plugin/it`
+ DefaultNamespaceEnricher documentation should now be visible in gradle
plugins documentation.
> test (gradle-plugin) : Port namespace maven integration test to gradle (#1238)

- gradle-plugin/it/src/it/ingress/build.gradle
- gradle-plugin/it/src/it/ingress/expected/groovy-dsl-config/kubernetes.yml
- gradle-plugin/it/src/it/ingress/expected/zero-config-extensionsv1beta1-enricher-config/kubernetes.yml
- gradle-plugin/it/src/it/ingress/expected/zero-config-extensionsv1beta1-host-enricher-config/kubernetes.yml
- gradle-plugin/it/src/it/ingress/expected/zero-config-host-enricher-config/kubernetes.yml
- gradle-plugin/it/src/it/ingress/expected/zero-config-no-host/kubernetes.yml
- gradle-plugin/it/src/it/ingress/gradle.properties
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/IngressIT.java
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/ingress/_jkube_ingress.adoc
Fix #1258 
+ Add a gradle integration test for IngressEnricher
+ Minor modification in IngressEnricher docs to show up in Gradle docs
> test (gradle-plugin/it) : Port ingress-xml-config Maven integration test to Gradle (#1258)

- CHANGELOG.md
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/image/_jkube_image.adoc
Fix #1257
Add asciidoc documentation for ImageEnricher to `jkube-kit/doc` section.
> doc (jkube-kit/doc) : Add enricher documentation for ImageEnricher

- CHANGELOG.md
- gradle-plugin/it/src/it/project-label/build.gradle
- gradle-plugin/it/src/it/project-label/expected/custom/kubernetes.yml
- gradle-plugin/it/src/it/project-label/expected/custom/openshift.yml
- gradle-plugin/it/src/it/project-label/expected/default/kubernetes.yml
- gradle-plugin/it/src/it/project-label/expected/default/openshift.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ProjectLabelIT.java
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/project-label/_jkube_project_label.adoc
Fix partially #1262 
+ Add integration test for ProjectLabelEnricher
+ Add ProjectLabelEnricher docs for Gradle Plugins as well 
> test (gradle-plugin/it) : Add gradle integration test for ProjectLabelEnricher (#1262)

- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageConfigurationTest.java
Fixes: #1340 
Replace hamcrest assertion with assertj
> Fixes #1340

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/JobHandlerTest.java
> Fix: #1339

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtilsTest.java
> Issue 1345 Fix: Hamcrest to AssertJ AssemblyFileSetUtilsTest

- jkube-kit/common-maven/pom.xml
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java
Signed-off-by: baruKreddy <bhargavirkotha@gmail.com>
> Issue 1343 Fix: Hamcrest to Assertj

- CHANGELOG.md
- gradle-plugin/it/src/it/name/build.gradle
- gradle-plugin/it/src/it/name/expected/custom-name/kubernetes.yml
- gradle-plugin/it/src/it/name/expected/custom-name/openshift.yml
- gradle-plugin/it/src/it/name/expected/default/kubernetes.yml
- gradle-plugin/it/src/it/name/expected/default/openshift.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/NameIT.java
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/name/_jkube_name.adoc
Fix #1259 
Add Integration test for NameEnricher
:heavy_check_mark: Test should pass once #1326 gets merged
> test (gradle-plugin/it) : Add integration test for NameEnricher (#1259)

- CHANGELOG.md
- gradle-plugin/it/src/it/serviceaccount-via-groovy-dsl/build.gradle
- gradle-plugin/it/src/it/serviceaccount-via-groovy-dsl/expected/kubernetes.yml
- gradle-plugin/it/src/it/serviceaccount-via-groovy-dsl/expected/openshift.yml
- gradle-plugin/it/src/it/serviceaccount/build.gradle
- gradle-plugin/it/src/it/serviceaccount/expected/kubernetes.yml
- gradle-plugin/it/src/it/serviceaccount/expected/openshift.yml
- gradle-plugin/it/src/it/serviceaccount/src/main/jkube/deployment.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ServiceAccountIT.java
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/serviceaccount/_jkube_serviceaccount.adoc
Fix #1299
+ Add gradle integration test for ServiceAccountEnricher for default
generation and Groovy DSL configuration
+ Moving ServiceAccountEnricher documentation so that it also shows up in
Gradle Plugin documentation
> test (gradle-plugin/it) : Add gradle integration test for ServiceAccountEnricher (#1299)

- gradle-plugin/it/src/it/project-label/expected/app/kubernetes.yml
- gradle-plugin/it/src/it/project-label/expected/app/openshift.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ProjectLabelIT.java
Fix #1262
Follow up to #1331
Add an integration test to verify `jkube.enricher.jkube-project-label.app`
flag works as expected
> test (gradle-plugin/it) : Add integration test for ProjectLabelEnricher's app configuration option (#1262)

- CHANGELOG.md
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java
…All call #1362
VolumePermissionEnricher : Replace iteration with bulk Collection.addAll call #1362 
> VolumePermissionEnricher : Replace iteration with bulk Collection.addAll call

- quickstarts/maven/wildfly-jar-slim/pom.xml
Fix #1400, updated WildFly Jar Slim quickstart's name to make it more specific and avoid a duplicity with the regular WildFly Jar quickstart
> Updated Pom.xml Name

- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtensionTest.java
> Added JUnit test for OpenShiftExtension

- jkube-kit/doc/src/main/asciidoc/inc/generator/_webapp.adoc
part of https://github.com/eclipse/jkube/issues/1208
Signed-off-by: Sun Tan <sutan@redhat.com>
> doc(gradle-openshift): Fix documentation for webapp env configuration should display openshift specifics for Gradle doc

- quickstarts/gradle/webapp-jetty/README.md
- quickstarts/gradle/webapp-jetty/build.gradle
- quickstarts/gradle/webapp-jetty/gradle.properties
- quickstarts/gradle/webapp/build.gradle
- quickstarts/gradle/webapp/gradle.properties
> chore(quickstarts): Update webapp and webapp-jetty README with instructions to deploy to Openshift (RH DevSandbox)

- jkube-kit/common-maven/pom.xml
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java
- jkube-kit/common-maven/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Signed-off-by: baruKreddy bhargavirkotha@gmail.com
> JMockit to mockito

- jkube-kit/build/service/docker/pom.xml
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/ImageConfigurationTest.java
- jkube-kit/build/service/jib/pom.xml
- jkube-kit/common/pom.xml
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/FileUtilTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/YamlUtilTest.java
- jkube-kit/config/image/pom.xml
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilderTest.java
- jkube-kit/enricher/generic/pom.xml
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ImageEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/RevisionHistoryEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java
- jkube-kit/generator/api/pom.xml
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/AbstractPortsExtractorTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java
- jkube-kit/generator/karaf/pom.xml
- jkube-kit/generator/karaf/src/test/java/org/eclipse/jkube/generator/karaf/KarafGeneratorTest.java
- jkube-kit/generator/webapp/pom.xml
- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/handler/JettyAppSeverHandlerTest.java
- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/handler/TomcatAppSeverHandlerTest.java
- jkube-kit/jkube-kit-vertx/pom.xml
- jkube-kit/parent/pom.xml
- kubernetes-maven-plugin/plugin/pom.xml
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoTest.java
- openshift-maven-plugin/plugin/pom.xml
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftUndeployMojoTest.java
- pom.xml
Fixes: #1344 
Refactored all the occurrences of hamcrest assertions in the entire jkube repository with the Assertj equivalent
> Fix: #1344 Refactor all occurences of Hamcrest assertions with AssertJ equivalents

- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java
Fix #1413
Simplified verify() call to remove argument matchers and to be more readable.
Let me know if there is any thing more I can do to help ;)
> Simplified Mockito verify the call and made it easy to read

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/ProjectEnricherTest.java
- quickstarts/maven/spring-boot/pom.xml
> Testcase add for projectEnrich

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/ProjectEnricherTest.java
refactor: test: refactored ProjectEnricherTest to remove redundancies
> refactor: test: refactored ProjectEnricherTest to remove redundancies

- CHANGELOG.md
- jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
Provide guidance when the final project packaged file is not found #1328 
> Provide guidance when the final project packaged file is not found#1328

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ImageEnricherTest.java
> refactor: Remove redundant conversion of KubernetesList (#1449)

- quickstarts/maven/quarkus/pom.xml
> Updated Quarkus quickstart version to latest Quarkus version #1430

- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
fix: NPE when performing gradle k8sConfigView
> fix: NPE when performing gradle k8sConfigView

- jkube-kit/enricher/specific/pom.xml
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java
> refactor (jkube-kit/enricher) : refactored DockerHealthCheckEnricherTest to remove redundancies (#1450)

- jkube-kit/enricher/generic/pom.xml
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherTest.java
> refactor (jkube-kit/enricher) : Remove redundant conversion of KubernetesList (#1448)

- .circleci/config.yml
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
- pom.xml
deps: bump JaCoCo Maven Plugin to 0.8.8
No CQ needed, just a patch version update (0.8.6 -> 0.8.8)
> deps: bump JaCoCo Maven Plugin to 0.8.8

- .circleci/config.yml
ci: fix: CircleCI cache keys not shared
> ci: fix: CircleCI cache keys not shared

- gradle-plugin/doc/src/main/asciidoc/inc/examples/_index.adoc
Follow-up to https://github.com/eclipse/jkube/pull/1495#discussion_r879384302
While refactoring documentation for quick start scenarios, this file was
moved to jkube-kit/doc. Removing invalid link left in examples index
file since it's no longer present.
> chore (gradle-plugin/doc) : Remove invalid link to _dockerfile from Gradle examples

- scripts/eclipse-dash-tool.sh
https://github.com/eclipse/dash-licenses
/cc @waynebeaton 
Executing the following command:
```shell
./scripts/eclipse-dash-tool.sh
```
Generates a new file target/dependencies-resolved.csv with the resolved dependencies and the matching GitLab Issue, CQ, or clearlydefined approval reference.
Invalid dependencies (not approved) are shown at the top. 
Executing the following command:
```shell
./scripts/eclipse-dash-tool.sh -project "ecd.jkube" -token "$YOUR_PAT_TOKEN" -review
```
Generates the report and automatically creates issues for non-matched dependencies at https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues.
> tool: created script to automatically run the Eclipse Dash License Tool

- jkube-kit/parent/pom.xml
- pom.xml
> chore(jkube-kit deps): Add JUnit5 dependency (#1547)

- jkube-kit/common-test/pom.xml
- jkube-kit/common-test/src/test/java/org/eclipse/jkube/kit/common/ResourceVerifyTest.java
> refactor (jkube-kit-common-test): Migrated module tests from JUnit4 to JUnit5 (#1548)

- jkube-kit/config/image/pom.xml
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageConfigurationTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/BuildConfigurationTest.java
> refactor (jkube-kit/config/image/) : Migrate all tests from JMockit to Mockito (#1584)

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
> refactor EnvUtil to handle corner cases (#1628)

- quickstarts/maven/openliberty/pom.xml
deps: bump OpenLibery quickstart versions
> deps: bump OpenLibery quickstart versions

- jkube-kit/common-maven/pom.xml
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/AnsiLoggerTest.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenConfigurationExtractorTest.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
> refactor (jkube-kit/common-maven): Migrate all tests from JUnit4 to JUnit5 (#1551)

- quickstarts/maven/micronaut/README.md
- quickstarts/maven/micronaut/pom.xml
Fixes #1429 
Signed-off-by: Mohd-Farhan <mohammadfarhan3255@gmail.com>
> feat: update version of micronaut

- jkube-kit/jkube-kit-thorntail-v2/pom.xml
- jkube-kit/jkube-kit-thorntail-v2/src/test/java/org/eclipse/jkube/thorntail/v2/enricher/ThorntailV2HealthCheckEnricherTest.java
Fixes https://github.com/eclipse/jkube/issues/1600
> (jkube-kit/jkube-kit-thorntail-v2/) : Migrate tests from JMockit to Mockito(#1600)

- jkube-kit/watcher/api/pom.xml
- jkube-kit/watcher/api/src/test/java/org/eclipse/jkube/watcher/api/WatcherManagerTest.java
Fixes https://github.com/eclipse/jkube/issues/1605
> (jkube-kit/watcher/api/) : Migrate tests from JMockit to Mockito

- openshift-maven-plugin/plugin/pom.xml
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftUndeployMojoTest.java
Fixes https://github.com/eclipse/jkube/issues/1608
> refactor (openshift-maven-plugin/plugin)  : Migrate all tests from JMockit to Mockito (#1608)

- jkube-kit/config/image/pom.xml
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageConfigurationTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameFullNameParseTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/ArgumentsTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/BuildConfigurationTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/CleanupModeTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilderTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/HealthCheckConfigTest.java
> refactor (jkube-kit/config/image): Migrate all tests from JUnit4 to JUnit5 (#1552)

- jkube-kit/resource/helm/pom.xml
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmUploaderTest.java
- quickstarts/maven/ibm-javaee8-webprofile-liberty/pom.xml
Fixes https://github.com/eclipse/jkube/issues/1603
> (jkube-kit/resource/helm/) : Migrate tests from JMockit to Mockito #1603

- CHANGELOG.md
Related to https://github.com/eclipse/jkube/issues/1619
Update CHANGELOG entry for issue in order to clarify the fix and
deprecations of old properties.
> doc : Update CHANGELOG entry (#1619)

- jkube-kit/config/resource/pom.xml
- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterConfigurationTest.java
- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/IngressConfigTest.java
- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ProcessorConfigTest.java
> refactor (jkube-kit/config/resource): Migrate all tests from JUnit4 to JUnit5 (#1553)

- CHANGELOG.md
- gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass-annotation/kubernetes.yml
- gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass-annotation/openshift.yml
- gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass/kubernetes.yml
- gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass/openshift.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/VolumePermissionIT.java
- jkube-kit/doc/src/main/asciidoc/inc/enricher/volume-permission/_jkube_volume_permission.adoc
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricherTest.java
- kubernetes-maven-plugin/it/src/it/volume-enricher-custom-storage-class/expected/kubernetes.yml
- openshift-maven-plugin/it/src/it/volume-enricher-custom-storage-class/expected/openshift.yml
Fixes #1361
VolumePermissionEnricher should now add StorageClass name in
`.spec.storageClassName` field instead of an annotation in metadata.
Add a new configuration field `useStorageClassAnnotation` in VolumePermissionEnricher
configuration for backward compatibility. User can switch back to
annotation by setting this field to `true`.
> feat (jkube-kit/enricher) : VolumePermissionEnricher : Use `.spec.storageClassName` instead of annotation to set PersistentVolume class (#1361)

- CHANGELOG.md
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ImageChangeTriggerIT.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/EnricherContext.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/JKubeEnricherContext.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/model/Configuration.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/JKubeEnricherContextTest.java
- jkube-kit/enricher/api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricherTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojoTest.java
Fixes #1532
No ImageChange trigger should added to DeploymentConfig if BuildStrategy
is JIB.
> fix (jkube-kit/enricher) : ImageChangeTriggerEnricher shouldn't generate ImageChange triggers for JIB build strategy (#1532)

- jkube-kit/build/service/jib/pom.xml
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
> refactor (jkube-kit-build-service-jib): Migrate test from JUnit4 to JUnit5 (#1556)

- jkube-kit/resource/helm/pom.xml
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/ChartTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmConfigTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmDependencyTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmRepoTypeTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmRepositoryTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmUploaderTest.java
> refactor(jkube-kit-resource-helm): Migrate all tests from JUnit4 to JUnit5 (#1558)

- jkube-kit/resource/service/pom.xml
- jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/DefaultResourceServiceTest.java
- jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/TemplateUtilTest.java
- jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/WriteUtilTest.java
> refactor (jkube-kit-resource-service): Migrate test from JUnit4 to JUnit5 (#1567)

- CHANGELOG.md
- jkube-kit/parent/pom.xml
> deps: Bump jib-core to 0.21.0

- jkube-kit/profile/pom.xml
- jkube-kit/profile/src/test/java/org/eclipse/jkube/kit/profile/ProfileUtilTest.java
> refactor (jkube-kit-profiles): Migrate test from JUnit4 to JUnit5 (#1566)

- jkube-kit/watcher/api/pom.xml
- jkube-kit/watcher/api/src/test/java/org/eclipse/jkube/watcher/api/WatcherManagerTest.java
> refactor (jkube-kit-watcher-api): Migrate test from JUnit4 to JUnit5 (#1568)

- jkube-kit/watcher/standard/pom.xml
- jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherTest.java
- jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/ExecListenerLatchTest.java
- jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/PodExecutorTest.java
> refactor (jkube-kit-watcher-standard): Migrate all tests from JUnit4 to JUnit5 (#1569)

- jkube-kit/jkube-kit-thorntail-v2/pom.xml
- jkube-kit/jkube-kit-thorntail-v2/src/test/java/org/eclipse/jkube/thorntail/v2/enricher/ThorntailV2HealthCheckEnricherTest.java
- jkube-kit/jkube-kit-thorntail-v2/src/test/java/org/eclipse/jkube/thorntail/v2/generator/ThorntailV2GeneratorIsApplicableTest.java
> refactor (jkube-kit-thorntail): Migrate all tests from JUnit4 to JUnit5 (#1571)

- jkube-kit/generator/karaf/pom.xml
- jkube-kit/generator/karaf/src/test/java/org/eclipse/jkube/generator/karaf/KarafGeneratorTest.java
> refactor (jkube-kit-generator-karaf): Migrate test from JUnit4 to JUnit5 (#1562)

- CHANGELOG.md
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricher.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/enricher/MicronautHealthCheckEnricher.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/enricher/MicronautHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-micronaut/src/test/resources/health-check-enricher-test/application.properties
MicronautHealthCheckEnricher should also consider Micronaut Gradle Plugin in isApplicable"
Fixes #1634 
> MicronautHealthCheckEnricher should also consider Micronaut Gradle Plugin in isApplicable" (#1634)

- jkube-kit/generator/java-exec/pom.xml
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/FatJarDetectorTest.java
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorCustomPropertiesTest.java
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorMainClassDeterminationTest.java
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaRunGeneratorTest.java
> refactor (jkube-kit-generator-java-exec): Migrate all tests from JUnit4 to JUnit5 (#1561)

- jkube-kit/jkube-kit-openliberty/pom.xml
- jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/OpenLibertyUtilsTest.java
- jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/enricher/OpenLibertyHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGeneratorIsApplicableTest.java
- jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGeneratorTest.java
> refactor (jkube-kit-openliberty): Migrate all tests from JUnit4 to JUnit5 (#1575)

- jkube-kit/jkube-kit-micronaut/pom.xml
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsGetMicronautConfigurationTest.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsTest.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/enricher/MicronautHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/generator/MicronautGeneratorTest.java
> refactor (jkube-kit-micronaut): Migrate all tests from JUnit4 to JUnit5 (#1574)

- jkube-kit/generator/api/pom.xml
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/FromSelectorTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/GeneratorManagerTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/AbstractPortsExtractorTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java
- jkube-kit/parent/pom.xml
Fixes https://github.com/eclipse/jkube/issues/1593
> (jkube-kit/generator/api/) : Migrate tests from JMockit to Mockito(#1593)

- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/LogMojoTest.java
Fixes #1702 
Signed-off-by: Kshitiz-Mhto <nkcmcdhy@gmail.com>
> Feat: Unused classes are removed

- CHANGELOG.md
- jkube-kit/doc/src/main/asciidoc/inc/generator/_webapp.adoc
- jkube-kit/parent/pom.xml
- quickstarts/gradle/docker-file-simple/Dockerfile
- quickstarts/gradle/docker-file-simple/README.md
- quickstarts/gradle/groovy-dsl-config/build.gradle
- quickstarts/gradle/micronaut-customized-image/build.gradle
- quickstarts/gradle/quarkus/README.md
- quickstarts/gradle/webapp-jetty/README.md
- quickstarts/gradle/webapp/README.md
- quickstarts/maven/quarkus/README.md
deps: bump JKube maintained base images to 0.0.16
> deps: bump JKube maintained base images to 0.0.16

- jkube-kit/build/service/docker/pom.xml
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/ImageConfigurationTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/ImagePullManagerTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/BuildConfigTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/KeyStoreUtilLoadPrivateKeyTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/KeyStoreUtilTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/ApacheHttpClientDelegateTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClientMockitoTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClientTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/HcChunkedResponseHandlerWrapperTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/unix/UnixSocketTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactoryTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/CredentialHelperClientTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSdkAuthConfigFactoryTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSigner4RequestTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/DockerRegistryAuthHandlerTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/EcrExtendedAuthTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/config/handler/RegistryServerConfigurationTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/PropertyConfigHandlerTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/AnsiLoggerFacadeTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/AutoPullModeTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/ConfigHelperTest.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/ImageNameFormatterTest.java
> refactor (jkube-kit-build-service-docker): Migrate all tests from JUnit4 to JUnit5 (#1555)

- openshift-maven-plugin/plugin/pom.xml
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/OpenShiftGeneratedPluginDescriptorTest.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftResourceMojoTest.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftUndeployMojoTest.java
> refactor (openshift-maven-plugin): Migrate all tests from JUnit4 to JUnit5 (#1579)

- jkube-kit/enricher/specific/pom.xml
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/PrometheusEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/WebAppHealthCheckEnricherTest.java
- jkube-kit/enricher/specific/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Fixes https://github.com/eclipse/jkube/issues/1592
> (jkube-kit/enricher/specific/) : Migrate tests from JMockit to Mockito #1592

- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_vertx.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/_jkube_healthcheck_vertx.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/gradle/_configuration_structure.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/gradle/_different_readiness_liveness.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/gradle/_exec_probe_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/gradle/_http_probe_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/gradle/_minimal_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/gradle/_shared_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/gradle/_tcp_probe_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/maven/_configuration_structure.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/maven/_different_readiness_liveness.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/maven/_exec_probe_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/maven/_http_probe_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/maven/_minimal_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/maven/_shared_configuration.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/vertx-healthcheck/maven/_tcp_probe_configuration.adoc
- jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java
- jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricherTest.java
chore(method modification): Add check for vertx gradle plugin with isApplicable method in VertxHealthCheckEnricher (#1633)
Fix #1633 
> Add check for vertx gradle plugin with isApplicable method in VertxHealthCheckEnricher

- CHANGELOG.md
- jkube-kit/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_wildfly_jar.adoc
- jkube-kit/jkube-kit-wildfly-jar/pom.xml
- jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/WildflyJarUtils.java
- jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricher.java
- jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGenerator.java
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/WildflyJarUtilsTest.java
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java
Fix: #1474
Signed-off-by: Anurag Singh Rajawat <anuragsinghrajawat22@gmail.com>
> feat (jkube-kit/wildfly-jar): Add startup probe in WildFlyJARHealthCheckEnricher (#1474)

- CHANGELOG.md
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/parent/pom.xml
- pom.xml
deps: bump Kubernetes Client from 6.0.0 to 6.1.1
Relates to: #1647
> deps: bump Kubernetes Client from 6.0.0 to 6.1.1

- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/GeneratorContext.java
- jkube-kit/jkube-kit-quarkus/pom.xml
- jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusUtils.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusModeTest.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusUtilsTest.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorExposedPortsTest.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
> refactor (jkube-kit-quarkus): Migrate all tests from JUnit4 to JUnit5 (#1573)

- jkube-kit/generator/java-exec/pom.xml
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorMainClassDeterminationTest.java
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java
- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaRunGeneratorTest.java
- jkube-kit/generator/java-exec/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Fixes https://github.com/eclipse/jkube/issues/1594
> (jkube-kit/generator/java-exec/) : Migrate tests from JMockit to Mockito

- jkube-kit/jkube-kit-quarkus/pom.xml
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
- jkube-kit/jkube-kit-quarkus/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Fixes https://github.com/eclipse/jkube/issues/1598
> (jkube-kit/jkube-kit-quarkus/) : Migrate tests from JMockit to Mockito

- jkube-kit/jkube-kit-vertx/pom.xml
- jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxPortsExtractorTest.java
Fixes https://github.com/eclipse/jkube/issues/1601
> (jkube-kit/jkube-kit-vertx/) : Migrate tests from JMockit to Mockito

- scripts/quickstarts.sh
chore: script to update quickstart gradle kit dependencies
> chore: script to update quickstart gradle kit dependencies

- .github/ISSUE_TEMPLATE/bug_report.yml
> chore(gh-template): Adding affect version 1.9.0 to the bug report form template

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/OpenshiftHelper.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/OpenshiftHelperTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftUndeployServiceTest.java
Fix #1747
Refactor remaining client.adapt call in `OpenShiftHelper.asOpenShiftClient` method to use isSupported() method. Just delegating OpenShift discovery to isOpenShift method (which uses isSupported() internally)
> fix (jkube-kit) : Upgrading from 1.8.0 to 1.9.0 and now failing : Not Found (#1747)

- jkube-kit/generator/api/pom.xml
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/FromSelectorTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/GeneratorManagerTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/AbstractPortsExtractorTest.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java
- jkube-kit/generator/api/src/test/resources/org/eclipse/jkube/generator/api/support/AbstractPortsExtractorTest.bla
> refactor (jkube-kit-generator-api): Migrate all tests from JUnit4 to JUnit5 (#1560)

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
Follow up PR to https://github.com/eclipse/jkube/pull/1750
Replace all null checks for getOpenShiftClient with `OpenShiftHelper.isOpenShift(kubernetesClient)` call.
> fix (jkube-kit/config) : Replace getOpenShiftClient null checks with OpenShiftHelper.isOpenShift()

- kubernetes-maven-plugin/plugin/pom.xml
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/GeneratedPluginDescriptorTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/SkipGoalsTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/LogMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojoTest.java
> refactor (kubernetes-maven-plugin): Migrate all tests from JUnit4 to JUnit5 (#1577)

- jkube-kit/enricher/specific/pom.xml
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/PrometheusEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricherTest.java
- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/WebAppHealthCheckEnricherTest.java
> refactor(jkube-kit-enricher-specific): Migrate all tests from JUnit4 to JUnit5 (#1565)

- jkube-kit/generator/webapp/pom.xml
- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/AppServerAutoDetectionTest.java
- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/WebAppGeneratorTest.java
- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/handler/JettyAppSeverHandlerTest.java
- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/handler/TomcatAppSeverHandlerTest.java
- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandlerTest.java
Fixes https://github.com/eclipse/jkube/issues/1596
> refactor (jkube-kit/generator/webapp/): Migrate all tests from JMockit to Mockito

- .github/pull_request_template.md
> chore(gh-pr-template): adding checklists to encourage smaller PRs and conventional commits

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ImagePullPolicyEnricherTest.java
> chore(ImagePullPolicyEnricherTest): Create additional tests to verify the enricher applied to KubernetesListBuilder with multiple resource types

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/ApacheHttpClientDelegate.java
> Make ApacheHttpClientDelegate$StatusCodeCheckerResponseHandler fields final

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSdkAuthConfigFactory.java
> Make AwsSdkAuthConfigFactory fields as final

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/DefaultLogCallback.java
> Fixing code style issue with declaration

- jkube-kit/config/service/pom.xml
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubBuildServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServicePortOrderTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceBuildIntegrationTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtilTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftUndeployServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/PatchServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/WebServerEventCollector.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/plugins/PluginManagerTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/plugins/PluginServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/portforward/PortForwardMonitorTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/portforward/PortForwardPodWatcherTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/portforward/PortForwardTaskTest.java
> refactor (jkube-kit-config-service): Migrate tests from JUnit4 to JUnit5 (#1559)

- jkube-kit/build/api/pom.xml
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyConfigurationSourceTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyConfigurationUtilsTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerCreateDockerTarArchiveTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerVerifyAssemblyReferencedInDockerfileTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuthTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/FromConfigRegistryAuthHandlerTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/SystemPropertyRegistryAuthHandlerTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/BuildUtilTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/KubernetesConfigAuthUtilTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/PathTestUtil.java
> refactor (jkube-kit-build-api): Migrate tests from JUnit4 to JUnit5 (#1554)

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/GroupArtifactVersion.java
Fixes #1809 ( GroupArtifactVersion fields may be 'final' ) 
> Changing fields to final

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/JKubeBuildTarArchiver.java
> change fields to final in JKubeBuildTarArchive

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/wait/HealthCheckChecker.java
Fixes https://github.com/eclipse/jkube/issues/1811
> change HealthCheckChecker fields

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/ArchiveService.java
> Declaring variable as final

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ProjectClassLoaders.java
> chore: make ProjectClassLoaders fields final

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/PlatformMode.java
> Issue #1837: Code style fix for PlatformMode.java fields

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java
> Add final to map in PatchService.java

- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilder.java
Signed-off-by: Ka Lan Leung <kalanleung@outlook.com>
Fixes #1807
> refactor(jkube-kit/config): Refactoring DockerFileBuilder collections to be final

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/service/MigrateService.java
> Made MigrateService.java fields final.

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogDispatcher.java
> bug: added final keyword in LogDispatcher

- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/LogConfiguration.java
> Update  LogDrivers field to final in LogConfiguration.java

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RunService.java
Fixes https://github.com/eclipse/jkube/issues/1867 (issue)
> RunService added final to fields

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuthConfig.java
RegistryAuthConfig fields may be 'final' is fixed here 
```private String propertyPrefix; ``` is replaced with  ```    private final String propertyPrefix; ```
Fixes #1864 
> RegistryAuthConfig fields may be 'final' is fixed.

- jkube-kit/resource/service/pom.xml
- jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/DefaultResourceServiceTest.java
- jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/TemplateUtilTest.java
- jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/WriteUtilTest.java
- jkube-kit/resource/service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Fixes https://github.com/eclipse/jkube/issues/1604
> (jkube-kit/resource/service/) : Migrate tests from JMockit to Mockito

- pom.xml
> ci: disable JaCoCo offline instrumentation

- gradle-plugin/kubernetes/pom.xml
- gradle-plugin/openshift/pom.xml
- pom.xml
> ci: temporarily reenable JaCoCo instrumentation

- gradle-plugin/openshift/pom.xml
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtensionPropertyTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtensionTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginRegisterTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftApplyTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftBuildTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftDebugTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmPushTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftPushTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftUndeployTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftWatchTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskEnvironmentExtension.java
> refactor (org.eclipse.jkube.openshift.gradle.plugin): Migrate tests from JUnit4 to JUnit5 (#1582)

- jkube-kit/jkube-kit-wildfly-jar/pom.xml
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/WildflyJarUtilsTest.java
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java
> refactor (jkube-kit-wildfly-jar): Migrate all tests from JUnit4 to JUnit5 (#1576)

- CHANGELOG.md
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherAddMissingPartsTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherExternalServiceTest.java
Fixes #1668
Rather than considering any Service type for merging with an opinionated Service; check Service name matches the controller name. As commented in https://github.com/eclipse/jkube/issues/1668#issuecomment-1285943688 there should be name provided always in fragment.
> feat (jkube-kit/enricher) : Allow additional services besides the default (#1668)

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ResourceFileType.java
> Fixed issue#1865

- jkube-kit/resource/service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- kubernetes-maven-plugin/plugin/pom.xml
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojoTest.java
Fixes https://github.com/eclipse/jkube/issues/1607
> (kubernetes-maven-plugin/plugin) : Migrate tests from JMockit to Mockito

- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/GeneratorContext.java
- jkube-kit/jkube-kit-spring-boot/pom.xml
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/enricher/AbstractSpringBootHealthCheckEnricherTestSupport.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherContext.java
Fixes https://github.com/eclipse/jkube/issues/1599
> (jkube-kit/jkube-kit-spring-boot/) : Migrate tests from JMockit to Mockito

- CHANGELOG.md
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/AnsiLogger.java
> fix: Maven 3.6.3 is still supported

- jkube-kit/jkube-kit-spring-boot/pom.xml
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/enricher/AbstractSpringBootHealthCheckEnricherTestSupport.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherTest.java
> refactor (jkube-kit-spring-boot): Migrate tests from JUnit4 to JUnit5(#1570)

- jkube-kit/common-maven/pom.xml
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MavenUtil.java
- jkube-kit/parent/pom.xml
deps: remove unneeded Plexus dependencies
> deps: remove unneeded Plexus dependencies

- jkube-kit/enricher/api/pom.xml
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/BaseEnricherGetReplicaCountTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/BaseEnricherTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/DefaultEnricherManagerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/EnricherConfigTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/JKubeEnricherContextTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/ServiceExposerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/model/KindAndNameTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtilTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/InitContainerHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitorTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DeploymentConfigHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DeploymentHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/HandlerHubControllerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/HandlerHubTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/JobHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerHTTPUrlTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ReplicaSetHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ReplicationControllerHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/StatefulSetHandlerTest.java
> refactor (jkube-kit-enricher-api): Migrate all tests from JUnit4 to JUnit5 (#1557)

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- pom.xml
> chore(jkube-kit): Remove Junit4 dependency (#1873)

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceBuildIntegrationTest.java
After compiling project with tests, I noticed an extra directory `jkube-extra` created everytime. 
```
jkube : $ cd jkube-kit/config/service/
service : $ mvn test -Dtest="org.eclipse.jkube.kit.config.service.kubernetes.JibBuildServiceBuildIntegrationTest"
...
service : $ git status
Untracked files:
(use "git add <file>..." to include in what will be committed)
jkube-extra/
no changes added to commit (use "git add" and/or "git commit -a")
service : $ 
```
Turns out it's getting generated by JibBuildServiceBuildIntegrationTest which was not passed outputDirectory from TemporaryFolder.
> chore (jkube-kit/config/service) : JibBuildServiceBuildIntegrationTest is leaving undeleted `jkube-extra` directory after execution

- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/_jkube_replicas.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/replicacount/_jkube_replicacount.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_installation.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-build.adoc
- Restored build configuration details
- Removed duplicate jkube-replicas (count) enricher doc
- Removed deprecated Maven settings installation note
> doc: misc fixes

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/TestHttpStaticServer.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
- jkube-kit/common/src/test/resources/remote-resources/deployment.yaml
- jkube-kit/common/src/test/resources/remote-resources/sa.yml
Fix #1753
KubernetesHelperTest's tests involving remote fragments keep breaking on Eclipse CI. Istead of hosting them on GitHub, add a temporary localhost web server that would host remote fragments directory till test has finished execution.
> refactor (jkube-kit/common) : Use temporary localhost WebServer in KubernetesHelperTest for remote fragments (#1753)

- CHANGELOG.md
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftRemoteDevTask.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginRegisterTaskTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftRemoteDevTaskTest.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenShiftRemoteDevMojo.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenShiftRemoteDevMojoTest.java
Fixes #1935
+ Override getLogPrefix() method in OpenShiftRemoteDevMojo to enforce OpenShift log prefix
+ Implement OpenShiftRemoteDevTask to enforce OpenShift log prefix
> fix (openshift-plugins) : `oc:remote-dev` goal / `ocRemoteDev` task have wrong log prefixes (#1935)

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuth.java
> Change authEncoded field of RegistryAuth to final

- jkube-kit/jkube-kit-wildfly-jar/pom.xml
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java
Fixes https://github.com/eclipse/jkube/issues/1602
> (jkube-kit/jkube-kit-wildfly-jar/) : Migrate tests from JMockit to Mockito #1729

- README.md
> Remove Katacoda link from README.md

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/ImagePullCache.java
> made the backend class in ImagePullCache.java final

- CHANGELOG.md
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/ImageNameFormatter.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/ImageNameFormatterTest.java
Fix #1858
Interpolate image name while formatting in ImageNameFormatter.
> fix (jkube-kit/build) : Properties in image name not getting replaced (#1858)

- .github/CODEOWNERS
> fix: codeowners syntax

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogOutputSpecFactory.java
Fixes #1833 
LogOutputSpecFactory fields changed to 'final'
> LogOutputSpecFactory fields changed to 'final'

- CHANGELOG.md
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
> fix (jkube-kit/enricher): Remove unused methods (#1974)

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java
> File[] resources and List<ValidationRule> are now final/ issue#1866

- pom.xml
Sonar job seems to be failing due to permission issues
> ci : Remove sonar login property from sonar profile

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/model/PortMapping.java
Remove `var` as a variable name as it will be used as a reserved keyword in the latest JAVA version.
Fixes #1994 
> fix: remove var as variable name

- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
Remove `var` as a variable name as it will be used as a reserved keyword as of JAVA version 10.
Fixes #1981
> fix: replace var as variable name

- CHANGELOG.md
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojoTest.java
Fixes #2008
Resource validation should be done after resources are written.
> fix (kubernetes-maven-plugin) : Resource Validation is done before resources are generated by `k8s:resource` (#2008)

- .github/workflows/license.yml
- .github/workflows/quickstarts.yml
Related to #1767
[Harden Runner](https://github.com/step-security/harden-runner) action seems to restrict outgoing traffic to only a specific set of allowed endpoints.
Initial mode `audit` generates a report on https://app.stepsecurity.io/ that recommends what endpoints are accessed during workflow run. These are the reports for our currently used GitHub Action workflows:
- [StepSecurity License Report](https://app.stepsecurity.io/github/eclipse/jkube/actions/runs/3901209860)
- [StepSecurity Quickstarts Report](https://app.stepsecurity.io/github/eclipse/jkube/actions/runs/3901209862)
> ci : Modify Harden Runner action egress-policy to block

- CHANGELOG.md
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/AnsiLogger.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/AnsiLoggerFallbackTest.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/AnsiLoggerTest.java
Fixes #2004
fix(common):AnsiOutputStream exceptions don't prevent logging or program execution
> fix(common): AnsiOutputStream exceptions don't prevent logging or program execution

- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
- pom.xml
> deps: rollback to Kubernetes Client 6.1.1

- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/RemoteDevelopmentServiceTest.java
test: Remote development test for open port
Stolen from @juazugas
> test: Remote development test for open port

- .circleci/config.yml
ci: CircleCI job to extract license information
> ci: CircleCI job to extract license information

- CHANGELOG.md
- gradle-plugin/it/src/it/metadata/build.gradle
- gradle-plugin/it/src/it/metadata/expected/kubernetes-replicaset-controller.yml
- gradle-plugin/it/src/it/metadata/expected/kubernetes.yml
- gradle-plugin/it/src/it/metadata/expected/openshift.yml
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitorTest.java
- kubernetes-maven-plugin/it/src/it/metadata-labels-annotations/expected/kubernetes.yml
- kubernetes-maven-plugin/it/src/it/metadata-labels-annotations/invoker.properties
- kubernetes-maven-plugin/it/src/it/metadata-labels-annotations/pom.xml
- kubernetes-maven-plugin/it/src/it/metadata-labels-annotations/verify.groovy
Fixes #1829
Add a trailing newline in case of multiline values in labels and annotations in MetadataVisitor
> fix (jkube-kit/enricher) : Add trailing newline for multiline strings in labels/annotations (#1829)

- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/PortForwarderTest.java
test(remote-dev): port forwarding tests
> test(remote-dev): port forwarding tests

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PluginServiceFactory.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/PluginServiceFactoryNestedContextTest.java
- jkube-kit/common/src/test/resources/service/test-services-nested-context
Required for  https://github.com/eclipse/jkube/pull/1984 (extracted for easier review) See https://github.com/eclipse/jkube/pull/1984#issuecomment-1372551980 for more details
PluginServiceFactory tries to create ServiceImpl objects by invoking their constructors with the constructor parameter. This works fine when the constructor parameter is not using complex inheritance, but if we provide a nested subtype as a constructor argument to PluginServiceFactory (let's say BaseA > BaseB > BaseC) it fails to resolve the constructor argument.
Instead of just getting types via `constructorParameter.getClass().getInterfaces()` try getting all possible subtypes recursively.
> fix (jkube-kit/common) : PluginServiceFactory fails to resolve constructor arguments for more than one level subclasses

- CHANGELOG.md
> chore: add missing release date to 1.11.0

- jkube-kit/doc/src/main/asciidoc/inc/resource-generation/gradle/_controller_resource_configuration_example.adoc
Update _controller_resource_configuration_example.adoc to not use deprecated `env` inside ResourceConfig and use `controller.env` instead
Fixes #2058
> doc (jkube-kit/doc) : Move env field inside controller Groovy DSL configuration example (#2058)

- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
feat: bumps JKube Base images to 0.0.18
> feat: bumps JKube Base images to 0.0.18

- CHANGELOG.md
- gradle-plugin/it/src/it/multiple-services/expected/kubernetes.yml
- gradle-plugin/it/src/it/multiple-services/expected/openshift.yml
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java
- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
- jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarder.java
- jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/LocalServiceManager.java
- pom.xml
deps: bump kubernetes-client to 6.5.0
> deps: bump kubernetes-client to 6.5.0

- CHANGELOG.md
- jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MavenConfigurationExtractor.java
- jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenConfigurationExtractorTest.java
Fixes #2093
Description: 
When the elements in pom.xml are in a list, and one of them has internal elements and the other does not(see code below), then we get a ClassCastException because the code does not know how to work with HashMap. Handling this situation also does not make sense, because the 2nd element does not contain anything inside, therefore we have nothing to add to the first element.
```
<module name="TreeWalker">
<module name="IllegalImport">
<property name="severity" value="warning"/>
<property name="illegalPkgs" value="sun, edu"/>
</module>
<module name="RedundantImport"/>
</module>
```
> fix: ClassCastException when extracting plugins

- CHANGELOG.md
- gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
- gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/persistentvolumeclaim-storageclass/_jkube_persistentvolumeclaim_storageclass.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/volume-permission/_jkube_volume_permission.adoc
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/PersistentVolumeClaimStorageClassEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java
- jkube-kit/enricher/generic/src/main/resources/META-INF/jkube/enricher-default
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/PersistentVolumeClaimStorageClassEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricherTest.java
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
- openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
Closes #1179
+ Make BaseEnricher's `getConfig` method public in order to make an enricher access other enricher's config
+ Move setting PersistentVolumeClaim's storageClass related logic into a
new enricher : PersistentVolumeClaimStorageClassEnricher . This way user can
simply exclude VolumePermissionEnricher to opt out of volume permission
initContainer.
+ Deprecate VolumePermissionEnricher's `defaultStorageClass` and
`useStorageClassAnnotation` fields in favor of
PersistentVolumeClaimStorageClassEnricher equivalents.
> refactor (jkube-kit/enricher) : Move storageClass related functionality out of VolumePermissionEnricher (#1179)

- jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm_push.adoc
Fixes #2064
We already seem to support providing credentials in maven settings for pushing helm charts. Added documentation to specify it more clearly.
> doc (jkube-kit/doc) : Add documentation clarifying usage of `settings.xml` for helm registry credentials (#2064)

- CHANGELOG.md
- pom.xml
deps: bump kubernetes-client to 6.5.1
> deps: bump kubernetes-client to 6.5.1

- jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarder.java
- jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/LocalService.java
- jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/LocalServiceManager.java
- jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/RemoteDevelopmentService.java
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/LocalServiceManagerTest.java
refactor(remote-dev): use constants for K8s labels
Relates to https://github.com/eclipse/jkube/pull/2087#discussion_r1149268383
> refactor(remote-dev): use constants for K8s labels

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JKubeFileInterpolator.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JKubeFileInterpolatorTest.java
Fixes #2101
Add dynamic transitive properties support
> fix: resolve transitive properties

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ControllerResourceConfig.java
- jkube-kit/doc/src/main/asciidoc/inc/enricher/_jkube_replicas.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/controller/_jkube_controller.adoc
- jkube-kit/doc/src/main/asciidoc/inc/resource-generation/_controller_resource_generation.adoc
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/CronJobHandler.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/HandlerHub.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandler.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/CronJobHandlerTest.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/HandlerHubControllerTest.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java
> feat(jkube-kit): Initial Support for CronJob (#1954)

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojoTest.java
Fix #2154
refactor: WatchMojo doesn't instantiate KubernetesClient
> refactor: WatchMojo doesn't instantiate KubernetesClient

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/access/ClusterConfiguration.java
Fix https://github.com/fabric8io/kubernetes-client/issues/5114 caused by changes in https://github.com/eclipse/jkube/commit/16020273d0dd0065249b0079b68b16aba53134e9
> fix: .kube/config trustCerts is not overwritten

- CHANGELOG.md
- jkube-kit/jkube-kit-spring-boot/pom.xml
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java
Fix #2166 
Adds integration test for SpringBootWatcher.
Removes potential command-line injection from secret in SpringBootWatcher
> fix: removes potential command-line injection from secret in SpringBootWatcher

- gradle-plugin/doc/src/main/asciidoc/inc/_profiles.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_profiles.adoc
> doc: remove nonexistent `osio` profile from documentation

- CHANGELOG.md
- gradle-plugin/doc/src/main/asciidoc/inc/_profiles.adoc
- gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
- gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_profiles.adoc
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
- openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
> fix: `internal-microservice` profile prevents Service exposure

- CHANGELOG.md
- jkube-kit/profile/src/main/java/org/eclipse/jkube/kit/profile/Profile.java
Fixes #2174
fix: profile merge constructor accounts for `parentProfile` field
> fix: profile merge constructor accounts for parentProfile field

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/ImageNameFormatter.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/ImageNameFormatterTest.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JavaProject.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JavaProjectTest.java
Create a reusable method to identify SNAPSHOT Maven projects
> chore: expose isSnapshot in JavaProject

- CHANGELOG.md
- gradle-plugin/it/src/it/security-hardening/build.gradle
- gradle-plugin/it/src/it/security-hardening/expected/kubernetes.yml
- gradle-plugin/it/src/it/security-hardening/expected/openshift.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SecurityHardeningIT.java
- gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
- gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JavaProjectTest.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecurityHardeningEnricher.java
- jkube-kit/enricher/generic/src/main/resources/META-INF/jkube/enricher-default
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/SecurityHardeningEnricherTest.java
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
- openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
Partial Fix for #2165. Follow-up PRs should continue to improve the spiked feature and to add others.
I'll provide documentation for the new feature in a separate, upcoming PR.
In order to test, run the plugin with the new profile (`security-hardening`) -opt in-: 
```
mvn -Djkube.profile=security-hardening k8s:resource
```
> feat: spike a Kubernetes resource Security Hardening profile (opt-in)

- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/security-hardening/_index.adoc
- jkube-kit/doc/src/main/asciidoc/inc/profiles/_index.adoc
doc: security-hardening enricher and profile
Partial Fix for #2165.
> doc: security-hardening enricher and profile

- gradle-plugin/it/src/it/serviceaccounts-via-groovy-dsl/build.gradle
- gradle-plugin/it/src/it/serviceaccounts-via-groovy-dsl/expected/default/kubernetes.yml
- gradle-plugin/it/src/it/serviceaccounts-via-groovy-dsl/expected/default/openshift.yml
- gradle-plugin/it/src/it/serviceaccounts-via-groovy-dsl/expected/skip-create/kubernetes.yml
- gradle-plugin/it/src/it/serviceaccounts-via-groovy-dsl/expected/skip-create/openshift.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ServiceAccountIT.java
Extracted from #1889
- Rename `serviceaccount-via-groovy-dsl` -> `serviceaccounts-via-groovy-dsl` 
- it seems to be testing `serviceaccounts` groovy dsl option. It seems to be testing `resources` -> `serviceAccounts` configuration option not `resources` -> `serviceAccount`
> chore (gradle-plugin/it) : Rename serviceaccount-via-groovy-dsl integration test project for clarity

- jkube-kit/build/service/docker/pom.xml
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServicePullIT.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServicePushIT.java
+ Add integration test RegistryServiceIT for RegistryService which tries to verify correct image name is being passed to docker REST API while pulling/pushing images.
> test (jkube-kit/build/service) : Add integration test for RegistryService

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
feat: bumps JKube Base images to 0.0.19
> feat: bumps JKube Base images to 0.0.19

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
`@return` tag being mistyped seems to be causing build failure on our [release pipeline](https://ci.eclipse.org/jkube/job/simplified-maven-central-release/44/consoleFull). We should merge this PR first and then rebase https://github.com/eclipse/jkube/pull/2205 ; javadoc check should pass there after this fix is merged.
> doc (jkube-kit/common) : fix typo in KubernetesHelper.isPodReady return javadoc

- .circleci/config.yml
Fixes #2204 
:construction: Requires https://github.com/eclipse/jkube/pull/2206 to be merged first
Somehow on machine build jvm this seems to be passing .  On Eclipse infrastructure, we are using `Java version: 1.8.0_292, vendor: AdoptOpenJDK,`
- :heavy_check_mark: machine build
- ```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```
- :x: cimg/openjdk:8.0
- ```
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Temurin)(build 25.362-b09, mixed mode)
```
- :x: cimg/openjdk:11.0
- ```
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7) …
```
> ci : Migrate CircleCI Javadoc workflow to docker from machine workflow (#2204)

- CHANGELOG.md
- pom.xml
deps: bump Kubernetes Client to 6.7.2
https://github.com/fabric8io/kubernetes-client/pull/5250
Relates to: #2211
> deps: bump Kubernetes Client to 6.7.2

- CHANGELOG.md
- gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
- gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
- jkube-kit/jkube-kit-helidon/pom.xml
- jkube-kit/jkube-kit-helidon/src/main/java/org/eclipse/jkube/helidon/HelidonUtils.java
- jkube-kit/jkube-kit-helidon/src/main/java/org/eclipse/jkube/helidon/enricher/HelidonHealthCheckEnricher.java
- jkube-kit/jkube-kit-helidon/src/main/resources/META-INF/jkube/enricher-default
- jkube-kit/jkube-kit-helidon/src/test/java/org/eclipse/jkube/helidon/HelidonUtilsTest.java
- jkube-kit/jkube-kit-helidon/src/test/java/org/eclipse/jkube/helidon/enricher/HelidonHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-helidon/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
- openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
Fixes #1713 
:heavy_check_mark:  ~Requires https://github.com/eclipse/jkube/pull/2129 to be merged first~
+ Add HelidonHealthCheckEnricher to automatically add liveness,
readiness and start probes based on already existing microprofile
health check enricher
> feat (jkube-kit) : Add HelidonHealthCheckEnricher to add Kubernetes health checks for Helidon applications (#1713)

- jkube-kit/jkube-kit-helidon/pom.xml
- jkube-kit/jkube-kit-helidon/src/test/java/org/eclipse/jkube/helidon/enricher/HelidonHealthCheckEnricherTest.java
- jkube-kit/jkube-kit-helidon/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
> review:refactor: helidon tests don't need mockito

- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
> test: Quarkus Generator for native disables Prometheus and Jolokia

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/RegistryUtil.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/RegistryUtilTest.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RegistryService.java
- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceGetApplicableRegistryTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java
- kubernetes-maven-plugin/it/src/it/xml-image-multilayer/expected/Dockerfile
- kubernetes-maven-plugin/it/src/it/xml-image-multilayer/expected/Dockerfile.second-image
- kubernetes-maven-plugin/it/src/it/xml-image-multilayer/pom.xml
- kubernetes-maven-plugin/it/src/it/xml-image/expected/Dockerfile
- kubernetes-maven-plugin/it/src/it/xml-image/pom.xml
+ The logic for determining applicable push or pull registry is duplicated and non uniform across different build services. Move common logic to RegistryUtil helper class.
+ Change base image in kubernetes-maven-plugin JIB integration tests `xml-image` and `xml-image-multilayer` to `registry.access.redhat.com/ubi8/ubi-minimal:8.8-860`
- After refactor JIB build seems to picking invalid credentials from [`kubernetes-maven-plugin/it/src/it/settings.xml`](https://github.com/eclipse/jkube/blob/master/kubernetes-maven-plugin/it/src/it/settings.xml) which results in build failure. Earlier in the absence of an explicit registry, [JibBuildService](https://github.com/eclipse/jkube/blob/master/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java …
> refactor (jkube-kit) : Move pull/push registry resolution logic to RegistryUtil

- CHANGELOG.md
- jkube-kit/jkube-kit-quarkus/pom.xml
- jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/NativeGenerator.java
- jkube-kit/jkube-kit-quarkus/src/main/resources-filtered/META-INF/jkube/default-images.properties
- jkube-kit/parent/pom.xml
fix: Quarkus native base image read from properties (configurable)
> fix: Quarkus native base image read from properties (configurable)

- CHANGELOG.md
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
- jkube-kit/parent/pom.xml
deps: Quarkus native base image uses UBI 8.7
> deps: Quarkus native base image uses UBI 8.7

- quickstarts/maven/helidon-microprofile/README.md
- quickstarts/maven/helidon-microprofile/pom.xml
- quickstarts/maven/helidon-microprofile/src/main/java/org/eclipse/jkube/quickstarts/maven/helidon/GreetResource.java
- quickstarts/maven/helidon-microprofile/src/main/java/org/eclipse/jkube/quickstarts/maven/helidon/GreetingProvider.java
- quickstarts/maven/helidon-microprofile/src/main/java/org/eclipse/jkube/quickstarts/maven/helidon/Message.java
- quickstarts/maven/helidon-microprofile/src/main/resources/META-INF/beans.xml
- quickstarts/maven/helidon-microprofile/src/main/resources/META-INF/microprofile-config.properties
- quickstarts/maven/helidon-microprofile/src/main/resources/META-INF/native-image/org.eclipse.jkube.quickstarts.maven.helidon/helidon-microprofile/native-image.properties
- quickstarts/maven/helidon-se/README.md
- quickstarts/maven/helidon-se/pom.xml
- quickstarts/maven/helidon-se/src/main/java/org/eclipse/jkube/quickstarts/maven/helidon/GreetService.java
- quickstarts/maven/helidon-se/src/main/java/org/eclipse/jkube/quickstarts/maven/helidon/Main.java
- quickstarts/maven/helidon-se/src/main/resources/META-INF/native-image/org.eclipse.jkube.gradle.sample.helidon/helidon-se/native-image.properties
- quickstarts/maven/helidon-se/src/main/resources/application.yaml
:heavy_check_mark:  ~Requires #2129 #2130 #2132 to be merged first~
+ Add Helidon SE maven quickstart
+ Add Helidon Microprofile maven quickstart
> chore : Add Helidon SE and Helidon Microprofile Quickstarts (#1475)

- jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
- jkube-kit/doc/src/main/asciidoc/inc/_generator.adoc
- jkube-kit/doc/src/main/asciidoc/inc/enricher/helidon-healthcheck/_jkube_healthcheck_helidon.adoc
- jkube-kit/doc/src/main/asciidoc/inc/generator/_helidon.adoc
:heavy_check_mark: ~Requires #2129 #2130 to be merged first~
+ Add documentation for HelidonGenerator
+ Add documentation for HelidonHealthCheckEnricher
> doc (jkube-kit/doc) : Add documentation for Helidon framework support (#1475)

- quickstarts/maven/uber-jar/README.md
- quickstarts/maven/uber-jar/pom.xml
- quickstarts/maven/uber-jar/src/main/java/org/eclipse/jkube/sample/uberjar/GreetingCommand.java
Follow up from the discussion we had [here](https://github.com/fabric8io/kubernetes-client/pull/5276#discussion_r1239929710) with @rohanKanojia 🙏 
> Add a uberjar example

- ADOPTERS.md
Fix #2144 
ADOPTERS template taken from [backstage ADOPTERS.md](https://github.com/backstage/backstage/blob/master/ADOPTERS.md) 
Add ADOPTERS.md file to GitHub repository so that users can add their organizations and use cases with Eclipse JKube in ADOPTERS.md file.
> chore : Create ADOPTERS.md file (#2144)

- gradle-plugin/it/src/it/fragments-custom-mapping/build.gradle
- gradle-plugin/it/src/it/fragments-custom-mapping/expected/kubernetes.yml
- gradle-plugin/it/src/it/fragments-custom-mapping/expected/openshift.yml
- gradle-plugin/it/src/it/fragments-custom-mapping/src/main/jkube/first-mtpl.yaml
- gradle-plugin/it/src/it/fragments-custom-mapping/src/main/jkube/second-my_template.yml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/FragmentsIT.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceFragments.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceFragmentsTest.java
- jkube-kit/enricher/api/src/test/resources/kubernetes-resource-fragments/file-name-with-dashes-kind-in-field.yml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/deployment.yml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/template.yml
- quickstarts/maven/spring-boot-crd/pom.xml
Relates to #2219 
- Fragments are completed only if necessary
- Fragments support dashes in file name
- Added integration test to verify custom mappings
> fix: fragment group-version-kind completed only if necessary

- gradle-plugin/doc/pom.xml
- gradle-plugin/kubernetes/pom.xml
- gradle-plugin/openshift/pom.xml
- gradle-plugin/pom.xml
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/VolumeBindingUtil.java
- jkube-kit/parent/pom.xml
- kubernetes-maven-plugin/doc/pom.xml
- kubernetes-maven-plugin/plugin/pom.xml
- kubernetes-maven-plugin/pom.xml
- openshift-maven-plugin/plugin/pom.xml
- openshift-maven-plugin/pom.xml
- pom.xml
- Fix plugin management settings
- Include require settings to allow the creation of a SNAPSHOT release pipeline
> Missing configurations to enable SNAPSHOT release pipelines

- .jenkins/pipelines/release-snapshots.Jenkinsfile
Relates to #2069
Bootstrapped Jenkins CI pipeline to release SNAPSHOTS.
Snapshots will be available at: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/jkube/
Publishing SNAPSHOTs avoid the need for #732 which can be replaced by a quickstart that uses SNAPSHOTs instead.
Once this is merged we can tune the https://ci.eclipse.org/jkube/job/ReleasePipelines/job/ReleaseSnapshots job to use the pipeline from GitHub.
A successful run of this pipeline can be checked at: https://ci.eclipse.org/jkube/job/ReleasePipelines/job/ReleaseSnapshots/10
- https://wiki.eclipse.org/CI_best_practices
- https://wiki.eclipse.org/Jenkins
- https://wiki.eclipse.org/CBI
- https://wiki.eclipse.org/Services/Nexus
While configuring the pipeline I noticed that if directory structure for the project …
> ci: SNAPSHOT release pipeline for Jenkins (https://ci.eclipse.org/jkube)

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
Relates to #2219
First iteration of a refactor to simplify ApplyService
> refactor: initial simplification of ApplyService

- .jenkins/pipelines/release-snapshots.Jenkinsfile
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3361
> ci: clone repo using SSH

- .jenkins/pipelines/release-snapshots.Jenkinsfile
Relates to #2069
ci: notifications for failed SNAPSHOT release
> ci: notifications for failed SNAPSHOT release

- .circleci/config.yml
- .jenkins/pipelines/javadoc.Jenkinsfile
- .jenkins/pipelines/sonar.Jenkinsfile
Part of #2069 
- ci: replace CircleCI Javadoc job with Jenkins
- ci: replace CircleCI Sonar (PR) job with Jenkins
Tasks:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3376
- https://github.com/eclipse-cbi/jiro/pull/286
References:
- https://wiki.eclipse.org/Jenkins#GitHub_Branch_Source_Plugin
- https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/github-webhook-pipeline-multibranch
> spike Jenkins jobs

- .jenkins/pipelines/javadoc.Jenkinsfile
- .jenkins/pipelines/sonar.Jenkinsfile
Part of #2069 
ci: disable concurrent builds
> ci: disable concurrent builds

- .circleci/config.yml
- .jenkins/pipelines/dependencies.Jenkinsfile
- scripts/eclipse-dash-tool.sh
Part of #2069 
ci: replace CircleCI Dependency check job with Jenkins
> ci: replace CircleCI Dependency check job with Jenkins

- .jenkins/pipelines/javadoc.Jenkinsfile
Part of #2069
ci:fix: Javadoc pipeline checks the appropriate branch
> ci:fix: Javadoc pipeline checks the appropriate branch

- .circleci/config.yml
- .jenkins/pipelines/doc-preview.Jenkinsfile
- jkube-kit/doc/pom.xml
- pom.xml
- scripts/generateDoc.sh
Part of #2069
ci: replace CircleCI documentation preview job with Jenkins
> ci: replace CircleCI documentation preview job with Jenkins

- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java
test: HelmServiceIT uses internal Serialization utils
> test: HelmServiceIT uses internal Serialization utils

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/BuildReferenceDateUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java
+ Fixed javadoc warning issues
Fixes #2210
> Fixed javadoc warnings

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootConfigurationHelperTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorIntegrationTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/resources/devtools-application-properties/application.properties
- jkube-kit/jkube-kit-spring-boot/src/test/resources/port-override-application-properties/application.properties
+ Add SpringBootGeneratorIntegrationTest to test SpringBootGenerator
behavior
+ Add test for SpringBootConfigurationHelper for cases that are not
covered by AbstractSpringBootHealthCheckEnricherTest
+ Add additional missing test cases in SprignBootGeneratorTest
> test (jkube-kit-spring-boot) : Add more tests for Spring Boot generator

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceCrudTest.java
test: ApplyService tests prior to further refactoring and method consolidation
> test: ApplyService tests prior to further refactoring and method consolidation

- .jenkins/pipelines/sonar.Jenkinsfile
ci: Sonar has complete report
"Could not find ref 'master' in refs/heads, refs/remotes/upstream or refs/remotes/origin. You may see unexpected issues and changes. Please make sure to fetch this ref before pull request analysis."
> ci: Sonar has complete report

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtilTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/TestFabric8HttpResponse.java
Extracted from #2147 
Add various methods required for performing HTTP requests to
Fabric8HttpUtil. Use Fabric8 K8s Client's HttpResponse abstractions for HTTP
requests.
> refactor (jkube-kit/common) : Add HTTP utility methods to Fabric8HttpUtil

- .circleci/config.yml
- .jenkins/pipelines/sonar.Jenkinsfile
Part of #2069
ci: replace CircleCI test job with Jenkins
As discussed, this pipeline makes no sense since it basically duplicates what the Sonar pipeline does. I added the codecov execution to the Jenkins sonar pipeline to keep that metric.
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3402
[Add CODECOV_TOKEN env variable](https://app.codecov.io/gh/eclipse/jkube/settings)
Requires requesting a new credential for Jenkins
(Not required for merge, but required for codecov to publish the report -can be delayed to after merge-)
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3399
- Disable `ci/circleci: test` check
- Enable `eclipse-jkube/sonar` check (after merge)
> ci: replace CircleCI test job with Jenkins

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/AsyncUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/AsyncUtilTest.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/ArtifactoryHelmRepositoryUploader.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/ChartMuseumHelmRepositoryUploader.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmUploaderManager.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/NexusHelmRepositoryUploader.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/StandardRepositoryUploader.java
- jkube-kit/resource/helm/src/main/resources/META-INF/jkube/helm-uploaders
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUploadIT.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmUploaderManagerTest.java
Extracted from #2147
HelmUploaderManager would use PluginServiceFactory to detect applicable Helm repository uploaders
> refactor (jkube-kit/resource/helm) : Add HelmUploaderManager to manage different Helm repository uploaders

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceCrudTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PatchServiceTest.java
Relates to #2219
refactor: remove consolidate redundant applyXxx methods into applyResource
> refactor: remove consolidate redundant applyXxx methods into applyResource

- gradle-plugin/it/src/it/fragments-custom-mapping/build.gradle
- gradle-plugin/it/src/it/fragments-custom-mapping/expected/kubernetes.yml
- gradle-plugin/it/src/it/fragments-custom-mapping/expected/openshift.yml
- gradle-plugin/it/src/it/fragments-custom-mapping/src/main/jkube/full.yaml
- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/MappingConfig.java
- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/MappingConfigTest.java
- jkube-kit/config/resource/src/test/resources/mapping-config.json
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceFragments.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceFragmentsTest.java
- jkube-kit/enricher/api/src/test/resources/kubernetes-resource-fragments/complete-directory-custom-mappings/custom2.yaml
- jkube-kit/enricher/api/src/test/resources/kubernetes-resource-fragments/complete-directory-custom-mappings/custom3.yaml
- jkube-kit/enricher/api/src/test/resources/kubernetes-resource-fragments/complete-directory-custom-mappings/hello-c1.yaml
- jkube-kit/enricher/api/src/test/resources/kubernetes-resource-fragments/complete-directory-custom-mappings/hello-c3.yaml
- jkube-kit/enricher/api/src/test/resources/kubernetes-resource-fragments/complete-directory-custom-mappings/provided-api-version-c2.yaml
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DependencyEnricherTest.java
- jkube-kit/resource/service/src/main/java/org/eclipse/jkube/kit/resource/service/DefaultResourceService.java
feat: MappingConfig supports defining apiVersion
Should address the last part of #2219
Documentation will be updated in subsequent PR.
> feat: MappingConfig supports defining apiVersion

- README.md
- jkube-kit/README.md
See preview [here](https://github.com/rohanKanojia/jkube/blob/pr/restructure-readme/README.md).
- Update README.md to have table of contents with useful links
- Add Kubernetes Gradle Plugin and OpenShift Gradle Plugin sections
- Add YouTube video demo links to plugin sections
- Remove JKube Kit section from README, at the moment I don't think anyone would be directly using this. Nor users would be interested in the project internal structure.
> chore : Update README.md to have table of contents

- .jenkins/pipelines/sonar.Jenkinsfile
ci: codecov analysis with secret token
Relates to: 
- #2069 
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3402
> ci: codecov analysis with secret token

- README.md
- USING-SNAPSHOT-ARTIFACTS.md
> doc : Add documentation for using jkube snapshots

- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/AbstractSpringBootNestedGenerator.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/FatJarGenerator.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootNestedGenerator.java
Related to #1674
Refactor SpringBootGenerator to use nested generator approach used in Quarkus and Helidon generators. For now, only LegacyJarGenerator is added.
> refactor (jkube-kit-spring-boot) : Refactor SpringBootGenerator to use nested generator approach

- gradle-plugin/it/src/it/vertx/build.gradle
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ITGradleRunnerExtension.java
While adding a gradle integration test for quarkus in #2287 I noticed it's not working with gradle version used in tests. I tried bumping it to 7.6.1 which doesn't seem to involve much changes.
> test (gradle-plugin/it) : Update integration test gradle distribution to v7.6.1

- gradle-plugin/it/src/it/configmap/build.gradle
- gradle-plugin/it/src/it/probes-groovy-dsl-config/build.gradle
- gradle-plugin/it/src/it/simple/build.gradle
- gradle-plugin/it/src/it/spring-boot-with-fragment/build.gradle
- gradle-plugin/it/src/it/spring-boot/build.gradle
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ConfigMapIT.java
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SimpleIT.java
> test: bump Gradle IT Spring Boot dependency

- CHANGELOG.md
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/HelidonIT.java
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SmallRyeIT.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java
Relates to #2299
Should completely fix the issue. Will close as soon as al of the ITs have been updated and `ITGradleRunnerExtension` is configured to use 8.2.1 in a subsequent PR.
> fix: gradle tasks work on Gradle v8.2.1

- .github/workflows/quickstarts.yml
- gradle-plugin/it/pom.xml
- gradle-plugin/kubernetes/pom.xml
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTaskTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTaskTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesUndeployTaskTest.java
- gradle-plugin/openshift/pom.xml
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftUndeployTaskTest.java
- gradle-plugin/pom.xml
- pom.xml
- scripts/eclipse-dash-tool.sh
feat: bump gradle api to 7.6.2
Relates to
- #2299
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9839
> @manusa
> This excerpt from the [handbook](https://www.eclipse.org/projects/handbook/#ip-third-party) seems applicable, since Gradle is a build tool and can be considered the platform that will eventually execute our plugin.
> @rahulmohang
> Hi [@mnuri](https://gitlab.eclipse.org/mnuri),
>
> As of now, we think that this assessment is right. 
> feat: bump gradle api to 7.6.2

- quickstarts/maven/micronaut-customized-image/pom.xml
When running mvn clean install in quickstarts/maven/micronaut-customized-image, we get this warning for  ${parent.version}, now after updating it to  ${project.parent.version} and no warning comes.
Fixes #2310 
Signed-off-by: Prashantkumar Khatri <prashantkhatri202@gmail.com>
> chore (quickstarts) : Updated pom.xml in micronaut-customized-image quickstart (#2310)

- CHANGELOG.md
chore: add missing changelog entry for #2239 / #2287
> chore: add missing changelog entry for #2239 / #2287

- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibLogger.java
- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Serialization.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/assertj/ArchiveAssertions.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceBuildIntegrationTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceGetApplicableRegistryTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java
> For jib mode use registry properties for build "from" image section

- .jenkins/pipelines/release-snapshots.Jenkinsfile
```
java.lang.IllegalArgumentException: The following recipient providers do not support org.jenkinsci.plugins.workflow.job.WorkflowJob hudson.plugins.emailext.plugins.recipients.ListRecipientProvider
at hudson.plugins.emailext.plugins.RecipientProvider.checkAllSupport(RecipientProvider.java:60)
```
> ci:fix: recipientsProviders-recipients() list doesn't work

- gradle-plugin/it/src/it/route-name-fragment/build.gradle
- gradle-plugin/it/src/it/route-name-fragment/expected/openshift.yml
- gradle-plugin/it/src/it/route-name-fragment/src/main/jkube/route.yml
- gradle-plugin/it/src/it/route-name-fragment/src/main/jkube/service.yaml
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/RouteNameAndFragmentIT.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherBehavioralTest.java
fix: route enricher with NAME Service configuration override fragments with default names
Closes #2350
> fix: route enricher with NAME Service configuration override fragments with default names

- CHANGELOG.md
chore: add missing changelog entry for #2091
> chore: add missing changelog entry for #2091

- scripts/jrelease.java
First version of interactive script to release JKube
Usage: 
```
jbang ./scripts/jrelease.java
```
Fixes https://github.com/eclipse/jkube/issues/2202
To be improved in later PRs:
- checks before execution (if running jkube git root folder)
- non interactive mode
- better guessing for remote fork name
- automate some git actions with jgit
- error handling: should detect and fallback to terminal if error with a command
> chore: jbang interactive release script

- CHANGELOG.md
- gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmTask.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ResourceUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/YamlUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/YamlUtilTest.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojoTest.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmMojo.java
Fix #2386: Helm icon inferred from annotations in independent resource files
(not aggregated kubernetes/openshift.yaml)
> fix: Helm icon inferred from annotations in independent resource files

- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
refactor: no need to expose createChartYaml
> refactor: no need to expose createChartYaml

- CHANGELOG.md
- gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionPropertyTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTaskTest.java
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoPluginTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojoPluginTest.java
Fix #2397
Default JKube work directory (`jkube.workDir`) changed from `${project.build.directory}/jkube` to `${project.build.directory}/jkube-temp`
Prevents confusion with the default directories that output production files such as the ones used by our Helm features.
> Default JKube work directory (`jkube.workDir`) changed to target/jkube-temp

- CHANGELOG.md
- gradle-plugin/it/src/it/helm-fragment-and-dsl/expected/values.yaml
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmParameter.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java
- jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/templates/kubernetes.yaml
- jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/values.yaml
- jkube-kit/resource/helm/src/test/resources/it/expected/openshift/templates/openshift.yaml
- jkube-kit/resource/helm/src/test/resources/it/expected/openshift/templates/test-pod.yaml
- jkube-kit/resource/helm/src/test/resources/it/expected/openshift/values.yaml
- jkube-kit/resource/helm/src/test/resources/it/sources/global-template.yml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/helm/templates/helm-and-fragments-configmap.yaml
- kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/helm/templates/helm-and-fragments-deployment.yaml
Fixes #2399
fix: helm no longer generates default function; broadens support for different value types
> fix: helm no longer generates default function; broadens support for different value types

- CHANGELOG.md
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ConfigMapEnricher.java
Fix #2186
In https://github.com/eclipse/jkube/pull/1977, we had moved these methods to a utility class KubernetesResourceUtil which were then ported to fabric8's KubernetesResourceUtil. Now that we've upgraded to that version containing added methods, we can directly rely on these.
+ Remove deprecated methods of `org.eclipse.jkube.kit.enricher.api.util.KubernetesResourceUtil`
+ Update ConfigMapEnricher to use `io.fabric8.kubernetes.client.utils.KubernetesResourceUtil`
> refactor (jkube-kit/enricher) : Reuse `io.fabric8.kubernetes.client.utils.KubernetesResourceUtil` ConfigMap utils methods (#2186)

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
deps: bump JKube base images to 0.0.20
> deps: bump JKube base images to 0.0.20

- jkube-kit/common/pom.xml
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
- jkube-kit/config/resource/pom.xml
- jkube-kit/config/service/pom.xml
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
- jkube-kit/parent/pom.xml
- pom.xml
chore(deps): Bump version.kubernetes-client from 6.8.1 to 6.9.2
> chore(deps): Bump version.kubernetes-client from 6.8.1 to 6.9.2

- CHANGELOG.md
- jkube-kit/doc/src/main/asciidoc/inc/generator/_helidon.adoc
- jkube-kit/doc/src/main/asciidoc/inc/generator/_quarkus.adoc
- jkube-kit/jkube-kit-helidon/src/test/java/org/eclipse/jkube/helidon/generator/HelidonGeneratorTest.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorIntegrationTest.java
- jkube-kit/parent/pom.xml
- kubernetes-maven-plugin/it/src/it/xml-image-multilayer/expected/Dockerfile
- kubernetes-maven-plugin/it/src/it/xml-image-multilayer/expected/Dockerfile.second-image
- kubernetes-maven-plugin/it/src/it/xml-image-multilayer/pom.xml
- kubernetes-maven-plugin/it/src/it/xml-image/expected/Dockerfile
- kubernetes-maven-plugin/it/src/it/xml-image/pom.xml
Fixes #2433
Update default docker native base image from `registry.access.redhat.com/ubi8/ubi-minimal:8.7` to `registry.access.redhat.com/ubi9/ubi-minimal:9.3`
> fix : Update default native base docker image to `registry.access.redhat.com/ubi9/ubi-minimal:9.3` (#2433)

- CHANGELOG.md
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SpringBootIT.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/LayeredJarGenerator.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorIntegrationTest.java
Fixes #2436
fix: debug functionality works with Spring Boot Layered JARs
> fix: debug functionality works with Spring Boot Layered JARs

- quickstarts/maven/spring-boot/pom.xml
As part of the fix for #2436 I updated the quickstart to Spring Boot v2.7.17
> chore(quickstarts): bump spring-boot to v2.7.17

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
Closes #1690
Base images are now based on ubi9
> deps: bump JKube base images to 0.0.21

- CHANGELOG.md
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/Chart.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/ChartTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
- jkube-kit/resource/helm/src/test/resources/valid-helm-fragments/Chart.helm.yaml
> fix: support for all missing Chart.yaml fields

- CHANGELOG.md
- gradle-plugin/it/src/it/spring-boot-properties/build.gradle
- gradle-plugin/it/src/it/spring-boot-properties/expected/kubernetes.yml
- gradle-plugin/it/src/it/spring-boot-properties/expected/openshift.yml
- gradle-plugin/it/src/it/spring-boot-properties/src/main/java/org/eclipse/jkube/it/gradle/spring/boot/Application.java
- gradle-plugin/it/src/it/spring-boot-properties/src/main/resources/application.properties
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SpringBootPropertiesIT.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootPropertyPlaceholderHelper.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootPropertyPlaceholderHelperTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
- jkube-kit/common/src/test/resources/util/springboot/spring-boot-complex-application.properties
Fixes #2444
feat: add support for Spring Boot application properties placeholders
> feat: add support for Spring Boot application properties placeholders

- .jenkins/pipelines/sonar.Jenkinsfile
Fixes #2428 
Update Sonar CI Pipeline's JVM version to `temurin-jdk17-latest` from `temurin-jdk11-latest`
> ci : Update Sonar CI pipeline to Java 17 (#2428)

- CHANGELOG.md
- gradle-plugin/it/src/it/helm-dsl/expected/Chart.yaml
- gradle-plugin/it/src/it/helm-fragment-and-dsl/expected/Chart.yaml
- gradle-plugin/it/src/it/helm-fragment/expected/Chart.yaml
- gradle-plugin/it/src/it/helm-properties/expected/Chart.yaml
- gradle-plugin/it/src/it/helm-zero-config/expected/Chart.yaml
- jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm.adoc
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmConfigTest.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoTest.java
Fix #2472
Adds the appVersion field to the HelmConfig class so that it can be propagated from the Helm plugin configuration and the `jkube.helm.appVersion` property.
The field is now provided by default with the current project version (i.e. by default Chart.yaml appVersion and version default to the same value)
> feat(helm): Support for Helm Chart.yaml appVersion field defaulting to project version

- jkube-kit/build/service/buildpacks/pom.xml
- jkube-kit/pom.xml
Related to #2454
Add new empty module `jkube-kit/build/service/buildpacks`
This module contains all the required classes for BuildPack related classes like BuildPackCLIController, BuildPackBuildCommand, BuildPackCLIDownloader etc. I'll add them in follow up PRs
> feat (jkube-kit) : Bootstrap JKube BuildPack build service module (#2454)

- CHANGELOG.md
- jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/FastJarGenerator.java
- jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
Fixes https://github.com/eclipse/jkube/issues/2257
This contribution was initially included in PR #2244, but it was later removed due to its lack of direct relevance to the changes introduced in that pull request.
This PR revisits and completes the fix initially provided by https://github.com/eclipse/jkube/pull/1408. Specifically, it addresses the issue in Quarkus projects to ensure comprehensive resolution.
> feat(jkube-kit/generator): Provide guidance when the final project package in Quarkus projects

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ExternalCommand.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/SpringBootLayeredJar.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/LayeredJarGenerator.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootNestedGenerator.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/SpringBootLayeredJarTest.java
> fix: support for Spring Boot 3.2.0 (and newer) layered jar format

- jkube-kit/common-it/pom.xml
- jkube-kit/parent/pom.xml
- kubernetes-maven-plugin/pom.xml
- openshift-maven-plugin/pom.xml
- pom.xml
JMockit dependency is no longer used, remove references.
- [] Bug fix (non-breaking change which fixes an issue)
> refactor: remove jmockit dependency

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/AuthConfig.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuth.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/KubernetesConfigAuthUtil.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/AuthConfigTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuthTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/FromConfigRegistryAuthHandlerTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/SystemPropertyRegistryAuthHandlerTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java
- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactoryTest.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Serialization.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
The only remaining usages are in the `PortMapping` class that should be addressed as part of #2481 
> refactor: remove `com.google.*` dependent code from the `jkube-kit-build-api` module

- quickstarts/maven/spring-boot-helm/README.md
- quickstarts/maven/spring-boot-helm/pom.xml
- quickstarts/maven/spring-boot-helm/src/main/jkube/service.yml
- quickstarts/maven/spring-boot-helm/src/main/jkube/template.yaml
- quickstarts/maven/spring-boot-helm/src/main/jkube/values.helm.yaml
doc: improved spring-boot-helm example to be clear about dev and prod
Relates #2479 
> doc: improved spring-boot-helm example to be clear about dev and prod

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ExternalCommand.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ExternalCommandTest.java
Related to https://github.com/eclipse/jkube/issues/2453
In order to read command's errorStream during failure, we need to refactor ExternalCommand to expose this logic so that child classes can override this logic as per the default behavior (i.e logging it as a warn message)
> refactor(jkube-kit/common): Extract errorStream processing in ExternalCommand enabling overrides

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/ArchiveDecompressor.java
refactor: ArchiveDecompressor uses Path
> refactor: ArchiveDecompressor uses Path

- CHANGELOG.md
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/AuthConfigTest.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuthTest.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Serialization.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
Fixes #2389
Add additional Jackson configuration `SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS` to sort keys alphabetically. 
This would change the ordering of YAML content that is written by JKube. Not sure whether users might be relying on ordering. If yes, it can be considered a breaking change.
> fix (jkube-kit/resource/helm) : Helm `values.yaml` sorted alphabetically

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
> deps: bump jkube-images to 0.0.23

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/ArchiveDecompressor.java
- kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
Adding information on annotations with special characters
This PR updates the documentation to provide information on special characters in kubernetes annotations
[Documentation preview](https://ci.eclipse.org/jkube/job/Build/job/Documentation/job/PR-2506/3/artifact/docs-generated/kubernetes-maven-plugin.html#xml-configuration)
Fixes #2505
> Update on how to handle properties with slashes as names with a human readable example

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java
removes redundant assertion
Fixes #2514
> removes redundant assertion

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceCrudTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java
refactor: ApplyService only accessible through JKubeServiceHub
> refactor: ApplyService only accessible through JKubeServiceHub

- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameDistributionReferenceTest.java
- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameORASReferenceTest.java
Add tests for ImageName for ORAS reference and Docker Distribution reference. These tests mainly test the `ParseReference` functionality in upstream equivalents.
- ImageNameORASReferenceTest to test compatibility with  [OCI Registry As Storage (ORAS) reference](https://github.com/oras-project/oras-go/blob/main/registry/reference_test.go)
- ImageNameDistributionReferenceTest to test compatibility with [Docker Distribution reference](https://github.com/distribution/reference/blob/main/reference_test.go)
This also includes some cases that might not be available in the latest versions of Docker. For example, support for IPv6 registries was added in https://github.com/distribution/distribution/pull/3489 but I didn't find it in Docker v24.0.7 
The tests that have been commented out represent …
> test (jkube-kit) : Add ImageName upstream compatibility tests

- CHANGELOG.md
- jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRepositoryUploader.java
- jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRepositoryUploaderTest.java
Fixes #2314
Add ImageName constructor call to verify name of the provided helm chart is a valid OCI artifact name
> fix (jkube-kit/resource/helm) : Add chart name validation before doing Helm OCI push

- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/BuildConfigurationTest.java
JKubeConfigurationTest uses deprecated ObjectMapper.configure method 
Fixes #2528
> refactor:JKubeConfigurationTest uses deprecated ObjectMapper.configure method

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/CommandLine.java
> removed cloneable interface from CommandLine.java file

- jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarder.java
> refactor: KubernetesSshServiceForwarder uses deprecated method

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java
Fixes #2522 refactor: replaced deprecated method createOrReplace with createOr method.
> Issue-Fix-#2522 refactor: changed deprecated method

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/UrlBuilder.java
Fixes [#2567](https://github.com/eclipse/jkube/issues/2567)
The fields in [UrlBuilder.Builder](https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/UrlBuilder.java#L246-L247) class changed to be 'final'.
All checks in the [DockerAccessWithHcClientTest](https://github.com/eclipse/jkube/blob/a1fcb571333121eef45810487e046672c65e90c2/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClientTest.java#L48) and [DockerAccessWithHcClientMockitoTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClientM …
> fix: fixed UrlBuilder jkube-kit final fields

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/SuffixFileFilter.java
> SuffixFileFilter.suffix field may be final

- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/RemoteDevelopmentServiceTest.java
Fixes #2576
Fix intermittent failures on CI related to RemoteDevelopmentServiceTest
> test (jkube-kit/remote-dev) : Fix intermittent failures of RemoteDevelopmentServiceTest

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ExternalCommandTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/ArchiveDecompressorTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SerializationTest.java
Fixes #2563 : Fixes failing unit tests for windows in ```jkube-kit/common``` package.
All the units tests are passing while running ```mvn clean install``` on Windows now.
> fix : fixed broken unit tests for `jkube-kit/common` on windows

- jkube-kit/helm/pom.xml
- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmRepositoryConnectionUtils.java
- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptorTest.java
refactor(helm): remove unneeded apache httpclient dependency
> refactor(helm): remove unneeded apache httpclient dependency

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/EnricherConfigTest.java
Replaced `org.mockito` reference from EnricherConfigTest to builders
Fixes #2597
> chore(jkube-kit-enricher-api): Replaced org.mockito references from EnricherConfigTest with builders #2597

- jkube-kit/parent/pom.xml
- pom.xml
Fixes: #2392
feat(helm): add helm-java dependency
> feat(helm): add helm-java dependency

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricherCreateTest.java
> DefaultControllerEnricherCreateTest.setUp The declared Exception exception is never thrown issue #2592

- quickstarts/maven/hello-world/pom.xml
- quickstarts/maven/tomee/pom.xml
Fixes #2612 
Removed unused run configuration from quickstarts/maven/hello-world and quickstarts/maven/tomee. Then I have confirmed that container image is pushed successfully.
> fix(quickstarts/maven): Removed unused run configuration

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JKubeException.java
- jkube-kit/helm/pom.xml
- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceLintIT.java
- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
> feat: HelmService provides linting features

- gradle-plugin/it/src/it/helm-lint/build.gradle
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/HelmLintIT.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesPlugin.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmLintTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmLintTaskTest.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmLintTask.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmLintTaskTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmLintMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/GeneratedPluginDescriptorTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmLintMojoTest.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmLintMojo.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/OpenShiftGeneratedPluginDescriptorTest.java
Part of https://github.com/eclipse/jkube/issues/2613
Exposed Helm linting capabilities in the Gradle and Maven plugins for OpenShift and Kubernetes.
> feat: helm lint exposed in Gradle and Maven plugins

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/JKubeEnricherContextTest.java
Fixes #2616 
Removed org.mockito.Mockito references from JKubeEnricherContextTest and added real objects.
> chore(jkube-kit-enricher-api): Removed org.mockito.Mockito references from JKubeEnricherContextTest

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesDebugTaskTest.java
> KubernetesDebugTaskTest.setUp The declared Exception exception is never thrown

- gradle-plugin/it/src/it/controller/expected/daemonset/kubernetes.yml
- gradle-plugin/it/src/it/controller/expected/replicaset/kubernetes.yml
- gradle-plugin/it/src/it/controller/expected/statefulset/kubernetes.yml
- gradle-plugin/it/src/it/dependency-resources/expected/kubernetes-defaults.yml
- gradle-plugin/it/src/it/dependency-resources/expected/kubernetes-with-replica-override.yml
- gradle-plugin/it/src/it/metadata/expected/kubernetes-replicaset-controller.yml
- gradle-plugin/it/src/it/triggersannotation/expected/kubernetes.yml
- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricher.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricherTest.java
- kubernetes-maven-plugin/it/src/it/dependency-resources/expected/kubernetes.yml
Fixes #2559
Added a check in the enriching process to only do it if the Kubernetes environment is OpenShift. Also added 2 new unit tests and updated releevant unit tests.
> bug:TriggersAnnotationEnricher should not execute in PlatformMode.kubernetes 

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricherTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojo.java
Fields with matching name in AbstractJKubeMojo are removed from UndeployMojo
Fixes #2636 
> Fields with matching name in AbstractJKubeMojo are removed from UndeployMojo

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java
Fixes #2674
enableImageChangeTrigger type is changed to boolean; trimImageInContainerSpecFlag type is changed to boolean; isImageChangeTriggerNeeded method return type changed to boolean; enrichAll field on line 116 type changed to boolean.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
- [x ] No …
> ImageChangeTriggerEnricher : Replace boxed Boolean with primitive boolean type #2674

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmTaskTest.java
> chore: removing redundant exception declaration at gradle-plugin/KubernetesHelmTaskTest

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricherTest.java
> chore: remove unThrown exception from DefaultControllerEnricherTest.setUp

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultMetadataEnricherTest.java
> test: remove redundant Exception declaration in DefaultMetadataEnricherTest.setUp (#2594)

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/IngressEnricherBehavioralTest.java
> test: remove redundant Exception declaration in IngressEnricherBehavioralTest.setUp (#2595)

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitorTest.java
Fixes #2679 
Replaced line feed with platform dependent line separator to cover testcase for Windows.
> Issue-Fix-#2679 chore(test): replaced line feed with platform dependent line separator

- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandler.java
Fixes #2637 
- [x ] I Added [CHANGELOG](../CHANGELOG.md) entry
- [x ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
- [ x] No new bugs, code smells, etc. in …
> Removed function getAnnotations and replaced function calls

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/GitEnricher.java
> return emptymap instead null in case of Exception#2710

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/MavenIssueManagementEnricherTest.java
> Removed unnecessary exception - Signed-off-by Abhiram Karri

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
> Chore: KubernetesHelperTest.setUp: Remove "throws Exception"

- pom.xml
> deps: bump helm-java from 0.0.3 to 0.0.6

- CHANGELOG.md
> chore: missing changelog for #2726

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceBuildIntegrationTest.java
Change the base image to specify explicit image digest instead of pulling the latest tag, which caused the test to fail.
Fixes #2742
> chore: fix failing JibBuildServiceBuildIntegrationTest due to JIB build image

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesRemoteDevTaskTest.java
> Removed exception that is never thrown #2717

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojoTest.java
> refactor WatchMojo and WatchMojoTest classes

- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
> Added lombok getter for name #2712

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
Fixes #2750
test: removed non-thrown declared IOexception from the method signature.
> #2750 Fixed SpringBootUtilTest: The declared Exception exception is never thrown.

- scripts/quickstarts.sh
chore(scripts): log project information in quickstarts.sh
> chore(scripts): log project information in quickstarts.sh

- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageConfigurationTest.java
Fixes #2755 
Replaced mock with concrete implementation of `BuildConfiguration` in `ImageConfigurationTest`
> Issue-Fix-#2755 chore(test): replaced mocks with concrete implementation

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTask.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JKubeException.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JKubeExceptionTest.java
- jkube-kit/profile/src/main/java/org/eclipse/jkube/kit/profile/ProfileUtil.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
+ Port KubernetesClientException.launderThrowable to JKubeException so
that we can wrap checked exceptions inside it.
+ Use abovementioned method in `ProfileUtil.blendProfileWithConfiguration`
+ Fix typo in method name `extractProcesssorConfiguration`
> refactor (jkube-kit/common) : Add `launderThrowable` method to JKubeException

- quickstarts/maven/micronaut-customized-image/pom.xml
- quickstarts/maven/micronaut/pom.xml
Update of to the latest 3.9.x version of micronaut
Fixes #2753
> Update the version of micronaut

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/ConfigHelper.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/ConfigHelperTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftBuildMojo.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftWatchMojo.java
~Requires #2766 #2765 to be merged first~
Refactor as mentioned in https://github.com/eclipse/jkube/pull/2378#issuecomment-1970800274
+ Remove `ConfigHelper.Customizer` interface from AbstractDockerMojo, AbstractJKubeMojos; mojos would directly pass a `GeneratorManager` to ConfigHelper which will invoke `generatorManage.generate` in `ConfigHelper.initImageConfiguration`
+ Add a helper class JKubeMojoUtils to keeping common methods between mojos, for scope of this change it only includes `createGeneratorContextBuilder` and `extractGeneratorConfig`
> refactor (kubernetes-maven-plugin) : Remove `ConfigHelper.Customizer` interface references from Mojos

- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorMainClassDeterminationTest.java
Fixes #2776 
Specified the parent directory for `fatJarArchive` in the `File` Class constructor.
> Issue-Fix#2776 chore(test): specified parent directory for `fatJarArchive`

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/ConfigHelper.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/ConfigHelperTest.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/GeneratorManager.java
- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/DefaultGeneratorManager.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/DefaultGeneratorManagerTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
There is `prePackagePhase` field present in GeneratorContext, Use the already present context field rather than providing an additional argument to method
> refactor (jkube-kit) : Remove `isPrePackagePhase` parameter from `GeneratorManager.generate` method

- jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java
> Fixed WildflyJARHealthCheckEnricherTest.setUp Exception

- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojoTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmLintMojoTest.java
Fixes #2777 
For `BuildMojoTest`:
Updated assertion statement to replace Linux file separator with platform dependent file separator.
For `HelmLintMojoTest`:
Replaced Line Feed with platform dependent line separators using `String.format()` and `%n`.
> Issue fix #2777 chore(test): fixed failing tests for windows in `kubernetes-maven-plugin`

- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/BuildConfigurationTest.java
Replace mock object by lombok builders in BuildConfigurationTest class
Fixes #2756 
- [] I have added tests that prove my fix is effective or that my feature works
> Replace mock object by lombok builders in BuildConfigurationTest class

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java
Replace loop for with Stream API
Use primitive int instead of Integer in for loop, replace loop of Map by Collection stream.
Fixes #2757 
> Replace Integer type by int one in SecretEnricher class

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
> #2813: Removed expression which always evaluates to false

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
> Modified size to isEmpty

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
> refactor: remove unused import from DefaultServiceEnricher

- CHANGELOG.md
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTask.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/JKubeBuildStrategy.java
- jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherContext.java
- jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherManager.java
- jkube-kit/watcher/api/src/test/java/org/eclipse/jkube/watcher/api/WatcherManagerTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
Fixes #2461
+ Add JKubeBuildStrategy field to WatcherContext
+ Throw exception when JKubeBuildStrategy.buildpacks is provided
> fix (jkube-kit): `k8s:watch`/`k8sWatch` should throw error in `buildpacks` build strategy

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmLintTaskTest.java
This PR contains the changes where the exception declaration is removed as it was never thrown.
Fixes #2668 
> Fix: #2668 Removed the declared exception which was never thrown

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- pom.xml
- quickstarts/gradle/docker-file-provided-context-and-assembly/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/docker-file-provided-context-and-file/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/docker-file-provided-context-dir/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/docker-file-provided-docker-file/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/docker-file-simple/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/groovy-dsl-config/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/micronaut-customized-image/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/micronaut/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/micronaut4/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/openliberty/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/plugin/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/quarkus-customized-image/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/quarkus/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/spring-boot-camel-complete/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/spring-boot-crd/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/spring-boot-helm/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/spring-boot-watch/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/spring-boot-with-jib-assembly/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/spring-boot/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/vertx/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/webapp-custom/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/webapp-jetty/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/webapp-wildfly/gradle/wrapper/gradle-wrapper.properties
- quickstarts/gradle/webapp/gradle/wrapper/gradle-wrapper.properties
- quickstarts/kit/custom-foo-generator/app/gradle/wrapper/gradle-wrapper.properties
- quickstarts/kit/custom-foo-generator/foo-generator/gradle/wrapper/gradle-wrapper.properties
- quickstarts/kit/custom-istio-enricher-gradle/gradle/wrapper/gradle-wrapper.properties
chore(deps): Bump version.kubernetes-client from 6.10.0 to 6.11.0
> chore(deps): Bump version.kubernetes-client from 6.10.0 to 6.11.0

- CHANGELOG.md
- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ControllerResourceConfig.java
- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandler.java
- kubernetes-maven-plugin/it/src/it/nodeSelector/expected/kubernetes.yml
- kubernetes-maven-plugin/it/src/it/nodeSelector/invoker.properties
- kubernetes-maven-plugin/it/src/it/nodeSelector/pom.xml
- kubernetes-maven-plugin/it/src/it/nodeSelector/src/main/java/org/eclipse/jkube/GreetingResource.java
- kubernetes-maven-plugin/it/src/it/nodeSelector/verify.groovy
> feat(controller-enricher): Add support for configuring nodeSelector spec for controller via xml/groovy DSL configuration

- quickstarts/maven/spring-boot-with-jib/src/main/java/org/eclipse/jkube/maven/sample/springboot/jib/HelloController.java
> Switched to GetMapping annotation 

- quickstarts/maven/quarkus-customized-image/pom.xml
- quickstarts/maven/quarkus-customized-image/src/main/java/org/eclipse/jkube/quickstart/quarkus/rest/CoolApplicationResource.java
- quickstarts/maven/quarkus-customized-image/src/main/java/org/eclipse/jkube/quickstart/quarkus/rest/CoolApplicationService.java
Fixes #2811 
Updated `Quarkus` version to `3.9.1` and fixed all the breaking imports.
> Issue fix #2811 chore (quickstarts/maven/quarkus-customized-image): Updated to latest version of Quarkus 

- quickstarts/maven/quarkus-customized-image/pom.xml
> fix(quickstart): set quarkus-compatible base image

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
> ResourceMojo : Remove unused private field useReplicaSet

- quickstarts/maven/spring-boot/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/HelloController.java
> Changed annotation to GetMapping 

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
> PortForwardServiceTest : Remove use of Thread.sleep #2752

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/RemoteDevMojo.java
Fixes #2779 
- x ] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
- [x ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) I am a user that has signed ECA "Signed-off-by:Mary Gurrieri \ <mgurrie@clemson.edu>"
- [ x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
- [ x] …
> issue 2779 fixed 

- quickstarts/maven/vertx4/pom.xml
Fixes #2874
This PR updates the Vert.x version in the vertx4 quickstart project to 4.5.7. The update ensures compatibility with the latest improvements and bug fixes in Vert.x.
Bug fix (non-breaking change which fixes an issue)
I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
My code follows the style guidelines of this project
I have performed a self-review of my code
I have added tests that prove my fix is effective or that my feature works
New and existing unit tests pass locally with my changes
I tested my code in Kubernetes
I tested my code in OpenShift
> Updated the Vert.x version to 4.5.7

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtils.java
Fixes bug introduced in https://github.com/eclipse/jkube/pull/2895
```
[ERROR] Failed to execute goal org.eclipse.jkube:openshift-maven-plugin:1.17-SNAPSHOT:build (default-cli) on project jkube-maven-sample-node-selector: Failed to execute the build: Unable to build the image using the OpenShift build service: Cannot invoke "java.util.Map.entrySet()" because the return value of "org.eclipse.jkube.kit.config.image.build.BuildConfiguration.getArgs()" is null -> [Help 1]
```
Not sure how it got through the unit tests ...
> fix(oc-build): image build should not fail if no build args is provided

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTaskTest.java
> KubernetesHelmPushTaskTest.setUp The declared Exception exception is never thrown is removed #2669

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java
> Fix : #2870 Updated map parameter types

- .jenkins/pipelines/release-snapshots.Jenkinsfile
ci: typo in release snapshot fixed message
> ci: typo in release snapshot fixed message

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
> KubernetesHelperTest Remove unused imports #2926

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginRegisterTaskTest.java
>  refactor: remove unused import from KubernetesPluginRegisterTaskTest.java

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTask.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/ConfigHelper.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/ConfigHelperTest.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/GeneratorManager.java
- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/DefaultGeneratorManager.java
- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/GeneratorContext.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/DefaultGeneratorManagerTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
+ `ConfigHelper.initImageConfiguration` which is modifying and filtering ImageConfiguration lists is better
suited to be placed inside GeneratorManager rather than some static utility method.
+ Add new fields `buildTimestamp`, `sourceDirectory`, `filter` to GeneratorContext (they are required by now that the image resolver logic is moved to GeneratorManager)
> refactor (jkube-kit) : Move `ConfigHelper.initImageConfiguration` to `GeneratorManager.generateAndMerge`

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
> KubernetesHelper : Replace call to toArray() with a pre-sized array argument with empty array #2837

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java
Fixes # https://github.com/eclipse-jkube/jkube/issues/2965
> remove unused import in OpenShiftBuildServiceUtilsTest

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ConfigMap.java
Fixes https://github.com/eclipse-jkube/jkube/issues/2972
> add Lombok annotations in org.eclipse.jkube.kit.config.resource.ConfigMap class

- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryEndpoint.java
Removed unused import in OCIRegistryEndpoint class
Fixes #2963
> Issue : 2963, Removed unused import in OCIRegistryEndpoint class

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
Fixes https://github.com/eclipse-jkube/jkube/issues/2971
> replace iteration with bulk Collection.addAll() call

- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptorTest.java
Removes unused import from OCIRegistryInterceptorTest class
Fixes #2964
> Issue #2964, remove unused imports from OCIRegistryInterceptorTest

- gradle-plugin/doc/src/main/asciidoc/index.adoc
- kubernetes-maven-plugin/doc/src/main/asciidoc/index.adoc
Currently, the titles of our plugin documentation pages aren't sufficiently human-readable:
- the titles don't clearly indicate that they are for documentation
- while `org.eclipse.jkube/kubernetes-maven-plugin` is suitable in code, it's not as effective as a webpage title
> docs: Improve readability of Eclipse JKube plugin documentation titles

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
- kubernetes-maven-plugin/plugin/src/main/resources/META-INF/plexus/components.xml
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojoTest.java
- openshift-maven-plugin/plugin/src/main/resources/META-INF/plexus/components.xml
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftResourceMojoTest.java
> refactor: remove unused component

- jkube-kit/profile/src/test/java/org/eclipse/jkube/kit/profile/ProfileUtilTest.java
> Chore #3023: Remove unused imports in ProfileUtilTest

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/RemoteDevMojo.java
Fixes  #3025 
Removes unused imports in RemoteDevMojo.java
> chore: Remove unused imports in RemoteDevMojo.java

- jkube-kit/doc/src/main/asciidoc/inc/_integrations.adoc
+ Move default buildpack builder image section to top
+ Add section for configuring buildpack builder image using `jkube.generator.buildpacksBuilderImage` property
> doc (jkube-kit/doc) : Restructure BuildPacks Builder Image section in BuildPack Integration

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/portforward/PortForwardPodWatcherTest.java
Fixes #3022
fix: PortForwardPodWatcherTest Remove unused imports (3022)
- [] I Added [CHANGELOG](../CHANGELOG.md) entry
- [] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
> fix: PortForwardPodWatcherTest Remove unused imports (3022)

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PodLogServiceTest.java
> Remove unused import

- jkube-kit/jkube-kit-helidon/src/test/java/org/eclipse/jkube/helidon/generator/HelidonGeneratorExposedPortsTest.java
Replace AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class))
Fixes #3059
> HelidonGeneratorExposedPortsTest : Replace AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class))

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ExternalCommandTest.java
Command `ls` may finish with different exit codes on different operating systems. Modified the test case `execute_whenCommandFailed_thenThrowException` to assert the non-zero exit code.
Fixes #3006
> Fix assertion to check for non-zero status code in ExternalCommandTest

- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorIntegrationTest.java
Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in class`SpringBootGeneratorIntegrationTest`.
Fixes #3058
> fix SpringBootGeneratorIntegrationTest: replace AssertJ's deprecated method asList()

- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
Remove getter methods and use Lombok `@Getter` annotation in HelmConfig.HelmType
Fixes #2930
> fix: remove getter methods and use lombok @Getter in HelmConfig.HelmType

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/AuthConfig.java
- jkube-kit/build/service/jib/pom.xml
- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibService.java
- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceIntegrationTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceTest.java
- Created the initial JibService abstraction layer
- Added integration tests for push operations
- Removed redundant JibServiceUtil helper methods
> refactor: introduce JibService abstraction layer for push

- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibService.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/TestAuthConfigFactory.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildService.java
refactor: JibService uses AuthConfigFactory interface
> refactor: JibService uses AuthConfigFactory interface

- CHANGELOG.md
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/config/property/ConfigKey.java
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/config/property/PropertyConfigResolver.java
- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/config/property/PropertyConfigResolverTest.java
- jkube-kit/build/service/jib/pom.xml
- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibService.java
- jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java
- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceBuildTest.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServicePushTest.java
- jkube-kit/doc/src/main/asciidoc/inc/_integrations.adoc
- jkube-kit/doc/src/main/asciidoc/inc/build/_configuration.adoc
feat: multiplatform build support (jib)
Fixes #2098
> feat: multiplatform build support (jib)

- CHANGELOG.md
- jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackBuildOptions.java
- jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/controller/BuildPackCliController.java
- jkube-kit/build/service/buildpacks/src/test/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackCliControllerTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildServiceTest.java
Related to #2463
+ Add clearCache boolean option to BuildPackBuildOptions
+ Add `--clear-cache` flag to pack CLI command line arguments when clearCache is set to `true`
+ Configure BuildPackBuildService to set clearCache when nocache is enabled in image build configuration
> feat (jkube-kit/build) : Clear BuildPack cache when nocache is enabled in build configuration

- README.md
chore: remove CircleCI badge from README
> chore: remove CircleCI badge from README

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesPlugin.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmDependencyUpdateTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmDependencyUpdateTaskTest.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmDependencyUpdateTask.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmDependencyUpdateTaskTest.java
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmDependencyUpdateMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/GeneratedPluginDescriptorTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/KubernetesHelmDependencyUpdateMojoTest.java
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmDependencyUpdateMojo.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/OpenShiftGeneratedPluginDescriptorTest.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmDependencyUpdateMojoTest.java
Related to #2110 
Expose Helm Dependency Update functionality added in HelmService via maven plugins' Mojos and Gradle Plugins' tasks.
> feat : Helm Dependency Update exposed via mojos and gradle tasks

- pom.xml
chore(deps): Bump version.kubernetes-client from 6.12.1 to 6.13.0
> chore(deps): Bump version.kubernetes-client from 6.12.1 to 6.13.0

- CHANGELOG.md
- jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackBuildOptions.java
- jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/controller/BuildPackCliController.java
- jkube-kit/build/service/buildpacks/src/test/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackCliControllerTest.java
- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildService.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildServiceTest.java
Fixes #3122
+ Add new field `appDirPath` to BuildPackBuildOptions to store application directory path
+ Pass abovementioned application directory path while running `pack build` by using `--path` flag during buildpacks build
> fix (jkube-kit/build/service/buildpacks) : JKube should also pass project directory in `buildpacks` build strategy

- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
Removed an unused import from WatchMojo.java file.
Fixes #3100
- Removed unused imports at class [WatchMojo](https://github.com/eclipse-jkube/jkube/blob/4cccc93af16fc7dbceee99c385fece3691bc7f56/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java#L17)
- [x ] Bug fix (non-breaking change which fixes an issue) …
> fix: removed unused imports.

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SerializationTest.java
> SerializationTest is failing #3113

- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
> HelmServiceTest is failing #3116

- gradle-plugin/it/src/it/git-annotations/expected/kubernetes.yml
- gradle-plugin/it/src/it/git-annotations/expected/openshift.yml
The changes introduced in #2831 to sanitize git URLs before adding them to Kubernetes resource annotations make the Gradle GitAnnotationsIT fail on specific environments.
This PR updates the regex in `kubernetes.yml` / `openshift.yml` expected files for git-annotations integration test to pass regardless of the remote URI.
> test (gradle-plugin/it) : Update `git-url` regex in expected git annotation integration test manifests

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/RemoteSpringBootDevtoolsCommand.java
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/RemoteSpringBootDevtoolsCommandTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java
- jkube-kit/jkube-kit-spring-boot/src/test/resources/dummy-java
- jkube-kit/jkube-kit-spring-boot/src/test/resources/failing-java
Fixes #2168
+ Create a new class RemoteSpringBootDevtoolsCommand that will extend
ExternalCommand class for starting remote spring boot process for
watch
+ SpringBootWatcher uses abovementioned class for running remote spring
application instead of directly using `Runtime.exec`
> refactor (jkube-kit) : SpringBootWatcher uses ExternalCommand for starting spring devtools process

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/AssemblyConfigurationTest.java
1. Replace AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class))
2. Substitute `hasSize(1).first()` with `singleElement()`
Fixes #3134 
> chore(deprecated assertions): Replace AssertJ's deprecated asList() DSL method

- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java
Replace statement lambda with expression lambda for JibServiceTest.build and JibServiceTest.buildMultiplePlatforms
Fixes #3135 
> #3135 Replace statement lambda with expression lambda for JibServiceTest.build and JibServiceTest.buildMultiplePlatforms

- jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilder.java
> Issue #3103 -- In DockerFileBuilder.java declared a field (private String source) to final

- CHANGELOG.md
> chore: added missing changelog entry for #3036/#2665

- gradle-plugin/it/src/it/spring-boot-managementhealthprobes/build.gradle
- gradle-plugin/it/src/it/spring-boot-managementhealthprobes/expected/kubernetes.yml
- gradle-plugin/it/src/it/spring-boot-managementhealthprobes/expected/openshift.yml
- gradle-plugin/it/src/it/spring-boot-managementhealthprobes/src/main/java/org/eclipse/jkube/it/gradle/spring/boot/Application.java
- gradle-plugin/it/src/it/spring-boot-managementhealthprobes/src/main/resources/application.properties
- gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SpringBootManagementHealthProbesIT.java
Related to #2665
Add gradle integration test to verify that SpringBootHealthCheckEnricher adds `/actuator/health/readiness` for readiness probe and `/actuator/health/liveness` for liveness probe when `management.health.probes.enabled` property is enabled in application.properties
> test (gradle-plugin/it) : Add E2E test to verify SpringBootHealthCheckEnricher detects management health probe endpoints

- jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherManager.java
> fix: removed unused import from WatcherManager class

- jkube-kit/common-it/src/main/java/org/eclipse/jkube/kit/common/ResourceVerify.java
Fixes #2841 
Fixed `readFile()` in `ResourceVerify` to add the platform specific line separator.
> Issue-Fix-#2841 chore(test): fixed readFile() in ResourceVerify for Windows

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceBuildTest.java
Fixes #3137 
Fixed `build_shouldLogBuiltTarImage()` for Windows by modifying `assert` statement.
> Issue-Fix-#3137 chore(test): fixed build_shouldLogBuiltTarImage() for windows

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
Required for #3142 
Add a utility class that would write a `kubeconfig` file by inspecting various attributes of KubernetesClient's configuration object.
> feat (jkube-kit/common) : Add utility class for exporting KubernetesClient configuration to a kubeconfig

- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojoTest.java
Add new tests to verify push/pull config when init HelmPushMojo
Fixes #3068 
> chore(push/pull config): add new tests to verify push/pull config when init HelmPushMojo

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/OpenshiftHelperTest.java
Fixes #3158
Replaced AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class)).
> fix: Replace deprecated method.

- pom.xml
Related to https://github.com/eclipse-jkube/jkube/pull/3142
I need latest version of Helm Java Library for a test in #3142 . I have tested by bumping the version and checking that the test works with the functionality provided in the latest release.
> chore (deps) : Bump helm-java version to v0.0.10

- quickstarts/maven/karaf-camel-2-log/pom.xml
Part of https://github.com/eclipse-jkube/jkube/issues/2381
> deps(karaf): bump karaf from 4.4.3 to 4.4.6

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
Fixes #3052
i just update the EnvUtilTest.testLoadTimestampShouldLoadFromFile where removing the throw exception which never throw any exception testLoadTimestampShouldLoadFromFile() 
> Updating `EnvUtilTest.testLoadTimestampShouldLoadFromFile` to remove exception from method signature

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java
1. Replace EnvUtil.stringJoin with String.join
2. Delete EnvUtil.stringJoin and the corresponding unit test
Fixes #3179
> chore(EnvUtil): replace EnvUtil.stringJoin with String.join

- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
> feat: base image doesn't rely on container detection

- quickstarts/maven/micronaut4/pom.xml
Remove duplicate dependency from pom file in Micronaut quickstarts
Fixes #3204 
> Remove duplicate dependency from pom file in Micronaut quickstarts

- pom.xml
chore(deps): Bump version.kubernetes-client from 6.13.0 to 6.13.1
> chore(deps): Bump version.kubernetes-client from 6.13.0 to 6.13.1

- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtil.java
Fixes #3202
- [x ] Bug fix (non-breaking change which fixes an issue)
> fix: replace duration.length() with duration.isEmpty() in GoTimeUtil

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/BuildOptions.java
BuildOptions 'buildArgs.size() > 0' can be replaced with '!buildArgs.isEmpty()'
Fixes #3197 
> BuildOptions - buildArgs.size()>0 replaced with !buildArgs.isEmpty()

- CHANGELOG.md
> chore: add missing changelog entries for #2911 and #2381

- jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherRestartContainerTest.java
Replace asList with asInstanceOf
Fixes #3176
- [ x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
- [x ] New and existing unit tests pass locally with my …
> chore(DockerImageWatcherRestartContainerTest): replace asList with asInstanceOf

- gradle-plugin/kubernetes/pom.xml
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesPlugin.java
- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmInstallTask.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginTest.java
- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmInstallTaskTest.java
- gradle-plugin/openshift/pom.xml
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
- gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmInstallTask.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
- gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmInstallTaskTest.java
- kubernetes-maven-plugin/plugin/pom.xml
- kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmInstallMojo.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/GeneratedPluginDescriptorTest.java
- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmInstallMojoTest.java
- openshift-maven-plugin/plugin/pom.xml
- openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmInstallMojo.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/OpenShiftGeneratedPluginDescriptorTest.java
- openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmInstallMojoTest.java
- https://github.com/eclipse-jkube/jkube/pull/3175
- https://github.com/eclipse-jkube/jkube/pull/3142 to get merged first
Exposes Helm Install Functionality via Gradle Tasks and Maven Plugins.
> feat : Helm Install functionality exposed via Maven Mojos / Gradle Tasks

- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilderTest.java
Fixes  #3201 
- [x ] Chore (non-breaking change which doesn't affect codebase;
> Replaced line.trim().length() == 0 to line().trim().isEmpty() in DockerFileBuilderTest.java 

- jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm.adoc
- jkube-kit/doc/src/main/asciidoc/inc/helm/gradle/_helm_install.adoc
- jkube-kit/doc/src/main/asciidoc/inc/helm/maven/_helm_install.adoc
- quickstarts/kit/helm/README.md
- quickstarts/maven/spring-boot-helm/README.md
> doc : Replace references to the `helm install` CLI command with the new `helm-install` goal/task.

- gradle-plugin/it/pom.xml
Fixes https://github.com/eclipse-jkube/jkube/issues/3243
> fix: systemPropertyVariable for maven-failsafe-plugin

- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
> replaced assertThat().asList() to .asInstanceOf()

- jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ControllerResourceConfigTest.java
Fixes #3240
- [x ] New and existing unit tests pass locally with my changes
> issue-3240:-Replace assertJ Deprecate method

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/JKubeConfigurationTest.java
Fixes https://github.com/eclipse-jkube/jkube/issues/3239
> refactor: change assertion of asList to asInstanceof in JKubeConfigurationTest

- jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/KarafHealthCheckEnricher.java
> Remove unnecessary 'toString()' call in class KarafHealthCheckEnricher

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/CronJobHandlerTest.java
CronJobHandlerTest : Replace AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class))
Fixes #3270
> Replace AssertJ's deprecated asList() DSL method

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
Fixes #3268
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
- [ x] New and existing unit tests …
> issue-3268:ProbeHandlerTest deprecated method asList() replaced

- CHANGELOG.md
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/MicronautUtils.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/generator/MicronautGeneratorTest.java
Fixes #3294
`MicronautUtils.hasMicronautPlugin` should also check for Micronaut4 `micronaut-maven-plugin` . In Micronaut4 `micronaut-maven-plugin`'s groupId has changed from `io.micronaut.build` to `io.micronaut.maven`.
>  fix (jkube-kit-micronaut) : Add micronaut4 maven plugin's groupId to MicronautUtils.hasMicronautPlugin

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/BuildRecreateMode.java
> refactor: remove unnecessary private modifier in enum BuildRecreateMode constructor

- jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java
- jkube-kit/common/pom.xml
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/TestOciServer.java
- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServicePushTest.java
Fixes #3225
Wait for 5 seconds for verifying that created Helm Oci Server instance is accepting connections.
> test : Add wait for oci server to become ready in JibImageBuildServicePushTest

- .jenkins/pipelines/dependencies.Jenkinsfile
- scripts/eclipse-dash-tool.sh
> ci:deps: bump eclipse-dash version to 1.1.1-SNAPSHOT / 1.1.0

- jkube-kit/jkube-kit-micronaut/pom.xml
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/MicronautUtils.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/AbstractMicronautNestedGenerator.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/FatJarGenerator.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/MicronautGenerator.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/MicronautNestedGenerator.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/NativeGenerator.java
- jkube-kit/jkube-kit-micronaut/src/main/resources-filtered/META-INF/jkube/default-images.properties
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsTest.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/generator/MicronautGeneratorIntegrationTest.java
- jkube-kit/parent/pom.xml
~Should be ready once https://github.com/eclipse-jkube/jkube/pull/3295 gets merged~
Related to  #494
MicronautGenerator would detect native build if these conditions are satisfied and prepares image with native artifact:
- the project is configured for native build
- `packaging=native-image` property configured in project (in case of maven projects) **or** 
- `org.graalvm.buildtools.gradle.NativeImagePlugin` plugin present in the project (gradle)
- native artifact is present in build directory
> feat : Support for Micronaut Framework Native Images

- jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java
Split `namesUsedByDockerTests` into separate test methods.
Fixes #3288 
P.S. I could not use a nested test class since `@MethodSource` requires a static method and static methods are not allowed in an inner class in Java 8. Any suggestions are welcome :)
> chore(refactor namesUsedByDockerTests): split namesUsedByDockerTests into separate test methods

- CHANGELOG.md
- jkube-kit/doc/src/main/asciidoc/inc/generator/_micronaut.adoc
> doc : Add documentation for native builds for Micronaut

- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceInstallIT.java
Test case failure fix
Fixes #3265
> issue-3265:-HelmServiceInstallIT test case failure fix

- jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/WebAppGeneratorTest.java
Fixes #3286
Replace deprecated asList() in Web App Generator Test
> Issue #3286: Replace deprecated asList() in Web App Generator Test

- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUninstallIT.java
Related to #2666 
Added `uninstall` method in HelmService
> feat (jkube-kit/helm) : HelmService exposes Helm uninstall functionality

- pom.xml
chore(deps): Bump version.kubernetes-client from 6.13.1 to 6.13.2
> chore(deps): Bump version.kubernetes-client from 6.13.1 to 6.13.2

- pom.xml
> chore (deps) : Bump maven-plugin-plugin to v3.13.1

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricherTest.java
> chore : replacing AssertJ's deprecated asList() DSL method with asInstanceOf(InstanceOfAssertFactories.list(type.class))

- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuth.java
> RegistryAuth Remove unused imports #3024

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
Tidy up setup test method signature.
Fixes #2749
> chore: tidy up setup test method signature

- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmLintMojoTest.java
> HelmLintMojoTest.setUp The declared Exception exception is never thrown #3053

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ThorntailUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/PropertiesUtilTest.java
- jkube-kit/common/src/test/resources/util/properties-util/properties/application.properties
- jkube-kit/common/src/test/resources/util/properties-util/yaml/application.yml
- jkube-kit/jkube-kit-helidon/src/main/java/org/eclipse/jkube/helidon/HelidonUtils.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/MicronautUtils.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/enricher/MicronautHealthCheckEnricher.java
- jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/MicronautGenerator.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsGetMicronautConfigurationTest.java
- jkube-kit/jkube-kit-micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsTest.java
- jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusUtils.java
- jkube-kit/jkube-kit-thorntail-v2/src/main/java/org/eclipse/jkube/thorntail/v2/enricher/ThorntailV2HealthCheckEnricher.java
- jkube-kit/jkube-kit-thorntail-v2/src/test/java/org/eclipse/jkube/thorntail/v2/enricher/ThorntailV2HealthCheckEnricherTest.java
Related to #2880 (extracted into separate PR to keep things small)
Prerequisite refactor before merging #2880
HelidonUtils, MicronautUtils, and QuarkusUtils seem to have similar methods for reading application config as Properties.
+ Move common logic these methods share to a generic method in PropertiesUtil Until.
+ Modify `ThorntailUtil.getThorntailProperties` to have the same method arguments as Helidon, Micronaut, and Quarkus `getConfiguration` methods
> refactor (jkube-kit/common) : Move application config resolution logic to PropertiesUtil

- jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DependencyEnricher.java
Removes the unnecessary 'Arrays.asList()' call in the class DependencyEnricher
Fixes #3340 
> fix: remove Arrays.asList() in DependencyEnricher.java

- jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
> refactor: infer explicit type arguments

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootConfiguration.java
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
- jkube-kit/doc/src/main/asciidoc/inc/enricher/spring-boot-healthcheck/_jkube_healthcheck_spring_boot.adoc
- jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/enricher/SpringBootHealthCheckEnricher.java
- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/enricher/AbstractSpringBootHealthCheckEnricherTestSupport.java
Fixes #1125
SpringBootHealthCheckEnricher now considers WebFlux dependency while adding liveness and readiness probes. If user is depending on webflux dependency and is using `spring.webflux.base-path` property, it would automatically be picked up in probe endpoints
> feat (jkube-kit-spring-boot) : Support WebFlux SpringBoot projects when generating liveness/readiness probes

- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
Fixes [#3336](https://github.com/eclipse-jkube/jkube/issues/3336)
> refactor: ``stream().forEach()`` replaced with ``forEach()`` for better readability

- jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
- jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherRestartContainerTest.java
> fix: Replace deprecated method from Updatable interface

- jkube-kit/jkube-kit-smallrye/src/test/java/org/eclipse/jkube/smallrye/SmallRyeUtilsTest.java
Replace mocks with builder initialization
Fixes #3363 
> Fix(SmallRyeUtilsTest): replace mock with builder in SmallRyeUtilsTest

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java
Fixes #3359 
- [x ] Chore (non-breaking change which doesn't affect codebase;
- [x ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
- [x ] New and existing …
> Chore(issue-3359): replace deprecated test method asList

- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ValidationUtil.java
Fixes #3367
Update the  Code as per the description mentioned in the Issue.
> Updated the Code of ValidationUtil

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ContainerEnvJavaOptionsMergeVisitorTest.java
Fixes #3360
- [x ] Chore (non-breaking change which doesn't affect codebase;
- [x ] I Added [CHANGELOG](../CHANGELOG.md) entry
> Chore(issue-3360): replace deprecated test method asList

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricherTest.java
This PR replaces the deprecated AssertJ `asList()` method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in the `VolumePermissionEnricherTest.java` file.
Fixes #3361
> Replace deprecated asList() with asInstanceOf in VolumePermissionEnricherTest (#3361)

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java
This PR replaces the deprecated AssertJ `asList() `method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in the `ImageStreamServicesTest.java` file.
Fixes #3394
> 3395-fix-assertj-aslist-in-imagestreamservices

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/BuildReferenceDateUtilTest.java
> Changed BuildReferenceDateUtilTest File

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandlerTest.java
In DaemonSetHandlerTest removed unused import 'import static org.mockito.Mockito.mock;'
Fixes #3388
> fix(DaemonSetHandlerTest): Removed Unused import DaemonSetHandlerTest

- jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java
Replace asList() methods with Latest AsertJ method 
Fixes #3428 
> replaced asList methods to AsertJ methods

- jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricher.java
Added class-level @getter annotation in AbstractHealthCheckEnricher.Config
Added 
Fixes #3402 
> Added class-level @getter annotation in AbstractHealthCheckEnricher.Config

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/BuildService.java
> fix(BuildService): Removed Unused import BuildService

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ImagePullPolicyEnricherTest.java
Replaced `asList()` with `InstanceOfAssertFactories.type(Container.class)`
Fixes #3435 
> Replaced AsList() with InstanceOfAssertFactories.type(Type.class) in `ImagePullPolicyEnricherTest`

- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/LocalServiceManagerTest.java
> LocalServiceManagerTest: Replaced AssertJ's deprecated asList() DSL

- jkube-kit/generator/dockerfile-simple/src/test/java/org/eclipse/jkube/generator/dockerfile/simple/SimpleDockerfileUtilTest.java
Replaced `asList()` with `asInstanceOf(InstanceOfAssertFactories.list(Type.class))` in `SimpleDockerFileUtilTest`
Fixes #3441 
> Replaced Deprected  AsList method with AsertJ's method in `SimpleDockerFileUtilTest`

- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/oci/OCIManifestTest.java
Replaced `asList()` with AsertJ's `asInstanceOf(InstanceOfAssertFactories.list(Type.class))`
Fixes #3437 
> Replaced `asList()` Deprected method with AsertJ's method in `OCIManifestTest file`

- jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java
Replaces `asList()` Deprected  Method  with AsertJ's `asInstanceOf(InstanceOfAssertFactories.list(Type.class))` method
Fixes #3440 
> Replaced `asList()` with The `asInstanceOf(InstanceOfAssertFactories.list(Type.class))` AsertJ's method in `JavaExecGeneratorTest`

- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/ChartTest.java
> Changed Deprecated asList() method with asinstanceOf()

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/util/AbstractNativeClientBuilder.java
> [3369]:Anonymous new DnsResolver() can be replaced with lambda

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricherTest.java
Replaced  `asList()` method with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in  `DefaultControllerEnricherTest`
Fixes #3459 
> Replaced  `asList()` method with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in  `DefaultControllerEnricherTest`

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
> BuildService 'nocache.length() == 0' can be replaced with 'nocache.isEmpty()' #3198 Fix

- jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java
Replaced `asList()` method with `.asInstanceOf(InstanceOfAssertFactories.list(Container.class))` in `DockerHealthCheckEnricherTest`
Fixes #3463 
>  #3463 issue : Replaced `asList()` method in `DockerHealthCheckEnricherTest` with `.asInstanceOf(InstanceOfAssertFactories.list(Type.class))`

- kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmUninstallMojoTest.java
> fix(issue #3471): removed unused import

- jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java
To fix failing tests in class SpringBootWatcherIntegrationTest, project path is replaced with the real path.
Fixes #3462
> chore(SpringBootWatcherIntegrationTest): fix SpringBootWatcher integration test by using real path

- jkube-kit/doc/src/main/asciidoc/inc/_introduction.adoc
fix(doc): remove diagram reference from unused doc page
> fix(doc): remove diagram reference from unused doc page

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/GitUtilTest.java
test: GitUtilTest, don't sign commits
> test: GitUtilTest, don't sign commits

- jkube-kit/helm/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
test(helm): remove no longer needed mock-maker-inline
> test(helm): remove no longer needed mock-maker-inline

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/GitEnricherTest.java
test: GitEnricherTest, don't sign commits
> test: GitEnricherTest, don't sign commits

- gradle-plugin/it/src/it/helidon-properties/build.gradle
test(gradle): remove unneeded repositories from helidon-properties IT
> test(gradle): remove unneeded repositories from helidon-properties IT

- jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/util/AbstractNativeClientBuilder.java
Remove unused import to improve code readability (#3469)
Fixes #3469
> fix: remove unused import in AbstractNativeClientBuilder (#3469)

- jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java
Fix #3470 
made changes in import packages
> Modified DebugService.java in jkube submodule

- jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java
Remove unused import
Fixes #3518
> Remove unused import from OpenShiftRegistryAuthHandlerTest.java

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/ProjectEnricherTest.java
- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherBehavioralTest.java
Fixes #3509
Fixes #3520 
Supersedes closes #3510
> Issue 3520 replace `aslist()` project enricher test

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmTask.java
Fixes #3516
Removed an unused import line from the file.
> removed unused import helm - Issue 3516

- CHANGELOG.md
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/LocalServiceManagerTest.java
Fixes #3517 
This PR resolves an issue of have an unused Imports in the Test class. 
> Issue 3517

- gradle-plugin/kubernetes/pom.xml
- gradle-plugin/openshift/pom.xml
- pom.xml
fix:deps: fix gradle tests, bump gradle from 7.6.2 to 7.6.4
> fix:deps: fix gradle tests, bump gradle from 7.6.2 to 7.6.4

- gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmDependencyUpdateTask.java
> issue #3513removed unwanted import 

- jkube-kit/jkube-kit-microprofile/src/test/java/org/eclipse/jkube/microprofile/enricher/AbstractMicroprofileHealthCheckEnricherTest.java
> AbstractMicroprofileHealthCheckEnricherTest : Replace Mockito.mock by creating actual object

- jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java
> test: fix flaky test in MacOS

- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/AbstractPortsExtractor.java
> fix: replace StringBuilder with String (3335)

- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
Fixes #3386 
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix:removed unused import from BaseGenerator (3386)

- jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ServiceProtocol.java
Fixes #3619
- [X ] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
- [X ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
- [X ] My code follows the style guidelines of this project
- [X ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [X ] I have performed a self-review of my code
- [X ] I Added [CHANGELOG](../CHANGELOG.md) entry
- [X ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
- [X ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
- [X ] I have added tests that prove my fix is effective or …
> fix: solved issue #3619 ServiceProtocol: Unnecessary semicolon ';'

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
> deps: bump jkube-images from 0.0.24 to 0.0.25

- quickstarts/gradle/micronaut-customized-image/build.gradle
- quickstarts/gradle/micronaut-customized-image/gradle.properties
- quickstarts/gradle/micronaut/gradle.properties
Fixes #2774 
•	Updated Micronaut version to ensure compatibility with the latest features and fixes.
•	Added the OpenShift plugin (org.eclipse.jkube.openshift version 1.17.0) 
•	Added the RxJava2 dependency (io.micronaut.rxjava2:micronaut-rxjava2) 
> Update Micronaut version, add OpenShift plugin, and RxJava2 dependency

- quickstarts/gradle/micronaut-customized-image/build.gradle
> doc(quickstarts): gradle micronaut-customized-image invalid config

- jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/PodExecutor.java
As this line is part of try catch statment. a semicolon is not needed.
I couldn't sign up as requested in the contribution guide in https://accounts.eclipse.org signing up give error, "Your GitHub username is invalid"
Fixes #3617
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
- [X ] My code follows the style guidelines of this project
- [ X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [ X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ X] I have performed a self-review of my code
- [ X] No new bugs, code smells, etc. in …
> Removed semicolon on line 74

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
> fix: skip executable libs when searching Spring Boot native binary

- jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
> Removed extra semicolon

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ConfigsTest.java
Removed unnecessary semicolon
Fixes https://github.com/eclipse-jkube/jkube/issues/3612
> #3612 remove unnecessary semicolon in config test

- quickstarts/maven/quarkus/pom.xml
> doc(quarkus): update Quarkus example to latest version 3.18.2

- CHANGELOG.md
- jkube-kit/parent/pom.xml
- jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
> deps: bump jkube-images from 0.0.25 to 0.0.26

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesConfigViewTaskTest.java
https://github.com/eclipse-jkube/jkube/pull/3626
> fix: revert sonarqube fix

- CHANGELOG.md
- jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/config/property/PropertyConfigResolver.java
- jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/DefaultGeneratorManager.java
- jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/DefaultGeneratorManagerTest.java
> fix: config properties resolved for generated images

- gradle-plugin/it/src/it/metadata/build.gradle
* Removed unnecessary semicolons in metadata/build.gradle (jkube/gradle-plugin).
Fixes #3608
> refactor: remove unnecessary semicolons

- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ConfigsTest.java
Fixes #3659 
Replaces deprecated `RandomStringUtils.randomAlphabetic` method with `RandomStringUtils.secureStrong.nextAlphabetic`.
> fix(#3659): replace deprecated RandomStringUtils.randomAlphabetic method

- .github/workflows/generate-maven-sbom.yml
As previously discussed, this PR aims to bootstrap the EF Security Team initiative of implementing automated SBOM generation for projects and uploading them to our DependencyTrack instance, with the goal of enhancing software supply chain security.
We wanted this to seamlessly integrate with your existing release processes, so we implemented 1 generation workflow meant to generate an SBOM for the entire jkube product.
Currently the workflow is triggered by either pushes to the master branch that modify the dependency file (pom.xml) or by pushing new tags. A maven cyclonedx plugin is used to generate the SBOM, which is then uploaded as an artifact. The "store-sbom-data" reusable workflow stores additional metadata about the project and upon completion, the self service system downloads the …
> Add SBOM generation and upload to DependencyTrack workflow

- gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTaskTest.java
> Simplified statement lambda to expression lambda

- jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherTest.java
> test: update assertions in DefaultServiceEnricherTest for improved clarity

- jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptor.java
> fix: handle empty access_token sent by harbor

- jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmConfigTest.java
Removed unnecessary semicolon
Fixes #3614
> Fixes #3614: Removed unnecessary semicolon

- SECURITY.md
chore(security): update security policy to latest Eclipse Foundation version
/cc @iliescuioana
> chore(security): update security policy to latest Eclipse Foundation version

- .jenkins/pipelines/sonar.Jenkinsfile
- pom.xml
> chore(ci): sonar scan with token

- CHANGELOG.md
- jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/XMLUtil.java
- jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/XMLUtilTest.java
> fix(common): remove unneeded XMLUtil.createNewDocument method

- USING-SNAPSHOT-ARTIFACTS.md
> chore(doc): update snapshot repository URLs
