.github/workflows/integration-tests.yml

Integration tests run in a workflow executed in the scope of this repository.
Tests are cloned from master branch of https://github.com/jshiftio/jkube-integration-tests <- This repo should be moved in the future.
Relates to:
https://github.com/jkubeio/jkube/issues/21

Integration tests from remote repository run in JKube repository workflow

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/wait/TcpPortChecker.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java
jkube-kit/jkube-kit-spring-boot/src/main/resources/META-INF/jkube/watcher-default
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/plexus/components.xml
openshift-maven-plugin/plugin/src/main/resources/META-INF/plexus/components.xml
quickstarts/maven/spring-boot/pom.xml
quickstarts/maven/vertx/pom.xml

* Fix following bugs reported by Sonar:
* https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AW3z0M30L3SSO-VMZS3t&open=AW3z0M30L3SSO-VMZS3t
* https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AW3z0NajL3SSO-VMZTH1&open=AW3z0NajL3SSO-VMZTH1
* https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AW3z0NajL3SSO-VMZTH0&open=AW3z0NajL3SSO-VMZTH0
* https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AW3z0Ng5L3SSO-VMZTKV&open=AW3z0Ng5L3SSO-VMZTKV
* Fix typo in watcher-default for Spring Boot
* Fix Plexus container environment dependencies for `DockerAssemblyManager`

Close input streams + other fixes

---

jkube-kit/build/maven/src/main/java/org/eclipse/jkube/kit/build/maven/ResourceMojoUtil.java
jkube-kit/build/maven/src/test/java/org/eclipse/jkube/kit/build/maven/ResourceMojoUtilTest.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/DockerBuildService.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ProjectClassLoaders.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ResourceUtil.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/maven/enricher/api/EnricherContext.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/maven/enricher/api/MavenEnricherContext.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/maven/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/enricher/AbstractSpringBootHealthCheckEnricherTestSupport.java
jkube-kit/jkube-kit-thorntail-v2/src/test/java/org/eclipse/jkube/thorntail/v2/enricher/ThorntailV2HealthCheckEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_integrations.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/index.adoc
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
openshift-maven-plugin/doc/src/main/asciidoc/inc/_integrations.adoc
openshift-maven-plugin/doc/src/main/asciidoc/index.adoc
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
quickstarts/maven/spring-boot-dekorate/pom.xml
quickstarts/maven/spring-boot-dekorate/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/dekorate/SpringDekorateApplication.java
quickstarts/maven/spring-boot-dekorate/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/dekorate/SpringDekorateResource.java
quickstarts/maven/spring-boot-dekorate/src/test/java/org/eclipse/jkube/maven/sample/spring/boot/dekorate/SpringDekorateResourceTest.java

Relates to:
- fabric8io/fabric8-maven-plugin#1767
- fabric8io/fabric8-maven-plugin#1483

feat: Configurable Dekorate integration

---

jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/main/resources/assemblies/webapp.xml

There's a typo in webapp generator.
I'm currently working on Integration tests for WebApp and stumbled upon this one.

fix: Generated webapp war has wrong name

---

jkube-kit/jkube-kit-thorntail-v2/src/main/java/org/eclipse/jkube/thorntail/v2/generator/ThorntailV2Generator.java
quickstarts/maven/thorntail/pom.xml

Relates to: https://github.com/fabric8io/fabric8-maven-plugin/issues/1363
Signed-off-by: Marc Nuri <marc@marcnuri.com>

fix: Disable Jolokia, missing PR port from FMP

---

jkube-kit/build/maven/src/main/java/org/eclipse/jkube/kit/build/maven/config/MavenBuildConfiguration.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java

After the initial Maven decoupling commits, a bug has appeared specific to Plexus injection of generic typed bean values.
This fix allows to inject `<configuration><images><image><build><assembly> ` entries again.

fix: Problem with plexus detecting target value type for bean injection

---

.github/workflows/integration-tests.yml

Seems VM machine get hogged when running OpenShift tests for Quarkus. This
will lower the amount of resources by running less tests at a time.

ci: Lowered number of parallel threads for OpenShift + disabled fail-fast

---

CHANGELOG.md
jkube-kit/common-maven/pom.xml
jkube-kit/config/resource/pom.xml

I think this would finally make Jkube-kit completely independent from maven.
Fix #30 
```
~/work/repos/jkube/jkube-kit : $ git grep -c "org.apache.maven" | grep -v "common-maven"
common/src/main/java/org/eclipse/jkube/kit/common/util/CommandLine.java:1
enricher/specific/src/main/java/org/eclipse/jkube/maven/enricher/specific/WebAppHealthCheckEnricher.java:1
enricher/specific/src/test/java/org/eclipse/jkube/maven/enricher/specific/WebAppHealthCeckEnricherTest.java:1
generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java:1
generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java:1
jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/Constants.java:1
parent/pom.xml:24
```
The remaining references are just some …

Chore: Remove unused maven dependency from Jkube-Kit config/

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ExposeEnricher.java
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/jkube-kit-openliberty/pom.xml
jkube-kit/jkube-kit-openliberty/src/main/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGenerator.java
jkube-kit/jkube-kit-openliberty/src/main/resources/META-INF/jkube/generator-default
jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGeneratorTest.java
jkube-kit/pom.xml
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_generator.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_openliberty.adoc
kubernetes-maven-plugin/plugin/pom.xml
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
openshift-maven-plugin/doc/src/main/asciidoc/inc/_generator.adoc
openshift-maven-plugin/doc/src/main/asciidoc/inc/generator/_openliberty.adoc
openshift-maven-plugin/plugin/pom.xml
openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
quickstarts/maven/openliberty/pom.xml
quickstarts/maven/openliberty/src/main/java/org/eclipse/jkube/maven/sample/openliberty/HelloWorldEndpoint.java
quickstarts/maven/openliberty/src/main/java/org/eclipse/jkube/maven/sample/openliberty/RestApplication.java
quickstarts/maven/openliberty/src/main/liberty/config/server.xml
quickstarts/maven/openliberty/src/test/java/org/eclipse/jkube/itests/SampleIT.java
quickstarts/maven/openliberty/src/test/resources/arquillian.xml

+ Add a generator for Open Liberty that extends the java-exec generator. It defaults webPort to the Liberty default port (9080) and adds an environment variable for use by S2I if it detects a Liberty runnable jar.
+ Add Liberty's default web ports (9080, 9443) to the ExposeEnricher so that routes get generated.
I would add the sample once #33 gets merged

Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1711

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java

fix: filtered is for variable interpolation/substitution, not for exclusion

---

CHANGELOG.md
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/maven/enricher/api/util/KubernetesResourceUtil.java

Ported PR from FMP https://github.com/fabric8io/fabric8-maven-plugin/pull/1794

Fix ImageChange triggers not being set in DeploymentConfig when resource fragments are used.

---

.github/workflows/integration-tests.yml
CHANGELOG.md
jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ThorntailUtil.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/YamlUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ThorntailUtilTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/YamlUtilTest.java
jkube-kit/common/src/test/resources/util/yaml-list.yml

Fix vulnerability described in #122 (https://bugs.eclipse.org/bugs/show_bug.cgi?id=561261)
Refactor YamlUtil to fix multiple document Yaml file resource splitting.

fix: CWE 502 Deserialization of Untrusted Data + fix yaml list resource split

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
jkube-kit/common/src/test/resources/util/fragments/deployment.yml
jkube-kit/common/src/test/resources/util/fragments/service.yml
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/OpenshiftBuildConfig.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java
jkube-kit/resource/service/src/main/java/org/eclipse/jkube/kit/config/service/BuildService.java
jkube-kit/resource/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceTest.java

Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1772

Provide support for setting BuildConfig memory/CPU requests and limits

---

.github/workflows/e2e-tests.yml

- Changed file name and title to reflect current status of test suite
- ~Set k8s max version to 1.18.0~
- Run test on push  **only** when branch is master

chore: Update test suite to current status (before demo)

---

openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftPushMojo.java

As discussed on [Gitter channel](https://gitter.im/eclipse/jkube) yesterday. I'm restoring Push goal in case of Openshift maven plugin. Right now, it doesn't do anything; it just prints a warning and skips execution. But we might add some other logic in case of other build modes (JIB, Kaniko, buildah) in future.

Restore PushMojo in Openshift Maven Plugin

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftBuildMojo.java
quickstarts/maven/webapp/pom.xml

Fix #138
Remove check related to checking docker access in case of OpenShift builds. I also faced one minor issue related to https://github.com/eclipse/jkube/pull/126

Fix #138: OpenShift build requires connection to dockerd

---

.github/workflows/e2e-tests.yml

Closes: #131 
There's no easy solution to add complete e2e tests for Windows Server 2019 (ephemeral k8s cluster).
Hyper-V is not enabled in GH Actions and enabling requires a VM restart which makes the GH Runner loose the connection to the VM.
Minikube with Virtualbox is not an option either, as it requires vt-x to be enabled (which isn't).
Trying to enable Linux container support doesn't work well and relies on experimental features (lcow project has been archived too), so running alternatives to Minikube (k3s, MicroK8s, etc.) is also impossible.
Current PR will create a Windows Container compatible Docker image and test resource generation.
Tested Eclipse JKube Features:
- build (k8s)
- push (k8s)
- resource (k8s & oc)
- helm (k8s & oc)
Blocked by: jkubeio/jkube-integration-tests#31

test: Windows IT

---

kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_controller.adoc

Added documentation to cover the defaults for the jkube-controller enricher.
I followed the jkube-service as an example but I do see some repetition in this line: 
> This can be either directly configured with fragments or with the XML configuration
In the future, it may be better to have a section that describes the general behavior of configuration options and the precedence of operations.
I supplied links to the K8s controller documentation but I could not see how to link to the list on controllers which I'm not happy about. 
https://stackoverflow.com/questions/60918319/

added documentation for jkube-controller enricher

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceTest.java
jkube-kit/parent/pom.xml

Signed-off-by: anandrkskd <anandrkskd@gmail.com>
This PR updates k8s-client to latest version i.e 4.9.1
CQs:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22096 :heavy_check_mark: 
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22095 :heavy_check_mark:

Kubernetes client updated with 4.9.1 version

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/JKubeAssemblyConfigurationUtils.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/core/assembly/JKubeAssemblyConfigurationUtilsTest.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/AssemblyConfiguration.java
quickstarts/maven/docker-file-provided/Dockerfile
quickstarts/maven/docker-file-provided/README.md
quickstarts/maven/docker-file-provided/pom.xml

Whenever an Assembly configuration such as:
```xml
<images>
<image>
<name>jkube/context-and-assembly</name>
<build>
<contextDir>${project.basedir}</contextDir>
<assembly>
<name>target</name>
</assembly>
</build>
</image>
</images>
```
The built Assembly object in `DockerAssemblyManager` should not be null as all of the required values should be inferred from the `BuildConfiguration`
Relates to: #149

fix: Assembly is never null

---

CHANGELOG.md
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/OpenShiftBuildStrategy.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/AppServerDetector.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/AppServerHandler.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/AbstractAppServerHandler.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/JettyAppSeverHandler.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/TomcatAppSeverHandler.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/AppServerAutoDetectionTest.java
jkube-kit/parent/pom.xml
quickstarts/maven/webapp-wildfly/pom.xml

- Updated jboss-wildfly image version
- Fixed Quickstart configuration
- Added required permissions to standalone directory so that any "randomized" user can start the app server

fix: Wildfly example works in OpenShift with s2i binary

---

CHANGELOG.md
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/RuntimeMode.java
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java

- Runtime mode was being computed from System properties that
were never set in the first place (this is specific to ResourceMojo)
- TODO: Refactor BaseEnricher so it behaves like BaseGenerator
(not critical because it works as the properties are there for
enrichers)

fix: BaseGenerator retrieves runtime mode from context

---

CHANGELOG.md
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/FromSelector.java
jkube-kit/generator/webapp/pom.xml
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/AppServerHandler.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java
jkube-kit/generator/webapp/src/main/resources-filtered/META-INF/jkube/default-images.properties
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandlerTest.java
jkube-kit/parent/pom.xml
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_webapp.adoc
quickstarts/maven/webapp-wildfly/pom.xml

3 build modes:
- Docker (Kubernetes) `mvn k8s:build`
- OpenShift-Docker (S2I Binary) `mvn oc:build -Djkube.build.strategy=docker`
- OpenShift-S2I (S2I Source) `mvn oc:build`

feat: Webapp-Wildfly supports S2I source builds too

---

CHANGELOG.md
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/jkube-kit-openliberty/src/main/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGenerator.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java
jkube-kit/parent/pom.xml
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_java_exec.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-watch.adoc
quickstarts/maven/spring-boot-watch/README.md
quickstarts/maven/spring-boot-watch/pom.xml
quickstarts/maven/spring-boot-watch/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/Application.java
quickstarts/maven/spring-boot-watch/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/HelloController.java
quickstarts/maven/spring-boot-watch/src/main/resources/application.properties
quickstarts/maven/spring-boot/README.md
quickstarts/maven/spring-boot/pom.xml
quickstarts/maven/spring-boot/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/HelloController.java

Closes spike PoC in #203 where standard base images are used.
Replace base images used in `JavaExecGenerator` (#183) for partially customized images based on [JBoss CEKit modules](https://github.com/jboss-openshift/cct_module).
Images are maintained by us in https://github.com/jkubeio/jkube-images and deployed to our public [Quay.io repositories](https://quay.io/organization/jkube), in this case https://quay.io/repository/jkube/jkube-java-binary-s2i.
These images shouldn't be used outside of Eclipse JKube as we don't want to provide extra-support or maintenance other than that related to the images working with JKube.

feat: JavaExecGenerator uses jkube/jkube-java-binary-s2i for Docker and S2I builds

---

CHANGELOG.md
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftBuildMojo.java
quickstarts/maven/spring-boot/pom.xml

Reported on https://gitter.im/eclipse/jkube?at=5ecc797c2280c80cbfca76a5

fix: pom.xml configured runtime mode `<mode>` is considered instead of `<configuredRuntimeMode>`

---

CHANGELOG.md
jkube-kit/generator/wildfly-swarm/src/main/java/org/eclipse/jkube/generator/wildflyswarm/WildFlySwarmGenerator.java

Integration tests work due to a workaround introduced in the config while implementing them:
https://github.com/jkubeio/jkube-integration-tests/blob/17b80a4d5ec2b5c7343b512f92edefec6dba8317/projects-to-be-tested/wildflyswarm/rest/pom.xml#L85

fix: added required configurations for WildFlySwarmGenerator to work

---

CHANGELOG.md
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/OpenShiftAnnotations.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/GitEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/GitEnricherTest.java

Fix #173: Use OpenShift compliant git/vcs annotations

---

CHANGELOG.md
jkube-kit/generator/api/pom.xml
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/FromSelector.java
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
jkube-kit/generator/api/src/main/resources-filtered/META-INF/jkube/default-images.properties
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/FromSelectorTest.java
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java
jkube-kit/generator/api/src/test/resources/META-INF/jkube/default-images.properties
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorMainClassDeterminationTest.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaRunGeneratorTest.java
jkube-kit/generator/karaf/pom.xml
jkube-kit/generator/karaf/src/main/resources-filtered/META-INF/jkube/default-images.properties
jkube-kit/generator/karaf/src/test/java/org/eclipse/jkube/generator/karaf/KarafGeneratorTest.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java
jkube-kit/parent/pom.xml
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_java_exec.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_karaf.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_webapp.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_wildfly_swarm.adoc
quickstarts/maven/vertx/README.md

fix: Remove Red Hat specific image support

---

CHANGELOG.md
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/BaseEnricher.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultNamespaceEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ExposeEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/IngressEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java
jkube-kit/profile/src/test/resources/jkube/config/profiles-lookup-dir/profiles.yaml
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_faq.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-apply.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
openshift-maven-plugin/it/src/it/simple-with-route-flag-true/expected/openshift.yml
pom.xml
quickstarts/maven/spring-boot/README.md
quickstarts/maven/spring-boot/pom.xml

Fix #184 
Ported PR https://github.com/fabric8io/fabric8-maven-plugin/pull/1730

Fix #184: IngressEnricher seems to be broken

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/KitLogger.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Slf4jKitLogger.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/Slf4jKitLoggerTest.java

Provided Slf4j delegate KitLogger implementation

feat: Provided Slf4j delegate KitLogger implementation

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/AssemblyFiles.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/ArchiveService.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtils.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtils.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtilsTest.java
quickstarts/maven/webapp/pom.xml

Watch goal was not working with projects with more complex Assemblies that involved renaming files, etc.
This fix allows watch to work again.
You can test it on:
- https://github.com/eclipse/jkube/tree/master/quickstarts/maven/webapp
- https://github.com/eclipse/jkube/tree/master/quickstarts/maven/thorntail
- ...

fix: Watch works with complex assemblies using AssemblyFile

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/OpenshiftHelper.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/access/ClusterAccess.java
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubTest.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java

Removed @Deprecated fields from ClusterAccess

fix: Removed @Deprecated fields from ClusterAccess

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/service/MigrateService.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/LazyBuilder.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/XMLUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/service/MigrateServiceTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/LazyBuilderTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/XMLUtilTest.java
jkube-kit/common/src/test/resources/service/migrate/test-project-profile/expected-pom.xml
jkube-kit/common/src/test/resources/service/migrate/test-project-profile/fabric8-pom.xml
jkube-kit/common/src/test/resources/service/migrate/test-project/expected-pom.xml
jkube-kit/common/src/test/resources/service/migrate/test-project/fabric8-pom.xml
jkube-kit/common/src/test/resources/util/xml-util.xml
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/util/MigrateMojo.java
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/util/OpenShiftMigrateMojo.java

- pluginManagement pom.xml entries are now considered (both in profile and build)
- Granular control for fmp- f8- prefix replacements (only where applicable)
- Improved MigrateService IT suite, validate complete expected pom.xml
- "Mergeable" fragment directory (idempotent migrate goal)
+ Rafactored LazyBuilder
Relates to: #195

fix: Improved MigrateMojo

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/AssemblyConfigurationUtils.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/core/assembly/AssemblyConfigurationUtilsTest.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilder.java

DockerFileBuilder only supports *nix paths (Dockerfile Linux only)
- Fixed provided invalid default configs (Dockerfile mode, etc.)
Fixes: #261

fix: DockerFileBuilder only supports *nix paths (Dockerfile Linux only)

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/AssemblyConfigurationUtils.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/AssemblyFiles.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/JKubeBuildTarArchiver.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/ArchiveService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/WatchMode.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManagerTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/AssemblyFileEntry.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtils.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtilsProcessAssemblyFileSetTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtilsTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/BaseWatcher.java
jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherContext.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/watcher/WatcherManager.java
quickstarts/maven/quarkus/pom.xml

Watch uses same logic as build to monitor changed assembly files (fixes #238 )
- One new code smell reported for TODO related to #94 for AssemblyFile permission/fileMode

fix: Watch uses same logic as build to monitor changed assembly files

---

CHANGELOG.md
jkube-kit/parent/pom.xml

fix #245: Debug goals work on webapp (Tomcat & Jetty)
Related commits:
- https://github.com/jkubeio/jkube-images/commit/6d6674cadab70101d1ecf43065c967e513d18779
- https://github.com/jkubeio/jkube-images/commit/541788d3e4de757d0b094e8d4b607bc74f68b213

fix: Debug goals work on webapp (Tomcat & Jetty)

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/PatchServiceTest.java

Signed-off-by: Marcos Trejo <marcos.trejo@gmail.com>
Generating a patch for Route, in a similar fashion as the plugin already did for Service and other resources. This fixes https://github.com/eclipse/jkube/issues/267

Fix #267: openshift-maven-plugin does not update Routes

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PodLogService.java

We no longer have start and stop goals. Replacing those with deploy
and undeploy

Fix warning in PodLogService when no running pod is found

---

quickstarts/maven/quarkus/README.md
quickstarts/maven/quarkus/pom.xml

Signed-off-by: Marc Nuri <marc@marcnuri.com>
Maven Quarkus quickstart supports JIB builds for native image

fix: Maven Quarkus quickstart supports JIB builds for native image

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmMojo.java
quickstarts/maven/spring-boot-helm/README.md
quickstarts/maven/spring-boot-helm/pom.xml

Fix: Template resolution and helm work in OpenShift-Maven-Plugin

Fix: Template resolution and helm work in OpenShift-Maven-Plugin

---

quickstarts/maven/spring-boot-helm/README.md
quickstarts/maven/xml-config/pom.xml

fix: xml-config quickstart provides configmap configuration in pom.xml

fix: xml-config quickstart provides configmap configuration in pom.xml

---

quickstarts/maven/spring-boot-dekorate/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/dekorate/SpringDekorateApplication.java

fix: Dekorate quick-start works in a deterministic way
If configuration for all annotation types is not provided, the resource manifests get generated
in a non-deterministic fashion since generators which provide common configurations (such as group or version)
will overwrite configuration in the Session for other generators.
I previously thought that setting some annotations (such as @DockerBuild) with an enabled = false field
would fix this, but it didn't, handlers/configurators/generators for those annotations are still being used.

fix: Dekorate quick-start works in a deterministic way

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
quickstarts/maven/webapp-jetty/pom.xml
quickstarts/maven/yaml-only/pom.xml

Somehow Openshift detected statement was showing without
any color
`getLog()` seems to be using logger from `AbstractMojo` class.
Also, updated some quickstarts with SNAPSHOT version
Before:
With this Patch:

Fix Logging in ApplyMojo during OpenShift detection

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/MavenProjectEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_project_label.adoc

Adding a new parameter for the `ProjectLabelEnricher`, called `customAppName` to make it possible to deploy the same application under the same namespace, but in different versions.
This PR closes #273 .

Fix #273: Enabling custom naming of the app label in deployment descriptor

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/JKubeProjectUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/JKubeProjectUtilTest.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/EnricherContext.java
jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java
jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxGenerator.java
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxGeneratorTest.java

fix: Vert.x generator and enricher to be applicable when `io.vertx` dependencies present
Previously projects containing a `<dependency><groupId>io.vertx</groupId></dependency>` were not being picked up by Vert.x generator and enricher since the behavior of `JKubeProjectUtil.hasDependency(getProject(), Constants.VERTX_GROUPID, null)` was not the one expected before Maven decoupling happened.

fix: Vert.x generator and enricher applicable when `io.vertx` dependencies present

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftBuildMojo.java

fix #334: Build strategy picked up from XML configuration and properties

fix: Build strategy picked up from XML configuration and properties

---

CHANGELOG.md
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc

Signed-off-by: Søren Jacobsen <sej@aety.io>

Fix doc to align with property jkube.openshift.imageChangeTriggers

---

jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java

fix: **push** to insecure registries JIB

fix: push to insecure registries JIB

---

.github/dependabot.yml
.github/workflows/license.yml
jkube-kit/jkube-kit-wildfly-jar/pom.xml
jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricher.java
jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGenerator.java
jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java
jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java
quickstarts/maven/external-resources/src/main/jkube/configmap.yml
quickstarts/maven/spring-boot-camel-complete/src/main/resources/application.properties
quickstarts/maven/wildfly-jar/pom.xml
quickstarts/maven/wildfly-jar/src/main/java/org/eclipse/jkube/maven/sample/wildflyjar/HelloWorldEndpoint.java
quickstarts/maven/wildfly-jar/src/main/java/org/eclipse/jkube/maven/sample/wildflyjar/RestApplication.java

License check was doing `mvn license:format` instead of
`mvn license:check`

Fix License Check Github Workflow

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/AutoTLSEnricher.java
jkube-kit/enricher/generic/src/main/resources/META-INF/jkube/enricher-default
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/AutoTLSEnricherTest.java

Signed-off-by: Søren Jacobsen <sej@aety.io>
Fix for adding annotation + volume config in AutoTLSEnricher
Fixes https://github.com/eclipse/jkube/issues/351

Fix AutoTLSEnricher - add annotation + volume config to resource

---

jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManager.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/Assembly.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtils.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtilsTest.java

Fix #350 
* AssemblyManager
* Makes use of existing assembly configuration and adds to it if it exists
* AssemblyManagerTest
* Tests for creating tar archive with docker file AND additional assembly
* AssemblyFileUtils
* Checks for and handles no output directory specified in inline assemblies

Fix #350: Stops docker configuration overwriting assembly configuration

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManager.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtilsTest.java
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java
jkube-kit/jkube-kit-openliberty/src/main/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGenerator.java
jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGeneratorTest.java
pom.xml

Fix #340: Exclude the main artifact from Docker build when Fat Jar is detected (JavaExecGenerator)

Fix #340: Exclude the main artifact from Docker build when Fat Jar is detected (JavaExecGenerator)

---

CHANGELOG.md
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java

Fix #341 
Earlier due to sidecar refactor, JKube wasn't able to find out
default application container's name for which we need to add
ImageChange triggers during openshift S2I build when we were
providing resource fragments in which container name was absent.

Fix #341 : ImageChangeTrigger now gets applied when resource fragments used

---

CHANGELOG.md
jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/PrometheusEnricher.java
jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/PrometheusEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_prometheus.adoc

fix #326: Add default `/metrics` path for `prometheus.io/path` annotation

fix: Add default `/metrics` path for `prometheus.io/path` annotation

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java

Fix #339: Https should be considered default while converting tcp urls

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RunService.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/develop/_jkube-watch.adoc

fix #297: Added missing documentation for WatchMojo configuration parameters

fix: Added missing documentation for WatchMojo configuration parameters

---

CHANGELOG.md
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/WebAppGeneratorTest.java

fix #371: WebAppGenerator path configuration is no longer ignored

fix: WebAppGenerator path configuration is no longer ignored

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyConfigurationUtils.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyConfigurationUtilsTest.java

Fix #381: Remove root as default user in AssemblyConfigurationUtils#getAssemblyConfigurationOrCreateDefault

---

CHANGELOG.md
jkube-kit/parent/pom.xml

Fix #358: Prometheus is enabled by default, opt-out via AB_PROMETHEUS_OFF required to disable (like in FMP)
The real fix has been done in https://github.com/jkubeio/jkube-images/pull/2, this PR only updates the jkube-images version. 

fix: Update jkube-images to 0.0.8 - Prometheus is enabled by default

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ContainerEnvJavaOptionsMergeEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ImageEnricher.java
jkube-kit/enricher/generic/src/main/resources/META-INF/jkube/enricher-default
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ContainerEnvJavaOptionsMergeTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ContainerEnvJavaOptionsMergeVisitorTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_container_env_java_options.adoc
kubernetes-maven-plugin/it/src/it/custom-environment/pom.xml
kubernetes-maven-plugin/it/src/it/java-options-env-merge/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/java-options-env-merge/invoker.properties
kubernetes-maven-plugin/it/src/it/java-options-env-merge/pom.xml
kubernetes-maven-plugin/it/src/it/java-options-env-merge/verify.groovy
kubernetes-maven-plugin/it/src/it/remote-resources/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/vertx/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/vertx/pom.xml
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/kind-filename-type-mapping-default.adoc
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
openshift-maven-plugin/it/src/it/custom-environment/pom.xml
openshift-maven-plugin/it/src/it/remote-resources/expected/openshift.yml
openshift-maven-plugin/it/src/it/vertx/expected/openshift.yml
openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml

fix #384: Enricher defined Container env vars get merged with vars defined in Image Build Configuration

fix: Enricher defined Container env vars get merged with vars defined in Image Build Configuration

---

CHANGELOG.md
jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGenerator.java
jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/generator/_wildfly_jar.adoc
quickstarts/maven/wildfly-jar/pom.xml

Signed-off-by: JF Denise <jdenise@redhat.com>
The quickstart evolution is tracked by https://github.com/eclipse/jkube/issues/399
* Support for slim server in WildFly bootable JAR.
* In addition the preferIPV4 is now added by default.
* Upgraded WildFly and wildfly-jar plugin versions in quickstart.

Fix for issue #385, WildFly Bootable JAR - Add native support for slim Bootable JAR

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc

Incremental PR for #375 (@sejacobsen) (Closes #375 + #356 )
Added annotations so Router can be configured w/ TLS termination from the pom. Updated docs accordingly.

Fix #356: Add further support for router config (tls termination and - Incremental to #375

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidatorTest.java
jkube-kit/common/src/test/resources/util/validator/invalid-deployment.yml
jkube-kit/common/src/test/resources/util/validator/valid-service.yml

Fix #415: Fixed resource validation for new json-schema-validator version

fix: resource validation works with new json-schema-validator version

---

CHANGELOG.md
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java

Fix #382 & #383 
RouteEnricher now considers merging opinionated route with route provided in resource fragments(if any). Earlier RouteEnricher used to skip a generation of the opinionated route if it found a route corresponding to target Service inside KubernetesListBuilder

Fix #382: Add support for merging fragment Route spec with default generated Route

---

jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java

Fix bug in merge fragment with opinionated route regarding array indexing, 0th index wasn't considered while doing the comparison

RouteEnricher doesn't merge route fragment when it's the only fragment

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/JKubeBuildTarArchiver.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerTest.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ContainerEnvJavaOptionsMergeEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ContainerEnvJavaOptionsMergeTest.java

Fix #386 
Updated code in JKubeBuildTarArchiver to allow copying files when already existing.

Fix #386: final fat jar is not updated in docker build directory

---

CHANGELOG.md
jkube-kit/build/service/docker/pom.xml
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/ApacheHttpClientDelegate.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/ApacheHttpClientDelegateTest.java

fix: Valid content type for REST docker API requests with body
Relates to: #66 (https://github.com/eclipse/jkube/issues/66#issuecomment-712732571)

fix: Valid content type for REST docker API requests with body

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherAddMissingPartsTest.java

fix #448 : Service.spec.type added from config if existing Service fragment doesn't specify it

fix: Service.spec.type added from config if existing Service fragment doesn't specify it

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/HcChunkedResponseHandlerWrapper.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/HcChunkedResponseHandlerWrapperTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildService.java

fix: Docker push works with Podman REST API

fix: Docker push works with Podman REST API

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/watch/WatchContext.java
jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MavenUtil.java
jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java

fix: Removed misleading watch-postGoal warning + fixed rolling update in DockerImageWatcher

fix: Removed misleading watch-postGoal warning + fixed rolling update in DockerImageWatcher

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
jkube-kit/common/src/test/resources/crontab-cr.yml
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java
jkube-kit/config/service/src/test/resources/gateway-cr.yml
jkube-kit/config/service/src/test/resources/virtualservice-cr.yml
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java

While testing #427 , I found out that ApplyMojo is not able to handle the case when there
is more than one CustomResource present with same ApiGroup and ApiVersion but different Kinds.
We should also consider Kind while comparing CustomResourceDefinitionContexts, not just
groups.

Fix CustomResource apply logic, should consider Kind too while checking CustomResourceDefinitionContext

---

CHANGELOG.md
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/ApacheHttpClientDelegateTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherAddMissingPartsTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java
jkube-kit/parent/pom.xml

chore: Upgrade assertj-core to 3.18.0

chore: Upgrade assertj-core to 3.18.0

---

CHANGELOG.md
quickstarts/kit/custom-istio-enricher/README.md
quickstarts/kit/custom-istio-enricher/app/pom.xml
quickstarts/kit/custom-istio-enricher/app/src/main/java/org/eclipse/jkube/quickstarts/kit/enricher/app/Application.java
quickstarts/kit/custom-istio-enricher/app/src/main/java/org/eclipse/jkube/quickstarts/kit/enricher/app/HelloController.java
quickstarts/kit/custom-istio-enricher/istio-enricher/pom.xml
quickstarts/kit/custom-istio-enricher/istio-enricher/src/main/java/org/eclipse/jkube/quickstart/kit/enricher/istio/IstioEnricher.java
quickstarts/kit/custom-istio-enricher/istio-enricher/src/main/resources/META-INF/jkube/enricher
quickstarts/kit/custom-istio-enricher/pom.xml

Added a Quickstart for JKube Kit Enricher API on how you can extend Eclipse JKube Kit and add an enricher for your own Custom Use case. This quickstart contains a simple Spring Boot application which uses a custom made enricher to generate dummy Istio Gateway.
This is based on the discussion in #427 . Although the user was able to get it working with FMP, I thought we should have this sample in Eclipse JKube too.

Added a Quickstart for Implementing your own Custom Enricher

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java
jkube-kit/build/api/src/test/resources/docker/Dockerfile_expose_ports
quickstarts/maven/docker-file-simple/Dockerfile
quickstarts/maven/docker-file-simple/pom.xml

Fix #240 
Add ports to ImageConfiguration generated in DockerFileUtil.createSimpleDockerfileConfig
by parsing contents of Dockerfile

Fix #240: No Ports exposed inside Deployment in case of Zero Config Dockerfile Mode

---

CHANGELOG.md
jkube-kit/jkube-kit-wildfly-jar/pom.xml

fix: wildfly-jar doesn't depend on common-maven module
For some reason wildfly-jar depends on common-maven module. This module should **only** be used in Maven plugins.

fix: wildfly-jar doesn't depend on common-maven module

---

.github/workflows/e2e-tests.yml

Port of https://github.com/fabric8io/kubernetes-client/pull/2553 to install JKube for all CI runs and cache the generated artifacts.
There shouldn't be any performance gain. Main reason is to allow tests to fail fast in case there are problems when installing JKube (we are getting many issues when downloading artifacts from maven central).

fix: CI fail-fast, install JKube and persist in ActionsCache

---

CHANGELOG.md
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/BaseEnricher.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/BaseEnricherGetReplicaCountTest.java

* Fix #488: Controller enricher replica count can be set to `0` when ResourceConfig is provided

fix: Controller enricher replica count can be set to `0` when ResourceConfig is provided

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/BuildOptions.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/ConfigKey.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/PropertyConfigHandler.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/BuildConfigTest.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/PropertyConfigHandlerTest.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/BuildConfigurationTest.java

Fix #484 : Port Cachefrom Support from DMP

Fix #484: CacheFrom parameter is missing in BuildConfiguration

---

CHANGELOG.md
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/PatchServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/WebServerEventCollector.java

Fix #455: Use OpenShiftServer with JUnit rule instead of directly instantiating the OpenShiftMockServer

---

jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricher.java
jkube-kit/enricher/specific/src/main/resources/META-INF/jkube/enricher-default
jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_service_discovery.adoc
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml

This is a port of ServiceDiscoveryEnricher from former Fabric8 Maven Plugin that adds 3scale discovery annotations to services.
Related to:
- https://issues.redhat.com/browse/ENTESB-15034
- https://github.com/fabric8io/fabric8-maven-plugin/pull/1394

ServiceDiscoveryEnricher from FMP

---

CHANGELOG.md
jkube-kit/parent/pom.xml
quickstarts/kit/custom-istio-enricher/README.md
quickstarts/maven/micronaut-customized-image/pom.xml
quickstarts/maven/micronaut/pom.xml
quickstarts/maven/spring-boot-with-jib/README.md
quickstarts/maven/xml-config/pom.xml

deps: Bump JKube base images to 0.0.9
Provides jkube-java-binary-s2i image with openjdk version "11.0.9.1" 2020-11-04 LTS
From:
```
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode, sharing)
```
To:
```
openjdk version "11.0.9.1" 2020-11-04 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1-LTS, mixed mode, sharing)
```
Relates to: https://github.com/jkubeio/jkube-images/pull/4

deps: Bump JKube base images to 0.0.9

---

kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_wildfly_jar.adoc

Signed-off-by: JF Denise jdenise@redhat.com
Fix typo.

Fix for #537, Typo in WildFly bootable JAR healthCheck documentation

---

jkube-kit/parent/pom.xml

fix: remove unneeded JRuby dependency

fix: remove unneeded JRuby dependency

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultNamespaceEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultNamespaceEnricherTest.java

Fix #511 
+ DefaultNamespaceEnricher should handle case when status is not provided in resource spec.
+ `.metadata.namespace` should be omitted from Project/Namespace resources since they are Cluster scoped
+ UndeployService should consider Project/Namespace resource while deletion phase

Fix #511: Namespace as resource fragment results in NullPointerException

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java

Prevents NPE thrown when `<dockerFile>` has no directory included (#518 )

Returns "./" if <dockerFile> doesn't include a directory to avoid NPE

---

CHANGELOG.md
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_compatibility.adoc

I've run integration tests on CRC with OpenShift versions 4.5.14 and
4.6.9 and plugin behavior seems to be consistent with older versions
of OpenShift.
Fix #510

Fix #510: Update Compatibility matrix for OpenShift 4.5 and 4.6

---

CHANGELOG.md
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/IngressRuleConfig.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/IngressRulePathConfig.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/IngressRulePathResourceConfig.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/IngressTlsConfig.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/IngressRuleConfigTest.java
jkube-kit/config/resource/src/test/resources/ingress-rule-config.json
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/IngressEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java
kubernetes-maven-plugin/it/src/it/ingress-xml-config/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/invoker.properties
kubernetes-maven-plugin/it/src/it/ingress-xml-config/pom.xml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/src/main/java/zero/Application.java
kubernetes-maven-plugin/it/src/it/ingress-xml-config/verify.groovy
quickstarts/maven/spring-boot/pom.xml

Fix #231 : IngressEnricher now supports generating Ingress from XML configuration

Fix #231: IngressEnricher ignores IngressRules defined in XML config

---

CHANGELOG.md
jkube-kit/config/image/pom.xml
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameFullNameParseTest.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java

Fix #523 
Periods can be in username too apart from registries. Refactor ImageName to consider this scenario.

Fix #523: period in image username omits registry in Deployment manifest

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java

Looks like I missed updating one entry of `client.customResourceDefinitions()`
in ApplyService while upgrading to fabric8 kubernetes client v5.0.0. We should be using client.apiextensions() DSL

Chore: Remove use of deprecated CustomResourceDefinition DSL in ApplyService

---

.circleci/config.yml
CHANGELOG.md

Upgrade build environment of sonar jobs on CircleCI

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/ValueProvider.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ProcessUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java

Fix: Removed Guava Functional interfaces

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandler.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/compose/DockerComposeServiceWrapper.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/ValueProvider.java

Fixes SonarCloud Debt for replacing **`Boolean.valueOf`** with **`Boolean.parseBoolean`** for `string` to `boolean` conversion
Closing this PR should fix #545 

Replace Boolean.valueOf with Boolean.parseBoolean for string to boolean conversion

---

CHANGELOG.md
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricher.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricherTest.java

The way the health path is builded for quarkus application is not correct.

Fixing quarkus health paths

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftUndeployServiceTest.java
jkube-kit/parent/pom.xml
kubernetes-maven-plugin/plugin/pom.xml
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/LogMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojo.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojoTest.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/LogMojoTest.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojoTest.java
kubernetes-maven-plugin/pom.xml
pom.xml
scripts/changelog.sh

feat: Apply and Undeploy service use configured Namespace
As opposed to using a property that was read from Maven and passed on
as a System property.

feat: Apply and Undeploy service use configured namespace

---

CHANGELOG.md
jkube-kit/build/api/pom.xml
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManager.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerCreateDockerTarArchiveTest.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/build/_assembly.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/build/_overview.adoc

Fix #529 
Added `.jkube-dockerignore`, `.jkube-dockerexclude` and `.jkube-dockerinclude` in AssemblyManager while creating Dockerfile assembly configuration
Ported methods for handling docker includes and docker excludes from https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java#L325-L352

Fix #529: `.maven-dockerignore`, `.maven-dockerexclude`, `.maven-dockerinclude` are no longer supported

---

CHANGELOG.md
jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxGenerator.java
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxGeneratorTest.java
kubernetes-maven-plugin/it/src/it/remote-resources/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/vertx/expected/kubernetes.yml
openshift-maven-plugin/it/src/it/remote-resources/expected/openshift.yml
openshift-maven-plugin/it/src/it/vertx/expected/openshift.yml
quickstarts/maven/vertx4/README.md
quickstarts/maven/vertx4/pom.xml
quickstarts/maven/vertx4/src/main/java/org/eclipse/jkube/quickstarts/maven/MainVerticle.java

feat: Improved Vert.x 4 support + added quickstart
#584  

feat: Improved Vert.x 4 support + added quickstart

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Base64Util.java
jkube-kit/parent/pom.xml
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
pom.xml

and align (transitive) dependencies
upgrading to latest Kubernetes Client 5.1.1 #592
First draft. Currently failing:
```
com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while parsing a block mapping
in 'reader', line 6, column 5:
app: test
^
expected <block end>, but found '<scalar>'
in 'reader', line 9, column 34:
helm-variable: "(( required "A valid .Values.global_template_ ... 
^
at [Source: (StringReader); line: 9, column: 34]
at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:359)
at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:868)
at …
```

Update Kubernetes Client from 5.0.0 to 5.1.1 #592

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java

In debug mode with suspend mode enabled (`-Djkube.debug.suspend`), the Kubernetes cluster restarts the pod if the remote debug session is not started soon enough, or the application startup debug process takes longer than the livenessProbe periods.
Documentation states that when [Debugging with suspension](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#_debugging_with_suspension):
>The jkube.debug.suspend flag will disable readiness probes in the Kubernetes deployment in order to start port-forwarding during the early phases of application startup
JKube correctly disables the readiness probes, but not the liveness probe. This means that if the configured liveness probe depends on the application running and we're on the middle of a debug session, maybe the liveness probe won't …

Debugging with suspend mode doesn't prevent Kubernetes cluster to restart the pod

---

CHANGELOG.md
jkube-kit/resource/helm/pom.xml
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/Chart.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/ChartTest.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmConfigTest.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/MaintainerTest.java
jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/Chart.yaml
jkube-kit/resource/helm/src/test/resources/it/expected/openshift/Chart.yaml

fix #591: Helm linter no longer fails with generated charts
+ updated jkube-kit-resource-helm to use assertj instead of hamcrest

fix: Helm linter no longer fails with generated charts

---

CHANGELOG.md
jkube-kit/common-test/pom.xml
jkube-kit/common-test/src/main/java/org/eclipse/jkube/kit/common/assertj/ArchiveAssertions.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/JKubeTarArchiver.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/JKubeTarArchiverTest.java
jkube-kit/resource/helm/pom.xml
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java

fix #587: Helm tar.gz packaged chart can be deployed

fix: Helm tar.gz packaged chart can be deployed

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WaitService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerCreateConfig.java

Replace usages of deprecated `org.apache.commons.text.StrSubstitutor` with `org.apache.commons.text.StringSubstitutor`.
Fixes #571 

Replace usages of deprecated StrSubstitutor

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/PortMapping.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/ImageConfigResolver.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/compose/ComposeUtils.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/PropertyMode.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/DockerPathUtil.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/VolumeBindingUtil.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilder.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ProcessorConfig.java

Fix #471: Remove the declaration of thrown runtime exceptions across javadoc

---

kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java

**Enhancement**
Current state:
When user wants to specify replica count, he has to use either _-Djkube.enricher.jkube-controller.replicaCount_ or _-Djkube.enricher.jkube-controller-from-configuration.replicaCount_ based on if resource fragments are used or not. This can be very confusing for users.
Proposal:
Unify both approaches (DefaultControllerEnricher and ControllerViaPluginConfigurationEnricher) to use _-Djkube.replicaCount_ instead
Reference issue: https://issues.redhat.com/browse/ENTESB-16080

Re-introduce jkube.replicas property

---

CHANGELOG.md
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/PropertiesUtilTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java

Fix #624 
Modify Mojos logic to consider image name configured from properties

Fix #624: Unable to override Image Name in Simple Dockerfile Mode with `jkube.generator.name`

---

CHANGELOG.md
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/parent/pom.xml

Update Fabric8 Kubernetes Client to v5.3.0
CQs:

Update Fabric8 Kubernetes Client to v5.3.0

---

CHANGELOG.md
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc

Fix #602 Add some documentation about service expose labels in Route generation
section for resource goal

Fix #602: Add documentation regarding automatic Route generation

---

CHANGELOG.md
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc

Relates to #630 
+ Added documentation for `jkube.build.switchToDeployment` flag

Fix #630: Add documentation for switchToDeployment flag

---

CHANGELOG.md
jkube-kit/jkube-kit-quarkus/pom.xml
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java

Signed-off-by: dloiacono <dloiacono@gmail.com>
Quarkus 1.12 was released last month which made Fast-jar packaging as default. Earlier we used to run *-runner.jar in previous versions, but now it's replaced by this:
java -jar target/quarkus-app/quarkus-run.jar
You can read more about it here.
Right now users can't use jkube in zero-configuration mode with Fast Jar. JKube fails with not being able to find -runner.jar:
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.1.1:build (default-cli) on project rosa-fruits-app: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.1.1:build failed: Can't find single file with suffix '-runner.jar' in …

Add support for Quarkus Fast Jar Packaging

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/chunked/EntityStreamReaderUtil.java

Replace deprecated JsonParser

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/JKubeProjectUtil.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusMode.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusUtils.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusAssemblies.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusModeTest.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusUtilsTest.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
quickstarts/maven/quarkus/pom.xml

refactor: QuarkusGenerator packaging configurable from everywhere*
- Project/Maven properties
- Application properties (.properties / .yaml)
- Inference from target/build directory structure
Closes #632 

refactor: QuarkusGenerator packaging configurable from everywhere*

---

CHANGELOG.md
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_configmap_file.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_namespace.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_service.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-build.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/BuildMojoTest.java

Fix #639 
+ Fixed OpenShift BuildConfig not getting picked up bug
+ Add documentation for XML resource configuration options

Fix #639: Configuring Quotas for OpenShift BuildConfig not working as expected

---

jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java

Set time image creationTime on jib api
bug fix

set jib image creation time

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtilTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java

fix: Custom Resource fragments can be replaced and recreated with FKC 5.3.x

fix: Custom Resource fragments can be replaced and recreated with FKC 5.3.x

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ResourceUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ResourceUtilTest.java
jkube-kit/common/src/test/resources/util/resource-util/custom-resource-cr.yml
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java
jkube-kit/resource/service/src/main/java/org/eclipse/jkube/kit/resource/service/WriteUtil.java
jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/WriteUtilTest.java

fix: Helm charts can be generated for custom resources, even those with same name (different apiGroup)

fix: Helm charts  generated for custom resources, even those with same name

---

CHANGELOG.md
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java

Fix #673 
ResourceConfig's port mapping doesn't seem to be getting used anywhere
neither there is any documentation about it's usage. I only see port
configuration via ServiceConfig or via <image> configuration.

Chore #673: Remove unused ports mapping field from ResourceConfig

---

CHANGELOG.md
jkube-kit/build/api/pom.xml
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManager.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerCreateDockerTarArchiveTest.java
jkube-kit/common-test/src/main/java/org/eclipse/jkube/kit/common/assertj/FileAssertions.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtils.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtilsExcludesTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtilsProcessAssemblyFileSetTest.java

fix: Only assembled files are copied to 'Docker' build target directory
- Increase in performance
- Avoids problems with excluded .git directories
Fixes (tentatively) #590

fix: Only assembled files are copied to 'Docker' build target directory

---

CHANGELOG.md
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/build/_configuration.adoc

Fix #497 
Remove assembly `<descriptor>` field from documentation as it's no
longer supported

Fix #497: Assembly descriptor removed but still in documentation

---

CHANGELOG.md
jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricher.java
jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/ServiceDiscoveryEnricherTest.java

Fix #704 
Add a user friendly message to NPE whenever Service Port is not provided
by user in fragment

Fix #704: NPE when using Service fragment with no port specified

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/AuthConfig.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/FromConfigRegistryAuthHandlerTest.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/SystemPropertyRegistryAuthHandlerTest.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/CredentialHelperClient.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSdkAuthConfigFactory.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSdkHelper.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactoryTest.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/CredentialHelperClientTest.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSdkAuthConfigFactoryTest.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/DockerRegistryAuthHandlerTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_authentication.adoc

Add support in AuthConfigFactory to retrieve credentials from
different mechanisms for AWS.
Port of https://github.com/fabric8io/docker-maven-plugin/pull/1311
Port of https://github.com/fabric8io/docker-maven-plugin/pull/1310
Related to #702

Fetch AWS Credentials from AWS SDK/Environment variables

---

CHANGELOG.md
jkube-kit/parent/pom.xml

chore(deps): Bump httpclient from 4.5.10 to 4.5.13

---

CHANGELOG.md
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusAssemblies.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGenerator.java

Improved the Quarkus generator to make use of the new multi-layer feature (#425).
Produces a single layer image with the native binary
Produces a single layer image with the runner fat-jar
Produces a 2 layer image:
- `lib` contains the libraries and dependencies
- `artifact` contains the slim runner jar
Produces a 2 layer image:
- `lib` contains **only** the libraries and dependencies
- `fast-jar` contains the every other file and directory (excluding lib/**/*) in the `quarkus-app` directory
| Cluster   | Packaging mode | Build strategy |                    |
|-----------|----------------|----------------|--------------------|
| Minikube  | native         | docker         | :heavy_check_mark: |
| Minikube  | native         | jib            | :heavy_check_mark: |
| Minikube  | uber-jar …

feat: QuarkusGenerator: Multi-layer images for the different Quarkus packaging modes

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServicePortOrderTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java
jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherTest.java

Fix #653
Make order of port forward arguments consistent across Service classes.
Now all methods have containerPort, remotePort argument format

Fix #653: `k8s:watch` port-forward websocket error due to wrong arguments in PortForwardService

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ProbeConfig.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandler.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
kubernetes-maven-plugin/it/src/it/probes-xml-config/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/probes-xml-config/invoker.properties
kubernetes-maven-plugin/it/src/it/probes-xml-config/pom.xml
kubernetes-maven-plugin/it/src/it/probes-xml-config/src/main/java/probe/Application.java
kubernetes-maven-plugin/it/src/it/probes-xml-config/src/main/java/probe/HelloController.java
kubernetes-maven-plugin/it/src/it/probes-xml-config/verify.groovy

Fix #672 
+ Add missing fields in ProbeConfig for configuring liveness/readiness
+ Added a check to keep host null in case it matches localhost

Fix #672: Add missing fields in ProbeConfig for configuring Readiness/Liveness Probes

---

jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/JKubeBuildTarArchiver.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/VolumeService.java

Remove unused import in VolumeService.java and JKubeBuildTarArchiver.java 

Remove unused imports, issues #773 and #774

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PatchService.java

Fix #756 
Use patch() instead of edit() since we don't seem to be making use of the `p`(argument in UnaryOperator which is usually resource fetched from Server).
Based on discussion here https://github.com/fabric8io/kubernetes-client/pull/3221#discussion_r665441853

Fix #756: Service re-apply error happening during `k8s:watch`

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/Arguments.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/ArgumentsTest.java

Fixes #755
This PR removes redundant code from `Arguments.java` as pointed by Sonar Cloud and https://github.com/eclipse/jkube/issues/755#issue-935580117.

Remove redundant code from Arguments.java

---

CHANGELOG.md
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusUtils.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricher.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/generator/QuarkusGenerator.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusUtilsTest.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricherTest.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_enricher.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_quarkus.adoc

Fix #758 
QuarkusHealthCheckEnricher now reads quarkus properties related to
rootPath(`quarkus.http.root-path`), nonApplicationRootPath(`quarkus.http.non-application-root-path`) and health checks(`quarkus.smallrye-health.root-path`,`quarkus.smallrye-health.liveness-path`) in order to
evaluate health check endpoints for Quarkus versions  greater than 1.11.x

Fix #758: QuarkusHealthCheckEnricher default health path outdated

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ExternalCommand.java

Fixes #785
Change the visibility of the constructor to protected in `ExternalCommand.java`.
Hi @manusa, how does this look?
Let me know if this needs any changes.
Thanks

change the visibility of constructor to protected

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/LazyBuilderTest.java

Changed LazyBuilderTest to use AssertJ in place of hamcrest
Fix https://github.com/eclipse/jkube/issues/786

Changed hamcrest to assertj for unit test

---

CHANGELOG.md
jkube-kit/common-test/src/main/java/org/eclipse/jkube/kit/common/assertj/ArchiveAssertions.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/JKubeTarArchiver.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/JKubeTarArchiverTest.java
jkube-kit/common/src/test/resources/jkubetararchiver-directory/jkubetararchiver-non-empty-file.txt

Fix #777 
Tar files generated during `k8s:build` were getting rejected from Docker
v1.12.1 (API version 1.24). Not setting size of TarArchiveEntry in case
of directories seem to fix this issue

Fix #777: Failure in processing generated tarball by old Docker versions

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/ImagePullManager.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/ConfigHelper.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/ImagePullManagerTest.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/ConfigHelperTest.java
jkube-kit/build/service/docker/src/test/resources/dummy-javaproject/Dockerfile
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/BuildReferenceDateUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/BuildReferenceDateUtilTest.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/RegistryAuthConfiguration.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java

Some code related to initialization of ImageConfiguration,
BuildTimestamps etc seems to be common in both gradle and maven plugins.
Moving this common code to JKube Kit in order to avoid duplication

KubernetesBuildTask Prequisire Refactor: Move code from AbstractDockerMojo to JKube Kit

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java

Right now everytime OpenShiftBuildServiceUtilsTest is run it creates a
file named `s2i-env-myapp` in jkube-kit/config/service directory. It's quite
annoying behavior; and it's due to buildDirectory being set as null in
BuildServiceConfig.
Explicitly set BuildServiceConfig.buildDirectory to some temporaryFolder
value in order to avoid this

Fix OpenShiftBuildServiceUtilsTest: Set buildDirectory to some temporaryFolder

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java

I noticed GradleUtil.findArtifact was picking the plain jar instead of
fat jar. We can sort all artifacts files by size so that fat jar with
larger size gets picked.
~Once we have the artifact, we can check it's name to find out whether
project has war or jar packaging~

[GRADLE PLUGINS] GradleUtil  pick finalArtifact of largest size

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/JKubeProjectUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/JKubeProjectUtilTest.java

In case artifact is set in JavaProject, pick finalArtifact from
this field. Keeping this as a fallback to old method to not break
any backward compatibility

JKubeProjectUtil.getFinalOutputArtifact : Pick finalArtifact file from JavaProject.artifact if present

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTask.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java

When JIB build strategy is picked, we were getting some
NullPointerExceptions due to BuildServiceConfig and
DockerServiceHub(required by OpenShiftBuildService) not
getting initialized.
Moving this initialization block out of `isDockerAccessRequired() { // .. }`
block.

Fix errors related to JIB mode

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java

Fix #815 
Using OpenShiftClient to store result of `clusterAccess.createDefaultClient()` seems to
cause ClassCastException when return value is of type DefaultKubernetesClient.
Instead, Use a temporaty KubernetesClient variable for `clusterAccess.createDefaultClient()`
and type cast it to OpenShiftClient in case it's adaptable to OpenShiftClient interface.
This would be the behavior after this change:
1. On OpenShift Cluster: Regular OpenShift S2I build as usual
2. On Kubernetes Cluster: `[ERROR] oc: Failed to execute the build [OpenShift platform has been specified but OpenShift has not been detected!]`
3. No Cluster: `Unknown host kubernetes.default.svc` 

Fix #815: ClassCastException during oc:build when OpenShift not present

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GroovyUtil.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GroovyUtilTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionTest.java
quickstarts/gradle/micronaut-customized-image/gradle/wrapper/gradle-wrapper.properties
quickstarts/gradle/spring-boot/build.gradle

feat: KubernetesExtension#images can be configured leniently
Images can now be configured with the following syntax options:
```groovy
// The most groovy compliant way
images {
image {
name = 'image1'
}
image {
name = 'image2'
}
}
// As a map of image entries
images {
image1 {
name = 'image1'
}
image2 {
name = 'image2'
}
}
// As a list of image entries
images ([
{
name = 'image1'
},
{
name = 'image2'
}
])
```

feat: KubernetesExtension#images can be configured leniently

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java

Fix #822
Signed-off-by: Jendrik Badde <jendrikbadde@gmail.com>

Fix#822: Use .equals() for JKubeBuildStategy enum instead of extracting label

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java

Fix #854: %n should be used in place of \n to produce the platform-specific line separator. 

---

jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MavenUtil.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JavaProject.java
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorMainClassDeterminationTest.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java
jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGeneratorTest.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java
jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorTest.java
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxGeneratorTest.java
jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java

Gradle's build directory doesn't contain jar files unlike maven.
Adding an additional field outputArtifactDir which will store parent
directory of artifact file.
JavaExecGenerator would make use of outputArtifactDir field in order to
look for fat jars and creating AssemblyFileSets
Related to #850

Pre-requisite for #850: Add outputArtifactDir to JavaProject

---

gradle-plugin/it/src/it/dockerfile-simple/expected/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/DockerfileSimpleIT.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ITGradleRunner.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTaskTest.java

Fix #882 
Provide `oc:resource` equivalent functionality to Kubernetes Gradle
Plugin.
Should be merged after #861

Fix #882: Add OpenShiftResourceTask to Kubernetes Gradle Plugin

---

gradle-plugin/it/src/it/extension-configuration/build.gradle
gradle-plugin/it/src/it/extension-configuration/expected/expected-config.yml
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtension.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java

Fix #880
Pre-requisite for #881
Add required configuration options for KubernetesApplyTask to KubernetesExtension.

Fix #880: Add Configuration Options for KubernetesApplyTask to KubernetesExtension

---

CHANGELOG.md
jkube-kit/parent/pom.xml

deps: Bump [JKube base images](https://quay.io/repository/jkube/jkube-java-binary-s2i?tab=tags) to [0.0.10](https://quay.io/repository/jkube/jkube-java-binary-s2i/manifest/sha256:b6a0e84440061ab27064534e342d99077aa4e8466913e74b16218c86baf74f00?tab=vulnerabilities).
New images don't have security warnings.

deps: Bump JKube base images to 0.0.10

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftResourceMojoTest.java

Right now `%g` placeholder which corresponds to default image user picks
`jkube.image.user` property first, if not then project groupId.
Due to a typo in ResourceMojo for DOCKER_IMAGE_USER property, wrong
property was being set in mojo.
Changes regarding changing access modifiers of some fields in ResourceMojo are only done
in order to be able to have them available in OpenShiftResourceMojoTest
Relates to #904

`%g` should be resolved to namespace in OpenShift Maven Plugin

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricherTest.java

Fix #904
Setting from.namespace field from image.getUser() can be problematic if
it's not equal to the namespace. If it's set to `%g`, it will work since
JKube will evaluate to current configured namespace but if user defines
image name to have a different user then ImageChangeTrigger would be
configured with a non-existent namespace.
Don't set from.namespace field for ImageChangeTrigger while adding
ImageChangeTrigger to DeploymentConfig

Fix #904: DeploymentConfig ImageChange trigger seems to be wrong for custom images

---

CHANGELOG.md
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java

Fix #908 
In quickstarts/maven/quarkus-customized-image,
KubernetesResourceUtil.extractContainerName tries to create an
opinionated container name from image name, but  in case image user also
contains periods, it doesn't sanitize it.
Add a replaceAll statement to sanitize returned imageUser.

Fix #908: OpenShift-Maven-Plugin doesn't remove periods from opinionated container name

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/ImageNameFormatter.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java

We have `jkube.image.user` property constant defined in both
ResourceMojo and ImageNameFormatter. In feat/gradle-plugin branch it's
also used by OpenShiftResourceTask.
Expose this constant in ImageNameFormatter so that it can be reused in
Mojos and Tasks.

Expose `jkube.image.user` property in ImageNameFormatter for reuse in Mojos

---

gradle-plugin/it/src/it/dockerfile-simple/expected/openshift.yml
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTaskTest.java

This property was wrongly named in ResourceMojo, for maven plugins
this got fixed in #910.
Fix property name in OpenShiftResourceTask as well

followup #910: Correct DOCKER_IMAGE_USER property in OpenShiftResourceTask

---

quickstarts/gradle/spring-boot-camel-complete/build.gradle
quickstarts/gradle/spring-boot/build.gradle

Related to #903 
+ Add OpenShift Gradle Plugin to Spring Boot Camel Complete Quickstart
+ Remove offline: true statement from openshift gradle plugin
configuration in spring boot quickstart

Chore: Update Spring Boot Quickstarts to use OpenShift Gradle Plugin & Don't set Offline to true

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/FileUtilTest.java

Fix #895
FileUtil#createDirectory works for files with trailing separator (`/`)
Provided test was failing before the fix was implemented.

fix: FileUtil#createDirectory works for files with trailing separator (`/`)

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_project_label.adoc

Fix #913 : make provider name configurable

Fix #913 : make provider name configurable

---

gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftApplyTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftApplyTaskTest.java

Fix #921
Add OpenShiftApplyTask to OpenShift Gradle Plugin which just extends
KubernetesApplyTask. There was no need to override any behavior from
KubernetesApplyTask since all configuration options are overridden in
case of OpenShiftExtension.

Fix #921: Implement `oc:apply` equivalent functionality for OpenShift Gradle Plugin

---

gradle-plugin/it/src/it/extension-configuration/build.gradle
gradle-plugin/it/src/it/extension-configuration/expected/expected-config.yml
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java

Fix #934
Add Configuration fields required by KubernetesPushTask to KubernetesExtension

Fix #934: Add KubernetesPushTask related configuration options to KubernetesExtension

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/TaskUtil.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskUtilTest.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftBuildTask.java

Fix #939
KubernetesBuildTask's initJKubeServiceHubBuilder() and
buildServiceConfigBuilder() are same as implementation for
KubernetesPushTask.
Moving them to a helper class BuildTaskHelper in order to reuse them.

Fix #939: Move KubernetesBuildTask's common initialization logic to a helper class

---

gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
gradle-plugin/doc/src/main/asciidoc/inc/tasks/build/_jkube-push.adoc
gradle-plugin/doc/src/main/asciidoc/inc/tasks/build/_tasks.adoc
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SimpleIT.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesPlugin.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTask.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java

Fix #935
Kubernetes Push Task ported to gradle
~Should be ready once #941 gets merged.~

Fix #935: Implement `k8s:push` equivalent functionality `k8sPush` for Kubernetes Gradle Plugin

---

gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SimpleIT.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftPushTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftPushTaskTest.java

Fix #945
Port OpenShiftPushMojo to OpenShift Gradle Plugin
Requires #941 and #942 to get merged first.

Fix #945: Implement `oc:push` task equivalent OpenShiftPushTask in OpenShift Gradle Plugin

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java

While testing #944, I noticed that Gradle project.getProperties() don't
contain System Properties which are passed to JVM. So some property
passed like like won't work:
```
gradle -Djkube.offline=true ocApply
```
Modify GradleUtil.extractProperty to include System.getProperties() as
well while converting Gradle Project to JavaProject

GradleUtil.extractProperty should also extract System Properties

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java

Fixes Issue #937 by handling the InterruptedExceptions by reinterrupting the thread in JibBuildService without suppressing

Fixes Issue #937: Handle InterruptedExceptions

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesUndeployTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/TaskUtil.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionPropertyTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesConfigViewTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesUndeployTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskUtilTest.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtension.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtensionPropertyTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftApplyTaskTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftPushTaskTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftUndeployTaskTest.java

Fix #952
KubernetesExtension and OpenShiftExtension can be configured via
properties.
Added property resolution logic inside KubernetesExtension and
OpenShiftExtension

Fix #952: KubernetesExtension and OpenShiftExtension field values can be configured with properties

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionPropertyTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java

fix: #949 
feat: KubernetesExtension has required configuration options for debug

feat: KubernetesExtension has required configuration options for debug

---

gradle-plugin/it/src/it/extension-configuration/build.gradle
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SimpleIT.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java
quickstarts/gradle/spring-boot/build.gradle
quickstarts/gradle/spring-boot/gradle/wrapper/gradle-wrapper.properties

fix: Gradle dependencies completely resolved with versions
Allows Enrichers (like SpringBoot Health Check) to work since
they rely on transitive dependencies with versions.

fix: Gradle dependencies completely resolved with versions

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/UrlBuilder.java

Fix #953 
Changed ret String array declaration from C Style to Java Style.
Signed-off-by: SIDDHANT DIXIT <siddhant.dixit23@gmail.com>

Java style array declaration

---

CHANGELOG.md
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java

Fix #971 
Rethrow interrupted exception in ApplyMojo.java

Rethrow InterruptException that is caught in ApplyMojo.java

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogOutputSpec.java

Fix #972 , have made variables final as these were modified only in constructor

making private variables as final

---

gradle-plugin/pom.xml
jkube-kit/doc/pom.xml
jkube-kit/parent/pom.xml
kubernetes-maven-plugin/doc/pom.xml
pom.xml

chore: bump asciidoctorj from 2.1.0 to 2.2.0 and asciidoctor-maven-plugin from 1.6.0 to 2.2.1 to enable doc watch on all files

---

quickstarts/kit/docker-image/src/main/java/org/eclipse/jkube/quickstart/kit/docker/Main.java
quickstarts/kit/dynamic-docker-image-file-multi-layer/src/main/java/org/eclipse/jkube/quickstart/kit/docker/dynamic/Main.java
quickstarts/kit/helm/README.md
quickstarts/kit/helm/pom.xml
quickstarts/kit/helm/src/main/java/org/eclipse/jkube/quickstart/kit/Main.java
quickstarts/kit/helm/static/deployment.yml

doc: Quickstart showing how to use JKube kit to dynamically generate Helm charts
This quickstart showcases most of the JKube's features regarding Helm chart generation.
- Use a Template to declare Chart values/variables
- Generate resource YAML manifests using Fabric8 Kubernetes client with placeholder to use variables
- Reuse existing YAML files to read pre-generated manifests
This should be a good starting point for users who want to generate Helm charts programmatically.
/cc @iocanel

doc: Quickstart showing how to use JKube kit to dynamically generate Helm charts

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ImageEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ImageEnricherTest.java

Fix #887
Don't log a warning about not overriding environment variable when both
old and new values are same.

Fix #887: Incorrect warning about overriding environment variable

---

CHANGELOG.md
jkube-kit/config/service/pom.xml
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
jkube-kit/config/service/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Waiting for #1120 
- fix #1115: OpenShiftBuildService flattens assembly only if necessary
- test: replaced jmockit with mockito
- chore: Add missing changelog entries

OpenShiftBuildService flattens assembly only if necessary

---

CHANGELOG.md
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java

fix: Helm supports `.yaml` and `.yml` source files

fix: Helm supports `.yaml` and `.yml` source files

---

gradle-plugin/doc/pom.xml
jkube-kit/doc/pom.xml
kubernetes-maven-plugin/doc/pom.xml
pom.xml

Fix #1034
This is finalising https://github.com/eclipse/jkube/issues/1034
1. extract common properties to the jkube parent pom.xml
2. added doc-watch profile for jkit and gradle doc
to try it run in either jkit or gradle doc project:
```
mvn clean -Pdoc-watch package
```
Make some changes in adoc files and see the site updated when refreshing the browser

chore: #1034 enable documentation autorefresh for jkit and gradle doc

---

.circleci/config.yml

Revert "chore: Update Docker Image used in Sonar workflows to eclipse-temurin:11"
This reverts commit 5a6c996f6b00b5e1fc8fc52a1518b0762782ba91.
Should no longer be necessary after fixes/refactor in OpenShiftBuildTest

Revert "chore: Update Docker Image used in Sonar workflows to eclipse-temurin:11"

---

CHANGELOG.md
gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
gradle-plugin/it/src/it/extension-configuration/build.gradle
gradle-plugin/it/src/it/extension-configuration/expected/expected-config.yml
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTask.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionPropertyTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTaskTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java

Fix #961
Add `canExecute` method in AbstractJKubeTask which decides whether a
task would get executed or not. Child Tasks would override this method
to modify factors on which execution would be skipped.

Fix #961: `k8sBuild`, `k8sResource` and `k8sApply` don't respect Skip options

---

gradle-plugin/it/src/it/extension-configuration/build.gradle
gradle-plugin/it/src/it/extension-configuration/expected/expected-config.yml
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionPropertyTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/TestKubernetesExtension.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/TestOpenShiftExtension.java

Add KubernetesWatchTask related configuration fields in KubenetesExtension.
Related to #1109

Add Configuration options for KubernetesWatchTask to KubernetesExtension

---

gradle-plugin/doc/src/main/asciidoc/inc/scenarios/_fragments.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
quickstarts/maven/external-resources/src/main/jkube/deployment.yml

We assume the name prefix `KUBERNETES_` on env vars is meant for Kubernetes/OpenShift own use. Therefore we should not encourage users to create custom env vars with this name prefix.
Fixes #1132
Note:  The name `KUBERNETES_NAMESPACE` name is also used in `jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandler.java` which is deliberately not touched in this PR as users may rely on this behavior ... even if it has never been documented/promised anywhere, AFAIK.

Doc and examples: Avoid using prefix KUBERNETES_ on env vars

---

gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftWatchTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginRegisterTaskTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftWatchTaskTest.java

Fix #1110 
Add OpenShiftWatchTask to OpenShift Gradle Plugin
Requires #1133 to be merged first

Fix #1110: Implement `oc:watch` equivalent functionality ocWatch for OpenShift Gradle Plugin

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/IngressEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_ingress.adoc
kubernetes-maven-plugin/it/src/it/ingress-xml-config/expected/xml-config/kubernetes.yml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/expected/zero-config-extensionsv1beta1-enricher-config/kubernetes.yml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/expected/zero-config-extensionsv1beta1-host-enricher-config/kubernetes.yml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/expected/zero-config-host-enricher-config/kubernetes.yml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/expected/zero-config-no-host/kubernetes.yml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/invoker.properties
kubernetes-maven-plugin/it/src/it/ingress-xml-config/pom.xml
kubernetes-maven-plugin/it/src/it/ingress-xml-config/verify.groovy

Fix #1030 
Change IngressEnricher's `targetApiVersion` to `networking.k8s.io/v1`
from `extensions/v1beta1`. Now default Ingress would be of
`networking.k8s.io/v1` apiVersion.

Fix #1030: Update IngressEnricher's default targetApiVersion to `networking.k8s.io/v1`

---

.gitignore

Git should ignore `bin` folders generated by vscode-java or Eclipse IDE

chore: gitignore bin folders generated by vscode-java or Eclipse IDE

---

CHANGELOG.md
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusUtils.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorTest.java

Relates to #1047 
gradle image build should use the Quarkus generator for Quarkus projects #1047

fix: gradle image build should use the Quarkus generator for Quarkus projects #1047

---

CHANGELOG.md
quickstarts/gradle/spring-boot-helm/gradle.properties
quickstarts/gradle/spring-boot-helm/src/main/jkube/deployment.yml

Fix #900
+ Use already provided properties `name` and `version` for getting
project artifactId and version rather than hardcoded properties

Fix #900: Remove `projectArtifactId` and `projectVersion` from `gradle.properties` in Spring Boot Helm Quickstart

---

CHANGELOG.md
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/UndeployMojo.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojoTest.java

Fix #1190
OpenShiftBuildService currently applies generated resources (Build,
BuildConfig, ImageStream, ImageStreamTag) in currently logged in
namespace. This means providing namespace configuration in plugin would
have no effect on OpenShift S2I build.
+ Add a namespace parameter to JKubeConfiguration which will be picked by
OpenShiftBuildService for determining namespace while applying
resources.
+ Move `jkube.namespace` property to parent Mojos(AbstractJKubeMojo, AbstractDockerMojo) to 
avoid duplication

Fix #1190: OpenShiftBuildService doesn't apply resources in configured namespace

---

CHANGELOG.md
jkube-kit/config/resource/pom.xml
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
jkube-kit/config/resource/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
jkube-kit/parent/pom.xml
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/ExecListenerLatch.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/PodExecutor.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherTest.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/ExecListenerLatchTest.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojoTest.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojoTest.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/LogMojoTest.java

deps: Bump Kubernetes Client to 5.11.2

deps: Bump Kubernetes Client to 5.11.2

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojoTest.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/SkipGoalsTest.java

Log informative message when  maven jkube goals are skipped.
part of https://github.com/eclipse/jkube/issues/1142

feat(maven-plugin): log informative message when maven jkube goals are skipped #1142

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandler.java
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/KubernetesConfigAuthUtil.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/KubernetesConfigAuthUtilTest.java
jkube-kit/build/api/src/test/resources/org/eclipse/jkube/kit/build/api/helper/kubernetes-config-auth/kube-config-missing-current-context.yaml
jkube-kit/build/api/src/test/resources/org/eclipse/jkube/kit/build/api/helper/kubernetes-config-auth/kube-config.yaml
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/compose/DockerComposeConfigHandler.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactoryTest.java
jkube-kit/common-test/pom.xml
jkube-kit/common/pom.xml
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java
jkube-kit/parent/pom.xml

fix: SnakeYaml uses SafeConstructor or delegates to Fabric8 Kubernetes Client

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskEnvironment.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskEnvironment.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/JavaProject.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/JKubeProjectUtil.java

feat: Gradle Plugin classes persisted in JavaProject
Required for some generators.
Can be used like:
```java
JKubeProjectUtil.hasGradlePlugin(getProject(), "io.openliberty.tools.gradle.Liberty")
```
or
```java
JKubeProjectUtil.hasGradlePlugin(getProject(), "org.gradle.api.plugins.JavaPlugin")
```

feat: Gradle Plugin classes persisted in JavaProject

---

CHANGELOG.md
jkube-kit/build/service/docker/pom.xml
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java

Fix #1055
Right now podman daemon doesn't fail the build sometimes when it's not
able to build image sucessfully. In case of #1055, image was being built
but when plugin tries to fet image id of the corresponding built image,
podman fails to resolve it and therefore `null` message is printed.
Add a null check when image id isn't resolved and throw an
IllegalStateException instead.
So instead of logging this:
```
[INFO] k8s: [java/live-stream-question:1.0.0]: Built image null
```
we should see this exception being thrown:
```
[ERROR] k8s: Failed to execute the build [Failure in building image, unable to find image built with name java/live-stream-question:1.0.0]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] …
```

fix : Throw Exception when podman daemon returns `null` for image id post build(#1055)

---

gradle-plugin/doc/src/main/asciidoc/inc/getting-started/_index.adoc
gradle-plugin/doc/src/main/asciidoc/inc/getting-started/_vertx.adoc

Add a quick getting started doc for Vert.x to common scenarios section
Related to #1146 

Add Documentation Vert.x zero config scenario to Common Scenarios

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/ConfigHelper.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/helper/ConfigHelperTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
openshift-maven-plugin/plugin/pom.xml
openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftResourceMojoTest.java

Add a log statement for Docker Build context directory when building a
docker image in Simple Dockerfile mode.
Related to https://github.com/eclipse/jkube/issues/1055

Log Docker Build Context Directory while building image in Simple Dockerfile mode

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RegistryService.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/AbstractImageBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java

Fix #1195
There is a skip field in BuildConfiguration class which skips image
build when enabled, but this doesn't work for push. Plugin tries to push
images even when they're not built and fails.
Handle skip field in RegistryService and JibBuildService

fix(jkube-kit) : Push goal doesn't skip push when image build skip field enabled (#1195)

---

CHANGELOG.md
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/Enricher.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/Constants.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ConfigMapEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/FileDataSecretEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ConfigMapEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/FileDataSecretEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_configmap_file.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_secret_file.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc
kubernetes-maven-plugin/it/src/it/secret-config/src/main/jkube/docker.yml
openshift-maven-plugin/it/src/it/secret-config/src/main/jkube/docker.yml

`maven.jkube.io` seems to be a side effect of search-replace during
migration from FMP to JKube. Deprecate all annotation properties
starting with this prefix.
Introduce the use of `jkube.eclipse.org` prefix instead.

chore: Deprecate `maven.jkube.io` annotation prefix from enrichers

---

CHANGELOG.md
gradle-plugin/doc/src/main/asciidoc/inc/tasks/build/_jkube-helm.adoc
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/Maintainer.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/MapUtilTest.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmConfigTest.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/templates/kubernetes.yaml
jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/values.yaml
jkube-kit/resource/helm/src/test/resources/it/expected/openshift/values.yaml
jkube-kit/resource/helm/src/test/resources/it/sources/global-template.yml
jkube-kit/resource/helm/src/test/resources/it/sources/kubernetes/kubernetes.yml
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-helm.adoc
kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/helm/templates/helm-and-fragments-configmap.yaml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/helm/templates/helm-and-fragments-deployment.yaml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/helm/values.yaml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/resource/kubernetes.yml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/expected/resource/kubernetes/helm-and-fragments-deployment.yml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/pom.xml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/configmap.yaml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/deployment.yml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/first-template.yml
kubernetes-maven-plugin/it/src/it/helm-and-fragments/src/main/jkube/template.yml
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoTest.java
quickstarts/maven/spring-boot-helm/pom.xml

feat: helm Parameters/Variables/Values.yaml can be configured via XML/DSL
Instead of providing parameters via `Template` resource fragment, they can now be provided via pom.xml XML configuration or build.gadle DSL configuration.
The following configuration:
```xml
<helm>
<parameters>
<parameter>
<name>chart_name</name>
<value>{{ .Chart.Name }}</value>
</parameter>
</parameters>
</helm>
```
Can interpolate a resource fragment:
```yaml
metadata:
annotations:
chart/name: ${chart_name}
```
To produce a:
```yaml
apiVersion: v1
kind: #...
metadata:
annotations:
chart/name: {{ .Chart.Name }}
```
/cc @dloiacono

feat: helm Parameters/Variables/Values.yaml can be configured via XML/DSL

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClientTest.java

Fixes #1232 
This issue repeats the same issue from docker-maven-plugin and the proposed solution is identical - https://github.com/fabric8io/docker-maven-plugin/issues/838
The problem appears when someone wants to tag the image with "latest" version which already exists in the repo but pushing this new image should remove "latest" tag from an older image. This behavior is impossible to achieve without this fix.

Fix #1232: Remove check for existing temporary tag

---

quickstarts/maven/webapp-wildfly/pom.xml

When running the maven goal `mvn wildfly:run`, it was failing trying to
download a distribution of wildfly with the plugin version.
`wildfly.version` was overiden with the plugin version. This is renaming
the plugin version property to avoid the conflict.
Signed-off-by: Sun Seng David TAN <sutan@redhat.com>

fix(quickstart-webapp-wildfly): plugin version should not conflict with wildfly version

---

CHANGELOG.md
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandler.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerHTTPUrlTest.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ProbeHandlerTest.java

Fix #1126
Fix incorrect mutation of IntOrString port object. Just setting `intVal`
or `strVal` won't result in output serialized as integer or string
respectively. We need to set kind too.
Use constructor directly instead of setting values manually in both try
and catch block.

fix (jkube-kit) : Liveness and readiness TCP ports are not serialized as numbers when defined as numbers (#1126)

---

CHANGELOG.md
gradle-plugin/it/src/it/controller/build.gradle
gradle-plugin/it/src/it/controller/expected/daemonset/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/daemonset/openshift.yml
gradle-plugin/it/src/it/controller/expected/default/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/default/openshift.yml
gradle-plugin/it/src/it/controller/expected/deployment/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/deployment/openshift.yml
gradle-plugin/it/src/it/controller/expected/job/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/job/openshift.yml
gradle-plugin/it/src/it/controller/expected/replicaset/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/replicaset/openshift.yml
gradle-plugin/it/src/it/controller/expected/replicationcontroller/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/replicationcontroller/openshift.yml
gradle-plugin/it/src/it/controller/expected/statefulset/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/statefulset/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/DefaultControllerIT.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/KubernetesConfiguredControllerIT.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/OpenShiftConfiguredControllerIT.java
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/controller/_jkube_controller.adoc

Fix #1236 
+ Add integration test to verify default controller resources generated by openshift and kubernetes gradle plugin resource tasks
+ Add integration tests to verify configured controller resources are generated as expected by kubernetes and openshfit gradle plugin resource tasks
+ Refactor Asciidoc documentation about DefaultControllerEnricher for Gradle Plugin docs.

test (gradle-plugin) : Add integration test for DefaultControllerEnricher in gradle-plugin (#1236)

---

CHANGELOG.md
gradle-plugin/it/src/it/java-options-env-merge/build.gradle
gradle-plugin/it/src/it/java-options-env-merge/expected/kubernetes.yml
gradle-plugin/it/src/it/java-options-env-merge/expected/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/JavaOptionsEnvMergeIT.java
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/javacontainerenvoptions/_jkube_container_env_java_options.adoc

Fix #1211
- Port `java-options-env-merge` invoker test to `gradle-plugin` integration tests module
- documentation for ContainerEnvJavaOptionsMergeEnricher

test(gradle-plugin) : Port JavaOptionsEnvMergeIT to gradle (#1211)

---

CHANGELOG.md
gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
gradle-plugin/it/src/it/controller/expected/job/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/job/openshift.yml
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java
jkube-kit/enricher/api/pom.xml
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/DaemonSetHandler.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/DeploymentConfigHandler.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/DeploymentHandler.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/JobHandler.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandler.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ReplicaSetHandler.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ReplicationControllerHandler.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/StatefulSetHandler.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/JobHandlerTest.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java
jkube-kit/enricher/generic/pom.xml
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricherCreateTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc

Fix #1278
Right now JKube doesn't generate resources with pod spec's
`restartPolicy` set. This works for most of the controller type
resources (e.g `Deployment`, `StatefulSet`, `DaemonSet`, `ReplicaSet`,
`ReplicationController` ); If not provided Kubernetes assumes it to be
`Always`.
But in case of `Job` it doesn't work and Kubernetes gives `422`. Add a
default restart policy in case of `Job`.
[kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy)

fix (jkube-kit) : Add default restartPolicy in case of controller type Job (#1278)

---

CHANGELOG.md
gradle-plugin/it/src/it/service/build.gradle
gradle-plugin/it/src/it/service/expected/kubernetes.yml
gradle-plugin/it/src/it/service/expected/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ServiceIT.java
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/service/_jkube_service.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/service/gradle/_jkube_service_enricher_configuration.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/service/gradle/_jkube_service_enricher_port_example.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/service/maven/_jkube_service_enricher_configuration.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/service/maven/_jkube_service_enricher_port_example.adoc

Fix #1239 
+ Add gradle integration test to verify DefaultServiceEnricher works with Groovy DSL service configuration
+ JKube Service enricher now shows up in gradle plugin documentation.
Moved maven specifiec configuration blocks to separate files which would
show up only when plugin-type variable is maven. Added gradle equivalent
configuration blocks.

test (gradle-plugin/it) : Add gradle integration test for DefaultServiceEnricher (#1239)

---

gradle-plugin/doc/src/main/asciidoc/inc/_generator.adoc
gradle-plugin/doc/src/main/asciidoc/inc/generator/_webapp.adoc

Based on maven webapp generator doc
Preview: https://jkubedoc-sutan-jkube-doc-gradle-webapp.surge.sh/#generator-webapp

doc(gradle-plugin): Adding webapp generator doc

---

gradle-plugin/it/src/it/secret-file/build.gradle
gradle-plugin/it/src/it/secret-file/expected/kubernetes.yml
gradle-plugin/it/src/it/secret-file/expected/openshift.yml
gradle-plugin/it/src/it/secret-file/src/main/jkube/secret.yml
gradle-plugin/it/src/it/secret-file/src/test/resources/secret-application.properties
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/FileSecretIT.java
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/secret-file/_jkube_secret_file.adoc

Fix #1250 
+ Add Gradle integration test to verify `jkube.eclipse.org/secret`
metadata annotation generates correct secret with base64 content of specified
files
+ Minor change in FileDataSecretEnricher docs for Gradle plugins related
to name property. Move FileDataSecretEnricher doc out of maven only
enrichers docs block.

test (gradle-plugin/it) : Add Gradle Integration test for FileDataSecretEnricher (#1250)

---

quickstarts/gradle/webapp/README.md
quickstarts/gradle/webapp/build.gradle

Adding readme to the gradle webapp quickstart and example how to override webapp generator defaults with gradle DSL

chore(quickstarts): Adding readme to the gradle webapp quickstart and example how to override webapp generator defaults with gradle DSL

---

CHANGELOG.md
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTaskTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PodLogService.java

This issue solves 2 issues with the PodLogService.
- Logging for `Jobs` with no selector (it's an [optional](https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-selector) field), fallback to use a label selector based on the Pod Template metadata labels (if present)
- Logging for a specific Pod name works even if no selector is detected (in case it's detected it is still used to filter out multiple pods).
e.g. `mvn k8s:log -Djkube.log.pod=helper` would tail the logs of a Pod named `helper`

PodLogService fixes

---

CHANGELOG.md
gradle-plugin/it/src/it/spring-boot-with-fragment/build.gradle
gradle-plugin/it/src/it/spring-boot-with-fragment/expected/kubernetes.yml
gradle-plugin/it/src/it/spring-boot-with-fragment/expected/openshift.yml
gradle-plugin/it/src/it/spring-boot-with-fragment/src/main/java/org/eclipse/jkube/it/gradle/spring/boot/Application.java
gradle-plugin/it/src/it/spring-boot-with-fragment/src/main/jkube/deployment.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/SpringBootWithFragmentIT.java
gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/RevisionHistoryEnricher.java
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml

Fix #1295
Right now with DeploymentConfigBuilder, TypedVisitor<ContainerBuilder>
is visiting ContainerBuilder twice instead of visiting it once. This is
generating list with duplicate ContainerBuilder elements.
Move DeploymentConfigEnricher lower than Health Check enrichers in order
to do conversion after health checks have been added to Deployment.

fix : Spring Boot actuator endpoints don't generate if `deployment.yml` fragment is used (#1295)

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java

Quick fixing ocBuild when base image used with s2i differs the one used in docker build strategy
Following the discussion here https://github.com/eclipse/jkube/issues/1208#issuecomment-1062732066 

fix(gradle-plugin): gradle ocBuild should pick s2i build strategy by default

---

CHANGELOG.md
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/WebAppGeneratorTest.java
quickstarts/gradle/webapp-custom/build.gradle

Fix #1284
Only set cmd while building ImageConfiguration when inferred docker run command is not null. Right now we were building invalid Argument object with everything null which gets rejected later during `ConfigHelper.initAndValidate` call

fix : webapp custom generator should not require to set a CMD configuration (#1284)

---

.circleci/config.yml
CHANGELOG.md
scripts/generateDoc.sh

Fix #1251 
~Use surge.sh to generate preview documentation of pull requests. Preview URL would be of format `jkubedocs-pull-$PR_NUMBER-preview.surge.sh`~
Generate documentation in CircleCi workflow and then upload it as circleci build artifacts. This way we won't need any kind of service to host our temporary website pages.

chore : Generate a preview of jkube documentation for PR if needed (#1251)

---

CHANGELOG.md
gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/NameEnricherTest.java
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml

Fix #1325 
Change ordering of NameEnricher and modify it's logic to override name in
case of custom enricher configuration

fix : `jkube.enricher.jkube-name.name` doesn't modify `.metadata.name` for generated manifests (#1325)

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/port-name/_jkube_port_name.adoc

Fix #1261
Add documentation for PortNameEnricher which should be visible in case
of both maven and gradle plugins

doc (jkube-kit/doc) : Add documentation for PortNameEnricher (#1261)

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/replicacount/_jkube_replicacount.adoc

Fix #1297 
ReplicaCountEnricher Asciidoc should be available in both maven and gradle plugin docs.

doc : Add documentation for ReplicaCountEnricher (#1297)

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/deploymentconfig/_jkube_openshift_deploymentconfig.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/deploymentconfig/_jkube_openshift_deploymentconfig_entry.adoc

Fix #1308
Add asciidoc documentation for DeploymentConfigEnricher which should
show up in both maven and gradle plugin docs.

doc (jkube-kit/doc) : Add documentation for DeploymentConfigEnricher (#1308)

---

CHANGELOG.md
gradle-plugin/it/src/it/revisionhistory/build.gradle
gradle-plugin/it/src/it/revisionhistory/expected/configured/kubernetes.yml
gradle-plugin/it/src/it/revisionhistory/expected/configured/openshift.yml
gradle-plugin/it/src/it/revisionhistory/expected/default/kubernetes.yml
gradle-plugin/it/src/it/revisionhistory/expected/default/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/RevisionHistoryIT.java
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/revisionhistory/_jkube_revision_history.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/revisionhistory/gradle/_revisionhistory_groovy_configuration.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/revisionhistory/maven/_revisionhistory_xml_configuration.adoc

Fix #1298 
+ Add gradle integration test for verifying RevisionHistoryEnricher works
as expected in default mode and enricher configuration mode
+ Minor modifications in RevisionHistoryEnricher to make them available
via Gradle Plugin docs also.
Signed-off-by: Rohan Kumar <rohaan@redhat.com>## Description

test (gradle-plugin/it) : Add gradle integration test for RevisionHistoryEnricher (#1298)

---

CHANGELOG.md
gradle-plugin/it/src/it/autotls/build.gradle
gradle-plugin/it/src/it/autotls/expected/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/AutoTLSIT.java
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/autotls/_jkube_openshift_autotls.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/autotls/_jkube_openshift_autotls_entry.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/autotls/gradle/_jkube_enable_openshift_autotls.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/autotls/maven/_jkube_enable_openshift_autotls.adoc

Fix #1303
+ Add a gradle integration test for AutoTLSEnricher to verify annotation
and initContainers for TLS are added as expected.
+ Minor changes in AutoTLSEnricher docs for making them show up in gradle
plugin docs as well.
I tested by enabling AutoTLSEnricher in a project(similar to the integration test configuration) and generated manifests seem to be getting applied correctly on OpenShift cluster (CRC)

test (gradle-plugin/it) : Add gradle integration test for AutoTLSEnricher (#1303)

---

CHANGELOG.md
gradle-plugin/it/src/it/imagechangetrigger/build.gradle
gradle-plugin/it/src/it/imagechangetrigger/expected/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ImageChangeTriggerIT.java
jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/deploymentconfig/_jkube_openshift_deploymentconfig.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/imagechangetrigger/_jkube_openshift_imagechangetrigger.adoc
jkube-kit/doc/src/main/asciidoc/inc/enricher/imagechangetrigger/_jkube_openshift_imagechangetrigger_entry.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc

Fix #1310
+ Add a gradle integration test for verifying no ImageChangeTrigger gets
added to DeploymentConfig on setting `jkube.openshift.imageChangeTriggers` to `false`.
+ Move ImageChangeTriggerEnricher and DeploymentConfigEnricher related
properties to respective enricher documentation
+ Add documentation for ImageChangeTriggerEnricher

test (gradle-plugin/it) : Add gradle integration test for ImageChangeTriggerEnricher (#1310)

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/generator/_webapp.adoc
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/WebAppGeneratorTest.java
quickstarts/gradle/webapp-wildfly/README.md
quickstarts/gradle/webapp-wildfly/build.gradle
quickstarts/gradle/webapp-wildfly/gradle.properties

This is allowing passing env variable to the webapp gen build.
For instance, for a gradle wildfly webapp project
```
openshift {
generator {
config {
'webapp' {
env = "GALLEON_PROVISION_LAYERS=web-server,ejb-lite,jsf,jpa,h2-driver"
}
}
}
}
```
will pass the right `GALLEON_PROVISION_LAYERS` to the s2i build and generate the right layers.
This is part of https://github.com/eclipse/jkube/issues/1208
I also provided to this PR an update of the gradle webapp-wildfly quickstart with an example of how to have it working in openshift by injecting `GALLEON_PROVISION_LAYERS`.

feat(webapp-generator): env variables configuration

---

jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtilTest.java

GoTimeUtilTest : Use assertThat(actual).contains(expected) instead of fetching and comparing optional #1378 

GoTimeUtilTest : Use assertThat(actual).contains(expected) instead of fetching and comparing optional

---

kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-build.adoc

Fixes the names of the parameters openshiftPullSecret, openshiftPushSecret, buildOutputKind in the `oc:build` section of the openshift-maven-plugin documentation.
The names in the doc do not correspond by the name of the properties on the codebase that it is using them [OpenshiftBuildMojo.java](https://github.com/eclipse/jkube/blob/479858aa6719ffaabe8320c87ec43d129c78ffe6/openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftBuildMojo.java).

doc(maven-openshift): Fix openshift global parameter names in documentation for oc:build

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java
jkube-kit/build/api/src/test/resources/org/eclipse/jkube/kit/build/api/helper/Dockerfile_multi_stage_with_args

Fix #1382  
Port https://github.com/fabric8io/docker-maven-plugin/pull/1490 from
Docker Maven Plugin to JKube in order to fix build ARG resolution issue
while pulling images
I've tested with Dockerfile provided in the issue. This seems to fix the issue reported in #1382 

fix : Build ARGS not replaced properly (#1382)

---

gradle-plugin/doc/src/main/asciidoc/inc/_groovy-configuration.adoc
gradle-plugin/it/src/it/metadata/build.gradle
gradle-plugin/it/src/it/metadata/expected/openshift.yml
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/MetaDataConfig.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitorTest.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultMetadataEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultMetadataEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/goals/build/_jkube-resource.adoc

Allow the DefaultMetadataEnricher to define labels and annotations to the OpenShift Route objects from the Resource configuration.

Define metadata labels and annotations to Route objects 

---

CHANGELOG.md
gradle-plugin/it/src/it/project-label/expected/group/kubernetes.yml
gradle-plugin/it/src/it/project-label/expected/group/openshift.yml
gradle-plugin/it/src/it/project-label/expected/version/kubernetes.yml
gradle-plugin/it/src/it/project-label/expected/version/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ProjectLabelIT.java
jkube-kit/doc/src/main/asciidoc/inc/enricher/project-label/_jkube_project_label.adoc
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricherTest.java

Fix #1268
Add two new options to ProjectLabelEnricher configuration for allowing
user to customize `group` and `version` labels added to match selectors
by ProjectLabelEnricher

fix (jkube-kit) : ProjectLabelEnricher group and version labels should be configurable (#1268)

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricherTest.java

Fix #1194
ControllerViaPluginConfigurationEnricher should consider adding
configured name while merging resource fragment with opinionated
defaults.

fix (jkube-kit) : jkube controller configuration ignored when using fragments (#1194)

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/generator/_webapp.adoc
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/TomcatAppSeverHandler.java
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/WebAppGeneratorTest.java
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/handler/TomcatAppSeverHandlerTest.java
jkube-kit/parent/pom.xml

~~This is picking the right base image for tomcat if legacy javaee dependencies are used in the project~~
- by default, war file is copied to the compat/migrate directory webapps-javaee (regardless of its dependencies)
- if deployment directory is webapps-javaee, INFO message is printed indicating this and how to make the deployment faster if already jakartaee compliant, by setting the deployment folder to webapps.
- Users should be able to provide a custom configuration and rely on our Tomcat 9 image as a last resort workaround.
Fix https://github.com/eclipse/jkube/issues/1324
Depends on https://github.com/jkubeio/jkube-images/pull/15

fix(tomcat-webapp-generator): Support legacy javaee as well as jakartaee projects

---

CHANGELOG.md
gradle-plugin/doc/src/main/asciidoc/inc/getting-started/_groovy.adoc
gradle-plugin/it/src/it/probes-groovy-dsl-config/build.gradle
gradle-plugin/it/src/it/probes-groovy-dsl-config/expected/liveness-readiness/kubernetes.yml
gradle-plugin/it/src/it/probes-groovy-dsl-config/expected/liveness-readiness/openshift.yml
gradle-plugin/it/src/it/probes-groovy-dsl-config/expected/none/kubernetes.yml
gradle-plugin/it/src/it/probes-groovy-dsl-config/expected/none/openshift.yml
gradle-plugin/it/src/it/probes-groovy-dsl-config/expected/startup/kubernetes.yml
gradle-plugin/it/src/it/probes-groovy-dsl-config/expected/startup/openshift.yml
gradle-plugin/it/src/it/probes-groovy-dsl-config/src/main/java/org/eclipse/jkube/it/gradle/probes/groovy/dsl/probesgroovydslconfig/ProbesGroovyDSLConfigResource.java
gradle-plugin/it/src/it/probes-groovy-dsl-config/src/main/java/org/eclipse/jkube/it/gradle/probes/groovy/dsl/probesgroovydslconfig/ProbesGroovyDslConfigApplication.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ProbesGroovyDSLIT.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandler.java
jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricher.java
jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/AbstractHealthCheckEnricherTest.java
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc
kubernetes-maven-plugin/it/src/it/probes-xml-config/pom.xml

Fix #1322 
Add new startup probe field in resource configuration which should be
available in XML maven plugin configuration/ Groovy DSL configuration in
maven and gradle plugins respectively.

feat (jkube-kit/config) : Support for Startup Probes via XML/DSL configuration (#1322)

---

jkube-kit/enricher/api/pom.xml

Fix https://github.com/eclipse/jkube/issues/1480
Remove duplicate dependency `mockito-core` in `jkube-kit/enricher/api/pom.xml`.

Remove duplicate dependency in jkube-kit/enricher/api/pom.xml #1480

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTask.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionPropertyTest.java

fix: gradle push registry can be configured via property

fix: gradle push registry can be configured via property

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/generator/_options_common.adoc
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/generator/karaf/src/main/java/org/eclipse/jkube/generator/karaf/KarafGenerator.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java

Fix #1188
Right now there isn't a way to add tags to BuildConfiguration while
using zero config mode in generators. Adding a configuration field in
BaseGenerator which would expect comma separated tags which can be
picked up by Generator while building opinionated Image configuration

feat (jkube-kit/generator) : Add configuration option in BaseGenerator to add tags (#1188)

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtils.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileUtilsTest.java

Fix #1483
Normalize output directory returned by AssemblyFileUtils

fix (jkube-kit) : Assembly files with unnormalized paths don't get fileMode changes (#1483)

---

CHANGELOG.md
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java

Fix #1489
BaseGenerator `add` and `tags` options also available with
`jkube.generator.add` and `jkube.generator.tags` properties
respectively.

fix (jkube-kit/generator) : Align BaseGenerator's config options to work with `jkube.generator.*`  properties (#1489)

---

.circleci/config.yml
scripts/generateDoc.sh

doc-preview-pr CircleCI workflow seems to be intermittently failing
sometimes due to jkube-kit-parent pom not found in circleci maven cache.
Removing load cache step and adding a build without tests step in
generateDoc script.

ci : fix intermittent failures of doc-preview-pr CircleCI workflow

---

jkube-kit/parent/pom.xml
jkube-kit/watcher/standard/pom.xml

Closes #1249 
Remove `com.jayway.jsonpath:json-path` dependency which isn't used by
tests anymore. 

chore (jkube-kit) : Remove unused json-path-assert dependency

---

jkube-kit/jkube-kit-vertx/pom.xml
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxGeneratorTest.java
jkube-kit/jkube-kit-vertx/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
jkube-kit/parent/pom.xml

Infinispan dependency was only getting used in jkube-kit-vertx under
test scope only. We can easily work around this by mocking static method
as per our requirement

chore : Remove vertx-infinispan dependency from jkube-kit

---

CHANGELOG.md
gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass/openshift.yml
gradle-plugin/it/src/it/volume-permission/expected/default/openshift.yml
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NetworkingV1IngressGenerator.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/IngressEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java

fix: route doesn't use the service "normalizePort"

---

CHANGELOG.md
gradle-plugin/doc/src/main/asciidoc/inc/_introduction.adoc

fix #1512: gradle plugins are graduated

fix: gradle plugins are graduated

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/unix/UnixSocket.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/unix/UnixSocketTest.java
jkube-kit/build/service/docker/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
jkube-kit/parent/pom.xml

Fix #1470 
The `jnr-unixsocket` was updated to the latest version and added some fixes due to the breaking API changes in their code 

fix(kubernetes-maven-plugin): add Apple M1 CPU support

---

jkube-kit/parent/pom.xml
pom.xml

Fix #1469
KubernetesResourceUtilTest seems to be failing on non-english locale
systems due to an assertion which is verifying exception message in
english. This causes problems on systems where language is other than
english like in case of #1469

fix (jkube-kit/enricher) : Configure surefire to run tests in english locale (#1469)

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SemanticVersionUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SemanticVersionUtilTest.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusUtils.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusUtilsTest.java

`QuarkusUtils.isVersionAtLeast` seems to be generic semantic version
utility which can be used to check whether given framework's version is more than
a given version.
Once this gets merged, we can use this method in #1541 and #1492
Related to #1473 

refactor (jkube-kit) : Move `QuarkusUtils.isVersionAtLeast` to jkube-kit/common

---

gradle-plugin/it/pom.xml
gradle-plugin/pom.xml
jkube-kit/common-test/pom.xml
jkube-kit/common-test/src/main/java/org/eclipse/jkube/kit/common/ResourceVerify.java
jkube-kit/common-test/src/main/java/org/springframework/beans/factory/NoSuchBeanDefinitionException.java
jkube-kit/parent/pom.xml
kubernetes-maven-plugin/it/pom.xml
kubernetes-maven-plugin/pom.xml
openshift-maven-plugin/it/pom.xml
openshift-maven-plugin/pom.xml
pom.xml

Replaced citrus-core module with the more specific `citrus-validation-json` and `citrus-validation-hamcrest`, and bumped to version 3.2.1.
Bumped transitive dependency json-smart from 2.2.1 to 2.4.8 which fixes a critical vulnerability.
n.b. Citrus 3 requires Java 11, I modified the IT modules so that they run only if there's a valid JDK 11 (should be no problem because all of our test pipelines are running on Java 11).

deps: bump/refactor Citrus from 2.6.2 to 3.2.1

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_quarkus.adoc
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/QuarkusUtils.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricher.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusModeTest.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/QuarkusUtilsTest.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricherTest.java

feat (jkube-kit/quarkus): Add startup probe in QuarkusHealthCheckEnricher (#1468)

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/JKubeTarArchiver.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/JKubeTarArchiverTest.java

Fix #777
While fixing tarball issue in #793, we had added this
`tarEntry.setSize(0L)` in JKubeTarArchiver to fix tarball compatibility
with old docker daemons. However, it is set only when the file is not
present in `fileModeMap`.
In case of Dockerfile based builds, `fileModeMap` seems to contain file
modes for different files and directories. Hence, we're not able to set
TarEntry size to zero.
Move `tarEntry.setSize(0L)` out of fileMode related `if-else` block.

fix (jkube-kit) : JKubeTarArchiver should always set set TarEntry size to zero for directories (#777)

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java

Fixes #1537
OpenShiftBuildService doesn't consider registry in ImageConfiguration
while building image. This causes problems when BuildOutput kind is set
DockerImage and no registry name can be inferred from ImageName,
eventually causing authentication failure.
Add logic to append registry in ImageName before building image.

fix (jkube-kit/config/service) : OpenShiftBuildService doesn't consider registry in ImageConfiguration (#1532)

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/AbstractImageBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java
quickstarts/maven/ibm-javaee8-webprofile-liberty/pom.xml

- fix #1654 - ImageConfiguration with missing build configuration should not be built
- bump dependencies for javaee8-webprofile-liberty quickstart

fix: NPE when building images with missing build configuration

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtils.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java

Fix #1411
Add support for adding multiple ImageStreamTags specified in
`tags` section of image's `build` configuration. After S2I build new
ImageStreamTags as specified in build configuration would get created.
They would point to same image as done by orignal ImageStreamTag output
of S2I build.

feat (jkube-kit/config) : OpenShiftBuildService should also respect multiple tags specified in Image Build Configuration (#1411)

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java

Related to #1639 
For creating lists use `resourceList(...)` instead of VarArg
`createOrReplace(...)` method which has been removed from Fabric8
Kubernetes Client v6.0.0

chore (jkube-kit/config/service) : Fix build failure in OpenShiftBuildService

---

jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java

In #1657, assertThat("").isEqualTo("") was used in opposite way. Actual
value should be placed inside assertThat() block and isEqualTo should
contain expected value

chore (jkube-kit/generator) : Invert arguments while comparing elements using AssertJ in BaseGeneratorTest

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/helper/AutoPullMode.java

Making the fields in AutoPullMode file 'final'  for the issue #1784

Changing the fields of AutoPullMode .

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/CredentialHelperClient.java

Makes field in CredentialHelperClient 'final'
Fixes #1798 

Make field final

---

jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java

Fixes #1813
added the final keyword

added final keyword / [Hacktoberfest] ImageChangeTriggerEnricher fields may be 'final' /

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileOption.java

Added final in DockerFileOption.java

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/IoUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java

fixed non final variable code smell

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/AssemblyMode.java

Fix #1779 
Added final keyword in [AssemblyMode.java](https://github.com/eclipse/jkube/blob/e412b88a6f283787e9edc9aed75874d352c1571f/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/AssemblyMode.java) solving [this issue](https://github.com/eclipse/jkube/issues/1779).

added final keyword in AssemblyMode

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogRequestor.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/wait/LogMatchCallback.java

issue resolved by adding final keyword

---

jkube-kit/jkube-kit-vertx/pom.xml
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricherTest.java
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxGeneratorIsApplicableTest.java
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxGeneratorTest.java
jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxPortsExtractorTest.java

refactor (jkube-kit-vertx): Migrate all tests from JUnit4 to JUnit5 (#1572)

---

gradle-plugin/kubernetes/pom.xml
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GradleUtilTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/GroovyUtilTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/JKubePluginTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionPropertyTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginRegisterTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesBuildTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesConfigViewTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesDebugTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesUndeployTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskEnvironmentExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/TaskUtilTest.java

refactor (org.eclipse.jkube.kubernetes.gradle.plugin): Migrate tests from JUnit4 to JUnit5 (#1581)

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/chunked/EntityStreamReaderUtil.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/HcChunkedResponseHandlerWrapper.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/HcChunkedResponseHandlerWrapperTest.java

Fixes https://github.com/eclipse/jkube/issues/1684

fix(docker-build): failing container build with Podman should fail properly

---

CHANGELOG.md
gradle-plugin/it/src/it/groovy-dsl-image/build.gradle
gradle-plugin/it/src/it/groovy-dsl-image/expected/kubernetes.yml
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesExtension.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesExtensionTest.java

Adds a convenience method to the `KubernetesExtension` to allow adding images using a builder:
```groovy
kubernetes {
addImage {builder ->
builder.name = 'the name'
}
}
```
I was wondering if we would prefer something like the following snippet instead:
```groovy
kubernetes {
images {
imageBuilder()
.name('the-name')
.build(imageBuildBuilder()./*...*/build())
}
}
```
/cc @melix

feat(gradle): KubernetesExtension has helper method to add image with builder

---

CHANGELOG.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java
jkube-kit/watcher/standard/pom.xml
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/ExecListenerLatch.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/PodExecutor.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherRestartContainerTest.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherTest.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/ExecListenerLatchTest.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/PodExecutorTest.java
jkube-kit/watcher/standard/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Fixes #1704 #1606
+ Use Fabric8 Kubernetes Client Pod upload API to upload changed files
instead of manually copying via exec
+ With this fix all watch tests in JettyK8sWatchITCase were passing ( https://github.com/jkubeio/jkube-integration-tests/pull/187 )

fix (jkube-kit/watcher) : Fix DockerImageWatcher under copy mode (#1704)

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServicePortOrderTest.java

Fixes #1940
PortForwardServicePortOrderTest and DebugServiceTest both seem to be using port forward in their tests.
On Eclipse Jenkins, somehow PortForwardServicePortOrderTest's portforward doesn't seem to be getting closed even after test execution which seems to fail portforward in DebugServiceTest where port seems unavailable for local port forward.
I've tested this on https://ci.eclipse.org/jkube/job/downloads-eclipse-release-job/ by pointing this pipeline to my branch.
Once this PR and #1941 get merged, I can enable tests in the main release pipeline on Jenkins

fix (jkube-kit/config/service) : Close LocalPortForward in PortForwardServicePortOrderTest (#1940)

---

CHANGELOG.md
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_introduction.adoc

Fix old reference to `fmp` in documentation

doc: fix old reference to fmp 

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/IngressEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/IngressEnricherTest.java

Fixes #1439
Currently, value for IngressRule's `.host` field depends either on `HOST` enricher configuration or `jkube.domain` configuration. If none of these options are provided, we set `.spec.defaultBackend`.
+ Add a hint to suggest specifying `jkube.domain` in case no value for host is found.
This hint will appear if user forgets to specify host via XML/Groovy DSL configuration or `jkube.domain`/`jkube.enricher.jkube-ingress.host` properties. IngressEnricher doesn't do anything when an Ingress fragment is provided. I'm not sure whether we should check fragment too.

fix (jkube-kit/enricher) : Add hint for using `jkube.domain` if `createExternalUrls` is used without domain (#1439)

---

jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricherTest.java
jkube-kit/resource/service/src/test/java/org/eclipse/jkube/kit/resource/service/WriteUtilTest.java
pom.xml

deps: bump kubernetes-client to 6.4.0
This PR includes changes to the `ClusterAccessTest`. The Kubernetes Mock server as become more stable and performant over the last couple of years. Being able to test `ClusterAccess `against a semi-real cluster is easier to maintain than relying on Mocks that need extra-maintenance. In this case, the Client is slowly moving to abstract away explicit KubernetesClient implementations and moving on to SPI provided and more generic ones instead.

deps: bump kubernetes-client to 6.4.0

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServicePortOrderTest.java

Fixes #2030
Move CompletableFuture assertion within try with resources block to ensure that LocalPortForward closes after CompletableFuture is satisfied.

test : Fix flaky PortForwardServicePortOrderTest (#2030)

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/wait/LogMatchCallback.java

'final' added to 'LogMatchCallBack' field

---

CHANGELOG.md
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/TestHttpStaticServer.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/LocalService.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/LocalServiceManager.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/PortForwarder.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/RemoteDevelopmentConfig.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/RemoteDevelopmentContext.java
jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/LocalServiceManagerTest.java
jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/PortForwarderTest.java
jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/SshServerExtension.java

Several enhancements to JKube Remote Dev:
- Autodiscovery of ports for local services exposed in the cluster
- SOCKS 5 proxy

Misc Remote Dev enhancements

---

jkube-kit/doc/src/main/asciidoc/inc/resource-generation/_controller_resource_generation.adoc

Most fields in this table are deprecated and cause confusion. It's better to remove these so that users don't get confused by them and use new configuration methods.
Fixes #2057

doc (jkube-kit/doc) : Remove deprecated fields from Controller Configuration table (#2057)

---

quickstarts/gradle/openliberty-with-legacy-plugin-syntax/build.gradle

fix(quickstarts): wrong syntax in quickstart buildscript dependency

fix(quickstarts): wrong syntax in quickstart buildscript dependency

---

CHANGELOG.md
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarder.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/LocalService.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/LocalServiceManager.java
jkube-kit/remote-dev/src/main/java/org/eclipse/jkube/kit/remotedev/RemoteDevelopmentContext.java
jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/KubernetesSshServiceForwarderTest.java
jkube-kit/remote-dev/src/test/java/org/eclipse/jkube/kit/remotedev/LocalServiceManagerTest.java

fix: create remote dev session id and reuse it

---

CHANGELOG.md
jkube-kit/build/service/docker/pom.xml
jkube-kit/parent/pom.xml

- bump BouncyCastle to 1.72
- use BouncyCastle JDK 1.8 compatible jars

Bump BouncyCastle dependencies

---

gradle-plugin/it/src/it/controller/build.gradle
gradle-plugin/it/src/it/controller/expected/cronjob/kubernetes.yml
gradle-plugin/it/src/it/controller/expected/cronjob/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/KubernetesConfiguredControllerIT.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/OpenShiftConfiguredControllerIT.java

#2012 / #1954 follow-up
Added Gradle integration tests for the CronJob controller

test (gradle-plugin/it): Add Gradle integration test for CronJob

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java

Fixes a chore remaining from #1279
As noted by @manusa  and @rohanKanojia, In the past we had fabric8.mode in Fabric8 Maven Plugin which used to work both on Kubernetes and OpenShift. Now we've specific plugins, so we should not specify Kubernetes/Openshift mode in log messages. 

removed redundant message specifying plugin mode

---

CHANGELOG.md
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftApplyTaskTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftUndeployTaskTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/OpenshiftHelper.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/OpenshiftHelperTest.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/access/ClusterAccess.java
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubTest.java
openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftUndeployMojoTest.java
pom.xml

Fix #1950 
Fix #2000
Bump Kubernetes Client to 6.6.0 (fixes issues when trace-logging OpenShift builds)

deps: fix: bump Kubernetes Client to 6.6.0 (fixes issues when trace-logging OpenShift builds)

---

jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherContext.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/DockerImageWatcher.java
jkube-kit/watcher/standard/src/main/java/org/eclipse/jkube/watcher/standard/PodExecutor.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherRestartContainerTest.java
jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/PodExecutorTest.java

Fix #2153 
fix: PodExecutor uses KubernetesClient singleton from JKubeServiceHub

fix: PodExecutor uses KubernetesClient singleton from JKubeServiceHub

---

CHANGELOG.md
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/access/ClusterAccess.java
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
pom.xml

deps: bump Kubernetes Client to 6.6.2

deps: bump Kubernetes Client to 6.6.2

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesApplyTask.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/access/ClusterAccess.java
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/access/ClusterAccessTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/ApplyServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesUndeployServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftUndeployServiceTest.java
jkube-kit/watcher/api/src/main/java/org/eclipse/jkube/watcher/api/WatcherManager.java
jkube-kit/watcher/api/src/test/java/org/eclipse/jkube/watcher/api/WatcherManagerTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java
quickstarts/kit/docker-image/pom.xml
quickstarts/kit/docker-image/src/main/java/org/eclipse/jkube/quickstart/kit/docker/Main.java
quickstarts/kit/dynamic-docker-image-file-multi-layer/pom.xml
quickstarts/kit/dynamic-docker-image-file-multi-layer/src/main/java/org/eclipse/jkube/quickstart/kit/docker/dynamic/DynamicDockerfileGenerator.java
quickstarts/kit/helm/src/main/java/org/eclipse/jkube/quickstart/kit/Main.java

Fix #2155 
refactor: removes redundant ClusterAccess.isOpenShift method

refactor: removes redundant ClusterAccess.isOpenShift method

---

gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/build.gradle
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/expected/fragment-overriding-serviceaccount/kubernetes.yml
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/expected/fragment-overriding-serviceaccount/openshift.yml
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/expected/no-fragment/kubernetes.yml
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/expected/no-fragment/openshift.yml
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/expected/unrelated-fragment/kubernetes.yml
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/expected/unrelated-fragment/openshift.yml
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/overridingServiceAccountNameFragmentDir/deployment.yml
gradle-plugin/it/src/it/serviceaccountname-via-groovy-dsl/regularFragmentDir/deployment.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ServiceAccountNameViaGroovyDSLIT.java

Test case covering #2187 
Failing cases have been commented. I'll remove comment in #1889 

test (gradle-plugin/it) : Add test for setting ServiceAccount name in generated controller (#2187)

---

jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java

fix: Helm OpenShift Templates can be loaded from yaml extensions

fix: Helm OpenShift Templates can be loaded from yaml extensions

---

CHANGELOG.md
quickstarts/maven/spring-boot-crd/src/main/java/org/eclipse/jkube/quickstart/springboot/crd/Application.java
quickstarts/maven/spring-boot-crd/src/main/java/org/eclipse/jkube/quickstart/springboot/crd/FrameworkResource.java

Fix #1985 
Spring Boot CRD seems to be broken. It seems to be inheriting kubernetes-client from jkube but it's using outdated `customResource` raw api calls.
Update it to use `genericKubernetesResource()` DSL call instead.

chore (quickstarts/maven/spring-boot-crd) : Update outdated methods in Spring Boot CRD (#1985)

---

quickstarts/gradle/spring-boot-crd/build.gradle
quickstarts/gradle/spring-boot-crd/src/main/java/org/eclipse/jkube/quickstart/gradle/springboot/crd/springbootcrd/Application.java

Align both maven and gradle quickstarts to follow the same approach of inheriting transitive KubernetesClient dependency from Eclipse JKube
Related to #1985 

chore (quickstarts/gradle/spring-boot-crd) : Spring Boot CRD Gradle quickstart should use KubernetesClient from Eclipse JKube

---

gradle-plugin/it/src/it/helidon/build.gradle
gradle-plugin/it/src/it/helidon/expected/kubernetes.yml
gradle-plugin/it/src/it/helidon/expected/openshift.yml
gradle-plugin/it/src/it/helidon/src/main/java/org/eclipse/jkube/it/gradle/helidon/GreetResource.java
gradle-plugin/it/src/it/helidon/src/main/java/org/eclipse/jkube/it/gradle/helidon/GreetingProvider.java
gradle-plugin/it/src/it/helidon/src/main/resources/META-INF/beans.xml
gradle-plugin/it/src/it/helidon/src/main/resources/META-INF/microprofile-config.properties
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/HelidonIT.java

+ Add integration test for Helidon health checks in generated manifests

test (gradle-plugin/it) : Add integration test for Helidon health checks resource generation

---

jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/ResourceConfigTest.java
jkube-kit/config/resource/src/test/resources/resource-config.json

fix: remove unused ResourceConfig.customResourceDefinitions field

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/RegistryUtil.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/RegistryUtilTest.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RegistryService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameFullNameParseTest.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceGetApplicableRegistryTest.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricher.java
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java

Fix #2116
Closes #2011
Relates to:
- #523 
- #543
- #2011
Earlier we split image names before tagging into `registry`, `user` and `repository`. In Docker code, there is no mention of this user attribute. Split image name into `registry` and `repository` only. User can be extracted from `repository` if required. This would mean that in some cases(`foo.bar/name:tag`) path element would be considered as registry, added a case in getNameWithoutTag to consider optionalRegistry as registry.
+ Remove user field from ImageName class
- In Docker reference package, there is no mention of user field. A valid
repository is split into a domain and path component. Remove this user
field, but keep getUser method which will try to extract possible
username from path component (repository).
- Add …

fix (jkube-kit/config/image) : Remove user field from ImageName (#2116)

---

CHANGELOG.md
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandler.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ConfigMapEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ImageEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ServiceAccountEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ConfigMapEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/FileDataSecretEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/PortNameEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricherTest.java
jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java
jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/enricher/WildflyJARHealthCheckEnricherTest.java
pom.xml

deps: bump Kubernetes Client to 6.8.0

deps: bump Kubernetes Client to 6.8.0

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ExternalCommand.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ExternalCommandTest.java

Related to #1674
While executing a command, add a workDir configuration option to execute the command in a directory other than the current directory.
This will be used in Spring Boot layered generator when we want to extract layers in the build output directory rather than the project's base directory.

feat (jkube-kit/common) : Add workDir configuration option in ExternalCommand

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/task.yml
.github/pull_request_template.md
CONTRIBUTING.md
MIGRATION-GUIDE.md
README.md
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java
jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
kubernetes-maven-plugin/README.md
openshift-maven-plugin/README.md
quickstarts/maven/ibm-javaee8-webprofile-liberty/README.md
scripts/changelog.sh

Fix #2148
fix: project website url is now based on eclipse.dev/jkube
Moved from eclipse.org/jkube
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3069

fix: project website url is now based on eclipse.dev/jkube

---

CHANGELOG.md
jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java

Fix #2293
We are doing separate push requests for each additional tag provided in build configuration. Use only single push request and rely on inbuilt jib's Containerizer.withAdditionalTag method.
Instead of iterating of tags provided in the build configuration, pass them over to jib's core withAdditionalTag method while preparing Containerizer for push request.

fix (jkube-kit/build/service/jib) : JibServiceUtil should push additional tags in single request (#2293)

---

gradle-plugin/it/src/it/quarkus-properties/build.gradle
gradle-plugin/it/src/it/quarkus-properties/expected/kubernetes.yml
gradle-plugin/it/src/it/quarkus-properties/expected/openshift.yml
gradle-plugin/it/src/it/quarkus-properties/gradle.properties
gradle-plugin/it/src/it/quarkus-properties/src/main/resources/application.properties
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/QuarkusPropertiesIT.java
jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricher.java
jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricherTest.java

Fixes #2239 
k8s:resource doesn't automatically pick up port from Quarkus application.properties

Fix: #2239 Quarkus k8s:resource automatic port pick up from application.properties

---

.gitpod.yml
CHANGELOG.md
README.md

Fixes #1946 
To get a preview of this click [here](https://gitpod.io/#github.com/anurag-rajawat/jkube/tree/gitpod)

Initial support for Gitpod (#1946)

---

gradle-plugin/it/src/it/service-name/build.gradle
gradle-plugin/it/src/it/service-name/expected/kubernetes.yml
gradle-plugin/it/src/it/service-name/expected/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ControllerIT.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ServiceNameIT.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/GroupArtifactVersion.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandler.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NameEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/DeploymentConfigEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ImageChangeTriggerEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/NameEnricherTest.java
jkube-kit/resource/service/src/main/java/org/eclipse/jkube/kit/resource/service/DefaultResourceService.java

Relates to #2350 
Some tests to verify current behavior
Further tests and fix will follow in subsequent PRs

test: prior tests to ensure name fixes

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceBuildIntegrationTest.java

fix: docker pull rate limit in tests

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm.adoc
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmDependency.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmDependencyTest.java

Adds `condition`, and `alias` properties to the `HelmDependency`. For more information on `condition` see [here](https://helm.sh/docs/topics/charts/#tags-and-condition-fields-in-dependencies), and [here](https://helm.sh/docs/topics/charts/#alias-field-in-dependencies) for `alias`.

feat (jkube-kit/resource) : Adds condition to HelmDependency

---

CHANGELOG.md
gradle-plugin/it/src/it/controller-name-fragment/build.gradle
gradle-plugin/it/src/it/controller-name-fragment/expected/kubernetes.yml
gradle-plugin/it/src/it/controller-name-fragment/expected/openshift.yml
gradle-plugin/it/src/it/controller-name-fragment/src/main/jkube/deployment.yml
gradle-plugin/it/src/it/service-name-fragment/build.gradle
gradle-plugin/it/src/it/service-name-fragment/expected/kubernetes.yml
gradle-plugin/it/src/it/service-name-fragment/expected/openshift.yml
gradle-plugin/it/src/it/service-name-fragment/src/main/jkube/service.yaml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ControllerNameAndFragmentIT.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ServiceNameAndFragmentIT.java
jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/GroupArtifactVersion.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceFragments.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceFragmentsTest.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DependencyEnricherTest.java
jkube-kit/resource/service/src/main/java/org/eclipse/jkube/kit/resource/service/DefaultResourceService.java

Fix #2350
Fragments are no longer initiated with a default name (was never necessary).
Either the `jkube-name` enricher or any of the other enrichers that merge opinionated defaults with the provided fragments (service, controller) will take care of providing a default metadata.name for the fragment in case it doesn't have one.

fix: enrichers with NAME configuration override fragments with default names

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SpringBootUtilTest.java
jkube-kit/jkube-kit-spring-boot/pom.xml
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/AbstractSpringBootNestedGenerator.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/LayeredJarGenerator.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/NativeGenerator.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootNestedGenerator.java
jkube-kit/jkube-kit-spring-boot/src/main/resources-filtered/META-INF/jkube/default-images.properties
jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/generator/SpringBootGeneratorIntegrationTest.java
jkube-kit/parent/pom.xml

Fixes #2138
+ Add NativeGenerator to to jkube-kit/jkube-kit-spring-boot module
+ NativeGenerator would be activated when there is graalvm native plugin present in project and there is a native artifact present in project build directory or `native/nativeCompile` directory (for gradle)
- right now we'll trigger native generator when native plugin is present and any kind of executable file is present in `target` or `build/native/nativeCompile` directory, if there is more than one native executable present; we throw exception

feat (jkube-kit/jkube-kit-spring-boot) : Support for Spring Native (#2138)

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java

+ Sort all fields in BuildConfiguration class by applicable build strategies.
+ Fields that are applicable to any build strategy are listed first; Then Docker specific buildstrategy fields are listed.
+ Add additional comment specifying whether a particular field is applicable to some specific build strategy or can be used in any build strategy

refactor (jkube-kit/config) : Sort BuildConfiguration fields by buildstrategy

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm.adoc
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmParameter.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmConfigTest.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/templates/kubernetes.yaml
jkube-kit/resource/helm/src/test/resources/it/expected/kubernetes/values.yaml
jkube-kit/resource/helm/src/test/resources/it/expected/openshift/templates/openshift.yaml
jkube-kit/resource/helm/src/test/resources/it/expected/openshift/templates/test-pod.yaml
jkube-kit/resource/helm/src/test/resources/it/expected/openshift/values.yaml
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojoTest.java

Adds preserveParameterCase to HelmConfig to allow opting in to preserve HelmParameter case in Values.yaml.
Adds apiVersion to HelmConfig to allow specifying chart schema version.
Fixes #2356 

feat (jkube-kit/resource) : Add toggle to preserve HelmParameter case

---

jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmParameter.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmConfigTest.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceIT.java

refactor: don't require an OpenShift Template:Parameter model type

refactor: don't require an OpenShift Template:Parameter model type

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/FileUtilTest.java

We don't seem to be preserving lastModified timestamps of files that are being copied while preparing the assembly for image. Make sure we're copying all the metadata of files/directories as well while copying them.

fix (jkube-kit) : lastModified timestamps should be preserved while preparing assembly

---

CHANGELOG.md
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorTest.java

Fixes #2393
We add `org.label-schema.build-date` LABEL to image while creating opinionated container images. This causes Dockerfile to be different for every build and it doesn't utilize Docker cache properly. It causes the following layers to always be rebuild without using cache.
:heavy_check_mark: `FROM quay.io/jkube/jkube-java:0.0.19`
:heavy_check_mark:  `ENV JAVA_MAIN_CLASS=org.springframework.boot.loader.JarLauncher JAVA_APP_DIR=/deployments`
:x: `LABEL org.label-schema.build-date=2023-09-27T22:11:40.590328158` 
:x: `EXPOSE 8080 8778 9779`
:x: `COPY /dependencies/deployments /deployments/`
:x: `COPY /spring-boot-loader/deployments /deployments/`
:x: `COPY /application/deployments /deployments/`
:x: `WORKDIR /deployments`
:x: `ENTRYPOINT …

fix (jkube-kit/generator) : Do not add build timestamp to `org.label-schema.build-date` LABEL to better utilize docker cache (#2393)

---

jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java

feat: Helm default config values computed lazily

feat: Helm default config values computed lazily

---

CHANGELOG.md
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtension.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftBuildTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftExtensionPropertyTest.java

Fixes #2414
Add getOpenshiftPushSecretOrDefault method in OpenShiftExtension to pick up configuration value from property if it's not provided in groovy dsl

fix (gradle-plugin) : OpenShiftExtension should pick up `jkube.build.pushSecret` property (#2414)

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java

Fix #2379 
Preserve Assembly Image Layers for Non-S2I Builds

fix (jkube-kit/config/service) : Preserve Assembly Image Layers for Non-S2I Builds (#2379)

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtil.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/okhttp/BufferStringReader.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/okhttp/HttpHeaders.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/Fabric8HttpUtilTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/okhttp/BufferStringReaderTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/okhttp/HttpHeadersTest.java
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptor.java

Fixes #2419
We try to add push scope to scope field extracted from Www-Authenticate header if it doesn't already exist. This was happening because our `www-authenticate` header parsing logic was flawed and it was omitting `push` scope from `pull,push` scope. We were directly splitting whole string based on commas.
Port OkHttp's [HttpHeaders.parseChallengeHeader](https://github.com/square/okhttp/blob/parent-3.14.9/okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.java#L180) method into our codebase for achieving this. We have runtime dependency on OkHttp, a transitive dependency coming from Fabric8 Kubernetes Client. We needed only `parseChallengeHeader` method for parsing WWW-Authenticate header for fetching authentication challenges. It seemed a better option to port the required …

fix (jkube-kit) : Fix `Fabric8HttpUtil.extractAuthenticationChallengeIntoMap` www-authenticate header parsing logic (#2419)

---

scripts/jrelease.java

Update release script to include the crucial step of sending an email to the mailing list during the release process.

chore(release-script): Include the step for sending announcement emails to both public and private mailing lists

---

jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/SpringBootDevtoolsUtils.java
jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/SpringBootDevtoolsUtilsTest.java

I noticed this while testing buildpacks PR with `k8s:watch`
JKube seems to be throwing an exception while running `k8s:watch` when a Spring Boot project doesn't contain the `spring.devtools.remote.secret` in project.
```
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.16-SNAPSHOT:watch (default-cli) on project spring-boot3-demo-jkube: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.16-SNAPSHOT:watch failed: Failure in creating directory /home/rokumar/work/repos/jkube-buildpacks-poc-testing/maven-it/target/classes 
```
Problem seems to lie in the SpringBootDevtoolsUtils directory creation check:
https://github.com/eclipse/jkube/blob/d4d41587236da6f8c1dccc3754e8ebac539a22ba/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/sp …

fix (jkube-kit-spring-boot) : fix create dir check in SpringBootDevtoolsUtils

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/TestHttpStaticServer.java

`IoUtil.getFreeRandomPort` seems to be returning already allocated port values ( see https://github.com/eclipse/jkube/issues/2501)
InetSocketAddress can automatically generate a port on it's own if we pass `0` as port value. See [InetSocketAddress javadocs](https://docs.oracle.com/javase/8/docs/api/java/net/InetSocketAddress.html#InetSocketAddress-int-).

fix (jkube-kit/common): Don't use IoUtil.getFreeRandomPort for TestHttpStaticServer

---

CHANGELOG.md
jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm.adoc
jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
jkube-kit/resource/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java

Fix #2391 
Detect if `values.schema.json` file is present in the project base directory and add it if it is present.

feat (jkube-kit/resource/helm) : Automatically add `values.schema.json` file if detected

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/RegistryConfigTest.java

Fixes #2529
Removes deprecated method usage. Test case succeeds after the change.

test(jkube-kit): fixed deprecated method usage

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PodLogServiceTest.java

test: functional tests for PodLogService
These tests will serve as the base to allow for a refactoring of the Pod Log service.

test: functional tests for PodLogService

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/AsyncUtil.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PodLogService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java

refactor: KubernetesHelper.printLogsAsync reused common tools

refactor: KubernetesHelper.printLogsAsync reused common tools

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/AsyncUtil.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PodLogService.java

PodLogService uses an instance variable to keep state derived from a method that can be invoked multiple times and breaking the functionality.
This change (first of a series) moves to use a local variable instead.

refactor: temporary usage of local CompletableFuture

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamServiceTest.java

Related to #2531 #2547
+ Make retries and retry timeout configurable via new constructor
+ Add tests covering functionality for finding latest tag SHA in ImageStreamStatus received from OpenShift Api server.
+ Minor changes in old tests to use Kubernetes MockServer instead of mockito to mock OpenShiftClient

test (jkube-kit/config/service) : Add more tests for `ImageStreamService.findTagSha`

---

CHANGELOG.md
jkube-kit/parent/pom.xml
pom.xml

chore(deps): Bump version.kubernetes-client from 6.9.2 to 6.10.0

chore(deps): Bump version.kubernetes-client from 6.9.2 to 6.10.0

---

jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/GitEnricherTest.java

+ Add tests for GitEnricher covering all resources
+ Add test for edge cases (failure in reading `.git` attributes, `git-remote` etc)
Related to #2500

test (jkube-kit/enricher) : Add more tests for GitEnricher

---

gradle-plugin/it/src/it/expose/expected/ftp-port-expose-annotation-enricher/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/ftp-port-expose-annotation-enricher/openshift.yml
gradle-plugin/it/src/it/expose/expected/ftp-port-expose-annotation/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/ftp-port-expose-annotation/openshift.yml
gradle-plugin/it/src/it/expose/expected/ftp-port-external/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/ftp-port-external/openshift.yml
gradle-plugin/it/src/it/expose/expected/ftp-port/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/ftp-port/openshift.yml
gradle-plugin/it/src/it/expose/expected/http-port-external/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/http-port-external/openshift.yml
gradle-plugin/it/src/it/expose/expected/http-port/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/http-port/openshift.yml
gradle-plugin/it/src/it/expose/expected/multiple-services/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/multiple-services/openshift.yml
gradle-plugin/it/src/it/expose/expected/no-ports/kubernetes.yml
gradle-plugin/it/src/it/expose/expected/no-ports/openshift.yml
gradle-plugin/kubernetes/src/main/resources/META-INF/jkube/profiles-default.yml
gradle-plugin/openshift/src/main/resources/META-INF/jkube/profiles-default.yml
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/AbstractLabelEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/WellKnownLabelsEnricher.java
jkube-kit/enricher/generic/src/main/resources/META-INF/jkube/enricher-default
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/WellKnownLabelsEnricherTest.java
kubernetes-maven-plugin/it/src/it/dependency-resources/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/fragments/expected/kubernetes.yml
kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml
openshift-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml

Related to #1700
+ Extract ProjectLabelEnricher functionality into a new abstract enricher `AbstractLabelEnricher`
+ Add WellKnownLabelEnricher that would add these labels to `.metadata` of all resources (also to `selector.matchLabels` in case of controller resources):
- `app.kubernetes.io/component`
- `app.kubernetes.io/managed-by`
- `app.kubernetes.io/name`
- `app.kubernetes.io/part-of`
- `app.kubernetes.io/version`
+ add `app.kubernetes.io/` labels to integration tests that do strict checks.

feat (jkube-kit/enricher) : Add WellKnownLabelsEnricher for adding Kubernetes Recommended Well Known Labels

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/GitEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/GitEnricherTest.java
kubernetes-maven-plugin/it/src/it/dependency-resources/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/fragments/expected/kubernetes.yml

Related to #2500 
GitEnricher should be executed in `enrich` phase so that it's invoked during OpenShift build.
+ Move GitEnricher execution logic into `enrich` from `create` method
+ Update GitEnricherTest to use updated method
+ Update GitEnricherTest parameterized test to use the parameter instead of using value from global `@BeforeEach`
+ Add `BuildConfig`, `ImageStream`, `Secret` resources to parameterized method source
+ Update integration tests with git annotations that do a strict comparison

fix (jkube-kit/enricher) : GitEnricher should implement `enrich` instead of `create`

---

jkube-kit/build/service/buildpacks/src/test/java/org/eclipse/jkube/kit/service/buildpacks/AbstractBuildPackCliDownloaderTest.java

Follow up to https://github.com/eclipse/jkube/pull/2495
Update TestHttpStaticServer used in tests to be initialized only once, holding both valid and invalid upload directories. Only change the download url properties in setup methods where needed.

test (jkube-kit/build/service/buildpacks) : Refactor AbstractBuildPackCliDownloaderTest to initialize server only once

---

CHANGELOG.md
gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass-annotation/kubernetes.yml
gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass-annotation/openshift.yml
gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass/kubernetes.yml
gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass/openshift.yml
gradle-plugin/it/src/it/volume-permission/expected/default/kubernetes.yml
gradle-plugin/it/src/it/volume-permission/expected/default/openshift.yml
jkube-kit/doc/src/main/asciidoc/inc/enricher/volume-permission/_jkube_volume_permission.adoc
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricherTest.java
kubernetes-maven-plugin/it/src/it/deployment-strategy-type-919/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/volume-enricher-custom-storage-class/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/volume-enricher-default-storage-class/expected/kubernetes.yml

Related to #2423
Update VolumePermissionEnricher imageName config's default value to`quay.io/quay/busybox` to avoid Docker Hub rate limiting issues.
+ Update VolumePermissionEnricher `imageName` field's default value to `quay.io/quay/busybox`
+ Add tests in VolumePermissionTest for overriding `imageName` and when volume mounts in container do not match the PersistentVolumeClaim
+ Remove redundant test case in VolumePermissionTest.adapt it was doing the same thing as parameterized test case above it.

fix (jkube-kit/enricher) : Change default initContainer image from `busybox` to `quay.io/quay/busybox`

---

jkube-kit/build/service/buildpacks/pom.xml
jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackBuildOptions.java
jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/controller/BuildPackCliController.java
jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/controller/BuildPackController.java
jkube-kit/build/service/buildpacks/src/test/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackCliControllerTest.java

feat (jkube-kit/build/service/buildpacks) : Add BuildPackCliController (#2453)

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameDistributionReferenceTest.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameTest.java

ImageName throws exception when image repository name length is greater than 255
Fixes #2542

 Add check for image name length to not exceed 255

---

jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java

Fixes #2580 
Fixed 'null' check before 'equals()' call #2580 

KubernetesResourceUtil.ensureHasPort unnecessary 'null' check before 'equals()' call #2580

---

gradle-plugin/it/src/it/well-known-labels/build.gradle
gradle-plugin/it/src/it/well-known-labels/expected/labelsViaResourceConfig/kubernetes.yml
gradle-plugin/it/src/it/well-known-labels/expected/labelsViaResourceConfig/openshift.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/WellKnownLabelsIT.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/AbstractLabelEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/WellKnownLabelsEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricherTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/WellKnownLabelsEnricherTest.java

Fix #1700 
While adding labels and selectors to a resource, WellKnownLabelEnricher and ProjectLabelEnricher would give precedence to label configured via resource label XML/Groovy DSL configuration.
This precedence would depend on the type of resource label configuration used. If `all` has been provided in configuration, this means precedence would be given for all resources. However, if some specific resource label configuration is used; precedence would only be given for that specific resource
+ Added another argument `Map<String, String> labelsViaResourceConfig` in AbstractLabelEnricher.createLabels to accommodate labels configured via resource configuration. `labelsViaResourceConfig` would override default opinionated or enricher configuration settings.
+ While invoking …

fix (jkube-kit/enricher) : WellKnownLabelEnricher also considers labels added via resource configuration

---

jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackCliDownloader.java
jkube-kit/build/service/buildpacks/src/test/java/org/eclipse/jkube/kit/service/buildpacks/AbstractBuildPackCliDownloaderTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/PropertiesUtil.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/JKubeBuildStrategy.java
jkube-kit/config/service/pom.xml
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildService.java
jkube-kit/config/service/src/main/resources/META-INF/jkube/build-service
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildServiceTest.java
jkube-kit/parent/pom.xml

Related to https://github.com/eclipse/jkube/issues/2465
Fixes #2493
+ Add new build strategy called `buildpacks` as new enum for buildpacks in JKubeBuildStrategy
+ Add BuildPackBuildService that would be activated when build strategy
is set to buildpacks

feat (jkube-kit/config/service) : Add BuildPackBuildService (#2493)

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildServiceTest.java

Fixes #2464
Delegate push image to RegistryService like we do in DockerBuildService

fix (jkube-kit/config) : `k8s:push` / `k8sPush` should work with `buildpacks` build strategy (#2464)

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameDistributionReferenceTest.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageNameORASReferenceTest.java

Fixes #2541 
1.added IPv6 address support
2.uncommented the related tests
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
- [ X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
- [X ] My code follows the style guidelines of this project
- [X ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [X ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ X] I have performed a self-review of my code
- [ X] No new bugs, code smells, etc. in …

ImageName should be able to parse image names with IPv6 address literals

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/IoUtil.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java

Fixes #2501 
+ Use ServerSocket to establish a connection instead of Socket which might also throw ConnectException for a socket already in use.
+ Modify IoUtilTes.findOpenPortWithSmallAttemptsCount to use `@RepeatedTest` annotation to run it 500 times

refactor (jkube-kit/common) : Refactor `IoUtil.getFreeRandomPort` to always generate a valid free random port (#2501)

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesConfigViewTaskTest.java

Remove IOException from setUp method in KubernetesConfigViewTaskTest
Fixes #2633

Remove IOException from setUp method in KubernetesConfigViewTaskTest #2633

---

jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm.adoc
jkube-kit/doc/src/main/asciidoc/inc/helm/_jkube_helm_push.adoc
kubernetes-maven-plugin/doc/src/main/asciidoc/inc/_authentication.adoc

When you use a Maven master password and want to use `helm-push`, this will fail if you do not configure `helm` → `security` to point to your master password file (which normally is something like
~/.m2/settings-security.xml or ~/.settings-security.xml). Documentation did not mention that, so that is added.

doc : When using a Maven master password you should configure `helm` → `security`

---

jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/unix/UnixSocketTest.java

Fix #2676
Refactor UnixSocketTest to use try-with-resources for UnixSocket objects

UnixSocketTest : Use try with resources while creating object #2676

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/FileUtilTest.java

On my platform (Ubuntu Linux 6.5.0-17-generic on ext4) the last modified timestamps are rounded to the nearest second.

Fix unit test so it works on all platforms

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java

Remove redundant exception declaration and relative now unused exception import.
Fixes #2673

chore: remove redundant exception declaration in KubernetesPushTaskTest.setUp

---

jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/AuthConfigTest.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuthTest.java
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Serialization.java
jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java

This pull request keeps the ordering of lines in Yaml fragments as-is. The only exception is the Helm `values.yaml` file, which is still sorted alphabetically.
This change is needed when we eventually want to allow plain Helm directives in Yaml fragments.
This pull request is an exerpt of https://github.com/eclipse/jkube/pull/2689.

Do not order all Yaml maps by keys, only the Helm values file

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/AssemblyConfigurationTest.java

Fixes https://github.com/eclipse/jkube/issues/2526
use JsonMapper configure method instead of deprecated configure method#2526

use JsonMapper configure method instead of deprecated configure method#2526

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesRemoteDevTaskTest.java

Removes a redundant 'throws Exception" in a test from the gradle plugin 
Fixes #2716 

chore (gradle-plugin): KubernetesRemoteDevTaskTest.setUp removed "throws Exception"

---

jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java

- Replace double assertion `assertThrows` + `assertThat` with the single equivalent and more readable assertj `assertThatIOException` in test `RegistryServiceTest.pullImageWithPolicy_pullPolicyNeverAndNoImage_shouldThrowException`
- Replace related import
Fixes #2713

chore: replace double assertion assertThrows and assertThat with single assertj's assertThatIOException in RegistryServiceTest

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesUndeployTaskTest.java

chore: remove unwanted exception throw #2719

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesResourceTaskTest.java

Erased IOException from KubernetesResourceTaskTest.java #2718

---

jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java

Fixes #2751 
Removed the useless exception in the method signature

#2751 Remove the useless exception because it is never thrown

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/JKubeProjectUtilTest.java

Fixes #2685 
JKubeProjectUtilTest seems to be using mock at some places, which can be refactor to use real objects.

chore(jkube-kit-common): Removed org.mockito.Mockito references from JKubeProjectUtilTest

---

BUILDING.md
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTask.java
jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractHelmMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractJKubeMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmLintMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojo.java
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmLintMojo.java
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmMojo.java

When new Helm goals will be written, this class will serve as a base class. (I'd like to take a stab at introducing `helm-install` and `helm-uninstall` goals.) Previously, the HelmMojo class served as both a Helm goal and a base class for other Helm goals (like helm-push and helm-lint).

Introduce AbstractHelmMojo class

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/GeneratorManager.java
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/DefaultGeneratorManager.java
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/DefaultGeneratorManagerTest.java
jkube-kit/generator/api/src/test/resources/META-INF/jkube/generator-default
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java

Refactor related to https://github.com/eclipse/jkube/pull/2378#issuecomment-1970800274
+ Add an interface `GeneratorManager` in `jkube-kit/config/image`
+ Rename existing `GeneratorManager` to `DefaultGeneratorManager` that will implement above interface, rather than relying on static method.
+ Update maven Mojos and AbstractJKubeTask to use GeneratorManager interface method instead of static method

refactor (jkube-kit) : Add GeneratorManager interface in `jkube-kit/config/image`

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java

Removed declared exception in ResourceMojo.extractEnricherConfig 

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTaskTest.java

Fixes #2720 - KubernetesWatchTaskTest.setUp The declared Exception exception is never thrown

updated setUp() function

---

jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java

Fixes #2775
Replaced the creation of the temporary directory with the `@TempDir` JUnit annotation

Replaced the creation of the temporary directory using the @TempDir JUnit annotation

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceBuildIntegrationTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java

Fixes #2733 
Fixes #2768 
For `JibBuildServiceBuildIntegrationTest`:
Changed the linux file separators to platform specific file separators.
For `OpenshiftBuildServiceIntegrationTest`:
Changed the `outputDirectory` to return relative path for `target`.
Changed `Dockerfile` location in `build_withDockerfileModeAndAssembly_shouldSucceed()` to `baseDirectory`

Issue-Fix-#2733 chore(test): fixed failing tests in jkube-kit/config/service module

---

jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/oci/OCIRegistryInterceptorTest.java

Fixes #2747
Updated the declaration of afterFailure_whenUnauthenticated_thenShouldAuthenticateWithGetAndFetchAccessToken() function, removed the throws statement

issue#2747:OCIRegistryInterceptorTest

---

jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandler.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ContainerHandlerTest.java

Fixes #2812 
Acceptance Criteria (From Bug description)

ContainerHandler : Return empty collection instead of null

---

gradle-plugin/it/src/it/multiple-services/expected/openshift.yml
gradle-plugin/it/src/it/route-name-fragment/expected/openshift.yml
gradle-plugin/it/src/it/service-name-fragment/expected/openshift.yml
gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass-annotation/openshift.yml
gradle-plugin/it/src/it/volume-permission/expected/custom-storageclass/openshift.yml
gradle-plugin/it/src/it/volume-permission/expected/default/openshift.yml
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherBehavioralTest.java
jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricherTest.java

Fixes #2847 
According to Openshift API specification, `spec.port.targetPort` have to be set with the target port of the service that the route try to expose:
```
The target port on pods selected by the service this route points to. If this is a string, it will be looked up as a named port in the target endpoints port list. Required
```
At the moment, openshift maven plugin use service set the route targetPort to service port.
https://docs.openshift.com/container-platform/4.15/rest_api/network_apis/route-route-openshift-io-v1.html#spec-port

#2847 OpenShift route generated targetPort doesn't use the service "targetPort"

---

CHANGELOG.md
jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackBuildOptions.java
jkube-kit/build/service/buildpacks/src/main/java/org/eclipse/jkube/kit/service/buildpacks/controller/BuildPackCliController.java
jkube-kit/build/service/buildpacks/src/test/java/org/eclipse/jkube/kit/service/buildpacks/BuildPackCliControllerTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildServiceTest.java

Fix #2459
+ Add `imagePullPolicy`, `tags`, `env`, `volumes` fields to BuildPackBuildOptions
+ Modify BuildPackBuildService to pass on abovementioned fields configured in ImageConfiguration to BuildPackBuildOptions

feat (jkube-kit/build) : Configure buildpacks build via ImageConfiguration

---

jkube-kit/doc/src/main/asciidoc/inc/resource-generation/_controller_resource_generation.adoc
jkube-kit/doc/src/main/asciidoc/inc/resource-generation/gradle/_controller_resource_configuration_example.adoc
jkube-kit/doc/src/main/asciidoc/inc/resource-generation/maven/_controller_resource_configuration_example.adoc

doc: Add documentation for nodeSelector support via Maven XML and Groovy DSL

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/ArchiveDecompressor.java

Adds parameterized type to ArchiveInputStream
Fixes #2838

Added paramterized type for ArchiveInputStream

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java

Removed Redundant Function from superclass

---

gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ITGradleRunnerExtension.java

This PR addresses a minor code cleanliness issue in the ITGradleRunnerExtension.afterEach method within the JKube Gradle Plugin Integration Tests. Previously, the method signature unnecessarily declared throwing an Exception, despite no such exceptions being thrown within the method body or by its operations. This change simplifies the method signature by removing the throws Exception declaration, aligning it with best practices and enhancing code readability.
Fixes #2630
Type of Change
Bug fix (non-breaking change which fixes an issue)
Checklist
I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
My code follows the style …

Updated afterEach method signature

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtils.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java

fix(oc-build): Correctly pass Docker build-arg from the build configuration to the Openshift build strategy

---

jkube-kit/profile/src/test/java/org/eclipse/jkube/kit/profile/ProfileUtilTest.java

Exception that was never thrown is removed

---

jkube-kit/doc/src/main/asciidoc/inc/_generator.adoc
jkube-kit/doc/src/main/asciidoc/inc/generator/_simple_dockerfile.adoc

Documentation for https://github.com/eclipse/jkube/pull/2802

doc (jkube-kit/doc) : Add documentation for SimpleDockerfileGenerator

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTaskTest.java

Fixes #2928
Removed an unused import statement in jkube/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTaskTest.java
- [ x] Chore (non-breaking change which doesn't affect codebase;

Remove unused imports

---

jkube-kit/jkube-kit-wildfly-jar/src/main/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGenerator.java

Fixes #2931
Defines and throws a dedicated exception instead of using a generic one in WildflJarGenerator.java 
Uses JKubeException class instead of RuntimeException
- [x ] Feature (non-breaking change which adds functionality)
- [ x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ x] I have performed a …

fixes Wildfly Generator to accept JKube exception for issue #2931

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/GitUtil.java

Removes the null check in `GitUtil.getGitRepository` 
Fixes #2711

Remove null check in GitUtil 

---

CHANGELOG.md
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesDebugTask.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesDebugTaskTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftDebugTaskTest.java
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/JKubeBuildStrategy.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugContext.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojo.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/DebugMojoTest.java

Fix #2462 
+ Add DebugContext POJO for storing debug goal related attributes from Mojo/Tasks to DebugService
+ Add boolean field `supportsDebug` in JKubeBuildStrategy to indicate whether debug is supported in a particular build strategy.
+ Add conditional statement in DebugService's debug method to throw exception when `supportsDebug` evaluates to `false`

feat (jkube-kit/config/service) : DebugService throws exception in `buildpacks` build strategy (#2462)

---

CHANGELOG.md
jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/BuildConfiguration.java
jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/BuildConfigurationTest.java
jkube-kit/config/image/src/test/resources/build-configuration.json
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildServiceTest.java
jkube-kit/doc/src/main/asciidoc/inc/build/_configuration.adoc
jkube-kit/doc/src/main/asciidoc/inc/generator/_options_common.adoc
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java

Fix #2470
Add a field in ImageConfiguration's Build named `buildpacksBuilderImage` that can be used by the user for configuring buildpack builder image. This field would also be exposed via `jkube.generator.buildpacksBuilderImage` property and generators `buildpacksBuilderImage` config

feat (jkube-kit) : Add configuration option for overriding buildpack builder image (#2470)

---

README.md
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java
quickstarts/maven/hello-world/README.md
quickstarts/maven/hello-world/pom.xml
quickstarts/maven/hello-world/src/main/java/org/eclipse/jkube/sample/helloworld/App.java
quickstarts/maven/hello-world/src/main/java/org/eclipse/jkube/sample/helloworld/RootHandler.java

Improve example 2788

---

jkube-kit/parent/pom.xml

Doesn't seem necessary anymore:
https://github.com/eclipse-jkube/jkube/pull/2980
After some analysis and digging, it seems that this was added to FMP and DMP for deployment purposes:
- https://github.com/fabric8io/fabric8-maven-plugin/pull/54
- https://github.com/fabric8io/docker-maven-plugin/commit/639bc925d1153bae61540c5497d12adf00f170f9
This seems to be unnecessary now. So maybe better to remove the dependency altogether.

config: remove wagon-ssh-external maven extension

---

openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/OpenshiftWatchMojo.java

Removed unused import

---

CHANGELOG.md
jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/BuildArgResolverUtil.java
jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/BuildArgResolverUtilMergeBuildArgsTest.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/BuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtils.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java

Added call to resolve build args from all sources in OpenShiftBuildServiceUtils so that build args get resolved from all the available sources (compared to just ImageConfig)
Fixes #2904

fix (jkube-kit/config) : `docker.buildArg.*` properties not taken into account in OpenShift plugins

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/Serialization.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SerializationTest.java

Fix #3007
Update Serialization's YAML_MAPPER to use line breaks specific to platform it's running on. Earlier we were always using Line Feeds whether on Windows or Unix.

fix (jkube-kit) : Configure YAML_MAPPER to use platform specific line endings

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/assertj/FileAssertions.java

Modified method fileTree to compute relative path based on the realPath of parent and children in a file tree
Fixes #3001 
- [] I have added tests that prove my fix is effective or that my feature works

Fix method fileTree to compare realPath of parent and children

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SerializationTest.java
jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitor.java
jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/visitor/MetadataVisitorTest.java

Related to #2841
Currently for enforcing trailing newline in case of multi line strings in resource annotations, we were relying on presence of `System.lineSeparator()`.
This was causing problems as YAML multiline scalar values are converted into strings with Line Feed (`\n`) endings when they're deserialized into objects. I checked in YAML spec and found this:
https://yaml.org/spec/1.2.2/#line-break-characters
> Line breaks inside[ scalar content](https://yaml.org/spec/1.2.2/#scalar) must be normalized by the YAML[ processor](https://yaml.org/spec/1.2.2/#processes-and-models). Each such line break must be[ parsed](https://yaml.org/spec/1.2.2/#parsing-the-presentation-stream) into a single line feed character. The original line break format is a[ presentation …

fix (jkube-kit/enricher) : YAML multiline annotations incorrectly serialized on windows

---

jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherIntegrationTest.java

In order to fix failing tests on macos, we need to use the real path of jars instead of the absolute path. I.e. we need to use `private/var/folders/...` instead of `/var/folders/...`. Thus, method `absolutePath` is replaced with the `realPath`.
Fixes #3009 
- [] I have added tests that prove my fix is effective or that my feature works

fix SpringBootWatcherIntegrationTest on macos

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtilTest.java

chore: remove unused import from KubernetesClientUtilTest.java

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftResourceTaskTest.java
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/DefaultGeneratorManager.java
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/GeneratorContext.java
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/DefaultGeneratorManagerTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java

In Resource mojo and tasks, we've duplicated code that adds the following properties to JavaProject in case of OpenShift mode:
- `jkube.image.user` : Sets image user property to currently logged in OpenShift namespace so that image user portion points to namespace
- `jkube.internal.effective.platform.mode` : Used by some enrichers to determine whether current platform is OpenShift. This looks like a remnant of Fabric8 Maven Plugin refactor. We should get rid of this in follow up PR.
This PR only moves code from Mojos/Tasks -> DefaultGeneratorManager.generateAndMerge()

refactor (jkube-kit) : Move logic for adding OpenShift Build specific properties to DefaultGeneratorManager

---

jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java

refactor: initial changes to support multiplatform build
relates to #2098

refactor: initial changes to support multiplatform build

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceTest.java

refactor: further changes in JibBuildService to support multiplatform build
relates to #2098

refactor: further changes in JibBuildService to support multiplatform build

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildService.java
jkube-kit/config/service/src/main/resources/META-INF/jkube/build-service
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceGetApplicableRegistryTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceIntegrationTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceTest.java

Allows for a new JibService generic service class that wraps JibServiceUtil
relates to #2098

refactor: rename JibBuildService to JibImageBuildService

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmMojo.java

Remove redundant method identical to super method in HelmMojo
Fixes #2929

fix: remove redundant method identical to super method in HelmMojo

---

CHANGELOG.md
jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceTest.java
jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUploadIT.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmPushMojoTest.java

The Docker/OCI registries used by the Helm Upload service were based on the configured global and pull registries. This was probably due to the fact that these registries were the only ones available from the JKubeConfiguration. Also because the name of the JKubeConfiguration field was misleading (see #3064).
These changes replace the usage of the global and pull registries with the usage of the global and push registries.

fix: helm push uses configured docker global and push registries instead of pull

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTask.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesPushTaskTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftPushTaskTest.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RegistryService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/AbstractImageBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/BuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/BuildPackBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/DockerBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/PushMojo.java

refactor: push registry information read from global JKubeConfiguration

refactor: push registry information read from global JKubeConfiguration

---

jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/AuthConfigFactory.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RegistryService.java
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/DockerAuthConfigFactory.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/DockerAuthConfigFactoryTest.java
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSdkDockerAuthConfigFactoryTest.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildService.java
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java

refactor: introduce AuthConfigFactory interface

refactor: introduce AuthConfigFactory interface

---

kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java

fix : removed Exception never thrown by WatchMojo.getWatchContext() method and the corresponding catch block associated with it..

---

jkube-kit/build/service/jib/pom.xml
jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibService.java
jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServiceBuildTest.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibImageBuildServicePushTest.java

refactor: reorganize JibService#build to support multiple target tar image files
Relates to #2098

refactor: reorganize JibService#build to support multiple target tar image files

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTask.java

KubernetesWatchTask.getWatchContext The declared exception is never thrown
Fixes #3054 

KubernetesWatchTask.getWatchContext The declared exception is never thrown

---

jkube-kit/build/service/jib/src/main/java/org/eclipse/jkube/kit/service/jib/JibServiceUtil.java
jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceTest.java

feat(jib): support building images from scratch

---

jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcherTest.java

SpringBootWatcherTest Remove unused imports #3102
Fixes #3102

SpringBootWatcherTest Remove unused imports #3102

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/assertj/ArchiveAssertions.java

fix : Deprecated method getNextTarEntry replaced with the method getNextEntry in ArchiveAssertions

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootConfiguration.java
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/enricher/SpringBootHealthCheckEnricher.java
jkube-kit/jkube-kit-spring-boot/src/test/java/org/eclipse/jkube/springboot/enricher/AbstractSpringBootHealthCheckEnricherTestSupport.java

Fixes #2665 
Added implementation for creating explicit path creation for `readiness` and `liveness` probes when `management.health.probes.enabled` is `true`.
Modified `SpringBootHealthCheckEnricher` to check if the suffix needs to be concatenated to the paths or not.
Created unit tests for the added implementation and verified if everything was working as expected.

Issue-Fix-#2665 feat: added implementation for explicit path for readiness and liveness Probes

---

jkube-kit/doc/src/main/asciidoc/inc/enricher/spring-boot-healthcheck/_jkube_healthcheck_spring_boot.adoc

Documentation for #2663
Add a note in SpringBootHealthCheckEnricher documentation about the effect of `management.health.probes.enabled` property on enricher behavior.

doc : Add note in SpringBootHealthCheckEnricher documentation about enabled management health probe endpoints

---

jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/IngressConfigTest.java

Fixes #3157 
Fixes #2527
1. Replaced `asList()` method with `asInstanceOf(...)`
2. Replaced `hasSize(1).element(0)` with `singleElement()`
3. Used `JsonMapper.builder().configure(..)` instead of deprecated `ObjectMapper.configure(..)`
- [] I Added [CHANGELOG](../CHANGELOG.md) entry

Replace AssertJ's deprecated asList() DSL method

---

jkube-kit/jkube-kit-helidon/src/test/java/org/eclipse/jkube/helidon/generator/HelidonGeneratorTest.java

Replace `asList` with `asInstanceOf`
Fixes #3159

chore(deprecated assertion):  replace asList with asInstanceOf

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java

Duplicated getNewestPod method is removed from PortForwardService and KubernetesHelper.getNewestPod is used.

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesMockServerUtil.java

Required by https://github.com/eclipse-jkube/jkube/pull/3142
+ When using KubernetesClient with Kubernetes Mock Server, `kubernetesClient.getConfiguration()` returns a Config object with no context set.
+ `kubernetesClient.getConfiguration()` does not provide any certificate data. When no certificate data is provided add `InsecureSkipTlsVerify` option in kubeconfig
Handle this case in KubernetesHelper to create an opinionated Context until this gets fixed in KubernetesMockServer

fix (jkube-kit/common) : Update `KubernetesHelper.exportKubernetesClientConfigToFile` to add opinionated Cluster Context

---

CHANGELOG.md
jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java
jkube-kit/generator/api/src/test/java/org/eclipse/jkube/generator/api/support/BaseGeneratorTest.java
jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/JavaExecGenerator.java
jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorCustomPropertiesTest.java
jkube-kit/generator/karaf/src/main/java/org/eclipse/jkube/generator/karaf/KarafGenerator.java
jkube-kit/generator/karaf/src/test/java/org/eclipse/jkube/generator/karaf/KarafGeneratorTest.java
jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java
jkube-kit/generator/webapp/src/test/java/org/eclipse/jkube/generator/webapp/WebAppGeneratorTest.java

Tag `latest` should not be added when image name contains pattern `%t`, or it will likely break immutable repositories that don't allow overwriting artifact tags.
Fixes https://github.com/eclipse-jkube/jkube/issues/3161

fix: don't unconditionally add latest tag

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractHelmTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmDependencyUpdateTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmLintTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTask.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmTask.java

Based on the previous work done on the issue #2714 , we introduce the same Abstract class but for Gradle plugin. 
Fixes #2773

Add abstract class for helm task

---

openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftResourceMojoTest.java

OpenShiftResourceMojoTest is failing on Windows due to use of \n as line separator.
Fixes #3180 
OpenShiftResourceMojoTest is failing on Windows due to use of \n as line separator #3180
Fix: Replaced \n with %n that would be platform independent

fix: Fixed failing test on Windows

---

gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesConfigViewTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmPushTaskTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmTaskTest.java

Fixes #2842 
For `KubernetesHelmPushTaskTest` & `KubernetesHelmTaskTest`:
The issue was occurring due to the use of linux file separator instead of the native file separator. The issue was fixed with the help of `separatorsToSystem()`.
For `KubernetesConfigViewTaskTest`:
The issue was related to the use of Line Feed in place in of native line separator. The issue fixed by modifying the test to use native line separator.

Issue-Fix-#2842 chore(test): fixed unit tests failing for gradle-plugin in Windows

---

jkube-kit/watcher/standard/src/test/java/org/eclipse/jkube/watcher/standard/DockerImageWatcherRestartContainerTest.java

DockerImageWatcherRestartContainerTest: Remove unused imports #2922 to clean up the code and improve readability.
On branch pr/issue2922
This PR addresses issue #2922 by removing unused imports in the `DockerImageWatcherRestartContainerTest` class. Specifically, the import statement on line 43:
import org.eclipse.jkube.kit.config.access.ClusterAccess;
Fixes #2922 

Chore: Remove unused imports in DockerImageWatcherRestartContainerTest

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesMockServerUtil.java
jkube-kit/helm/pom.xml
jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java
jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java
jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceInstallIT.java
jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java
jkube-kit/helm/src/test/resources/it/source-helm-install/kubernetes/kubernetes.yml

Related to #2663
+ Add new method `prepareMockWebServerExpectationsForAggregatedDiscoveryEndpoints` in KubernetesMockServerUtil for adding manual expectations for Kubernetes Aggregated Discovery endpoints
+ Added a new `install` method in HelmService that would perform installation of a helm chart onto Kubernetes cluster using Helm  java library
+ Added configuration options in HelmConfig
- `releaseName`
- `installDependencyUpdate`
- `installWaitReady`
- `disableOpenAPIValidation`

feat (jkube-kit/helm) : HelmService exposes helm install functionality

---

CHANGELOG.md
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ImageEnricher.java
kubernetes-maven-plugin/it/src/it/env-metadata/expected/kubernetes.yml
kubernetes-maven-plugin/it/src/it/env-metadata/pom.xml

Handle env variable with null value, translating it as empty String to avoid error on compare operation
Fixes #3220 

fix: ImageEnricher#mergeEnvVariables causes error for empty env

---

jkube-kit/common-maven/src/main/java/org/eclipse/jkube/kit/common/util/MojoExecutionService.java

Fixes https://github.com/eclipse-jkube/jkube/issues/3234

fix: MojoExecutionService 'goal.length() > 0' can be replaced with '!goal.isEmpty()'

---

CHANGELOG.md
jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/SpringBootLayeredJar.java

Fix #3228
Till now we were executing layertools list command to extract layer related information for Spring Boot Layered jar. This has started causing problems in Spring Boot 3.3.x where we're getting additional deprecation warning that's breaking behavior of SpringBootGenerator. Additionally, layertools command has become deprecated in Spring Boot 3.3.x
Instead of relying on layertools command, directly read layers.idx file present in layered jar to extract list of layers. `layers.idx` file format seems to be consistent across previous Spring Boot versions. You can see it's spec in [LayersIndex.java](https://github.com/spring-projects/spring-boot/blob/3648f5f494e6b5bb010bb7f881eb748cbc0f8cc5/spring-boot-project/spring-boot-tools/spring-boot-loader-tools/src/main/java/org/springframework/ …

fix (jkube-kit-spring-boot) : Directly read `layers.idx` file to get layers information

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtils.java

The code is cleaned up a little by replacing the nocache.length() == 0 with nocache.isEmpty in OpenShiftBuildServiceUtils
Fixes #3235

Replace string.length with isEmpty in OpenShiftBuildServiceUtils

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java

Fixes https://github.com/eclipse-jkube/jkube/issues/3205

fix: Failing Test in `KubernetesHelperTest` on windows machine

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/RegistryConfigTest.java

Fixes https://github.com/eclipse-jkube/jkube/issues/3238

refactor: improve assertion statements for RegistryConfigTest

---

jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/MappingConfig.java
jkube-kit/config/resource/src/test/java/org/eclipse/jkube/kit/config/resource/MappingConfigTest.java

Fixes #3233
FYI, looks like some of the whitespace got changed, let me know if this is something the linter shouldn't be doing.

chore: replaced .length() with .isEmpty() for filenameTypes check in MappingConfig

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/WebServerEventCollector.java

WebServerEventCollector 'evts.size() > 0' can be replaced with '!evts.isEmpty()'

---

jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandlerTest.java

Fixes https://github.com/eclipse-jkube/jkube/issues/3269

refactor: asList to asInstanceof for ServiceHandlerTest

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/UrlBuilder.java

UrlBuilder 'queryParams.size() > 0' has been replaced with '!queryParams.isEmpty()'

---

jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java

KubernetesResourceUtilTest refactor
KubernetesResourceUtilTest initContainersInSpec.size() == 0' replaced with 'initContainersInSpec.isEmpty()
https://github.com/eclipse-jkube/jkube/issues/3232
Fixes #3232

chore: KubernetesResourceUtilTest refactor

---

jkube-kit/build/service/jib/src/test/java/org/eclipse/jkube/kit/service/jib/JibServiceUtilTest.java

Fixes #3242 
Replace deprecated asList method 

chore(JibServiceUtilTest): replace deprecated asList method, issue #3242

---

jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java

Replacing AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in KubernetesResourceUtilsTest
Fixes #3267 

chore: Replace AssertJ's deprecated asList() DSL method in KubernetesResourceUtilsTest

---

jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java

Fixes #3285
Changes Made:
Replaced the anonymous inner class in the Runtime.getRuntime().addShutdownHook method with a lambda expression.

: Refactor PortForwardService to Replace Anonymous Thread with Lambda

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/access/ClusterConfiguration.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/access/ClusterConfigurationTest.java

Related to failures in #3304
ClusterConfiguration `getConfig()` method converts ClusterConfiguration to a KubernetesClient Config object. It should also set namespace in current context while setting current context in Config.

fix : ClusterConfiguration `getConfig()` should also set namespace in current context

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/RegistryAuthConfiguration.java

This pull request refactors the `RegistryAuthConfiguration` class by replacing the condition `content[i + 1].length() > 0` with `!content[i + 1].isEmpty()`. This change improves code readability and utilizes the existing `isEmpty()` method for better clarity.
Fixes #3258

Refactor RegistryAuthConfiguration to use isEmpty() instead of length() > 0

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/KubernetesPlugin.java
gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmUninstallTask.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/KubernetesPluginTest.java
gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmUninstallTaskTest.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/OpenShiftPlugin.java
gradle-plugin/openshift/src/main/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmUninstallTask.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/OpenShiftPluginTest.java
gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmUninstallTaskTest.java
kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmUninstallMojo.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/GeneratedPluginDescriptorTest.java
kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/HelmUninstallMojoTest.java
openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftHelmUninstallMojo.java
openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/OpenShiftGeneratedPluginDescriptorTest.java
openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftHelmUninstallMojoTest.java

Related to #2666
Add Mojos and Gradle tasks for exposing Helm Uninstall functionality via maven and gradle plugins

feat : Helm Uninstall functionality exposed via Maven Mojos / Gradle Tasks

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java

Issue Fix:#3230

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ValidationUtil.java

Reduces code smell by replacing String concatenation in StringBuilder call with StringBuilder.append().
Fixes #2840

chore: replaces String concatenation arguments with StringBuilder.append() (2840)

---

CHANGELOG.md
jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildService.java
jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenshiftBuildServiceIntegrationTest.java

Fix #2844 
This PR  substitutes log retrieval from `pods/log` by `build/logs`.
It removes the necessity for additional rules for building service account.
- [] I tested my code in Kubernetes

fix: openshift use pods/log to retrieve logs from build

---

jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorExposedPortsTest.java

Fixes #3341
Replace AssertJ's deprecated asList() in [jkube/jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorExposedPortsTest.java](https://github.com/eclipse-jkube/jkube/blob/8cc048e699c982a901ec8d9236fcb1430953ece4/jkube-kit/jkube-kit-quarkus/src/test/java/org/eclipse/jkube/quarkus/generator/QuarkusGeneratorExposedPortsTest.java#L72)

fix: replace deprecated aslist method in QuarkusGeneratorExposedPortsTest

---

jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/build/CleanupModeTest.java

- Added `@ParameterizedTest` to remove a `for` loop in `CleanupModeTest`.
Fixes #3345 

CleanupModeTest : refactor test to use @ParameterizedTest instead of loop

---

CHANGELOG.md
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/BuildRecreateMode.java
jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/BuildRecreateModeTest.java

Fixes #3354
No need to convert value to lowercase when parsing string value to enum

fix (jkube-kit) : Build fails with imageStream for buildRecreate value

---

jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java

Jkube-kit
fix: Casting 'serverUrls' to 'List<?>' is redundant
Fixes #3337 

fix: Casting 'serverUrls' to 'List<?>' is redundant

---

jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/OpenLibertyUtilsTest.java

Replaced Mockito.mock by creating actual object 
Fixes #3407

Replaced Mockito.mock by creating actual object

---

jkube-kit/jkube-kit-openliberty/src/test/java/org/eclipse/jkube/openliberty/generator/OpenLibertyGeneratorTest.java

This pull request addresses issue #3403, where the deprecated `asList() `DSL method in the AssertJ framework is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class)) ` in the OpenLibertyGeneratorTest class. This change is necessary to ensure compatibility with the latest versions of AssertJ, where the `asList() `method has been marked as deprecated.
Fixes #3403 

Replaced deprecated-aslist-in-open-liberty-generator-test

---

jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/generator/SpringBootGenerator.java

Fixes #3371
- This pull request addresses issue #3371, which suggests replacing lambda expressions with method references where applicable in the SpringBootGenerator. Method references offer more concise syntax and can improve readability.
**Changes:**
- Refactored lambda expressions that can be simplified by method references.
- Updated occurrences where method references provide cleaner and more efficient code, ensuring no changes to the functionality of the SpringBootGenerator.

Replace lambda with method reference in SpringBootGenerator (#3371)

---

jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java

Fixes #3339
Modified VertxHealthCheckEnricher class, replaced Collections.<String, String>emptyMap() with Collections.emptyMap().

3339 issue fix (replaced Collections.<String, String>emptyMap() with Collections.emptyMap() )

---

jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java

Fixes #3472
- [ x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [ x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report

issue #3472 has been resolved by remove .toString() method

---

.github/workflows/build-macos.yml
gradle-plugin/it/src/it/git-annotations/expected/kubernetes.yml
gradle-plugin/it/src/it/git-annotations/expected/openshift.yml
jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/WatchServiceTest.java

ci: build pipeline based on MacOS

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java

Fixes #3368
Fixed issue for class GradleUtil : Explicit type argument Configuration replaced with <>
This is my first contribution, so please let me know if I could have done something better.

 Fixed issue for class GradleUtil : Explicit type argument Configuration replaced with <>

---

jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricherAddMissingPartsTest.java

This pull request addresses **Issue #3507**, which involves replacing the deprecated `asList()` method in the `DefaultServiceEnricherAddMissingPartsTest` class with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`. This update is necessary to ensure compatibility with the latest AssertJ library and to maintain code quality.
Fixes #3507 

Fix #3507: Replace Deprecated `asList()` Method in DefaultServiceEnricherAddMissingPartsTest

---

jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/win/NpipeConnectionSocketFactory.java

Description: Removed IOException that was being thrown in [NpipeConnectionSocketFactory.createSocket](https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/win/NpipeConnectionSocketFactory.java#L36)
Fixes #2746
- [x ] Chore (non-breaking change which doesn't affect codebase;
- [ x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
- [x ] I Keep It Small and Simple: The smaller the PR is, …

fix: Deleted IOException from NpipeConnectionSocketFactory.createSocket

---

gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/DependencyResourcesIT.java

Avoids conflict of file locks during clean phase by generating replica set in a different directory.
Fixes #3476 
Related to #3406 

fixes file locking issue in DependencyResourcesIT

---

gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesHelmLintTask.java

Fixes #3514
This pull request (#3514) removes the unused import 'org.eclipse.jkube.kit.resource.helm.HelmConfig' from the `KubernetesHelmLintTask.java` file.

Removed unused import from KubernetesHelmLintTask.java

---

openshift-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenShiftHelmUninstallMojoTest.java

Removed the declaration of thrown exception'java.io.IOException', as it cannot be thrown from method's body

SonarQube AI Fix - openshift-maven-plugin

---

gradle-plugin/it/src/it/secret-file/expected/kubernetes_windows_line_endings.yml
gradle-plugin/it/src/it/secret-file/expected/openshift_windows_line_endings.yml
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/FileSecretIT.java
gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/FileSecretWindowsIT.java
jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/FileDataSecretEnricher.java

FileSecretIT Issue resolved

---

jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/generator/MicronautGenerator.java

Refactor: #3370: MicronautGenerator: Replaced Lambda expression with Method reference.

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/HealthCheckMode.java

Fixes #3613
The class [HealthCheckMode](https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/HealthCheckMode.java#L27) presents the issue: Unnecessary semicolon `;`.
The following line:
[jkube/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/HealthCheckMode.java](https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/HealthCheckMode.java#L27)
Line 27 in [5da6068](https://github.com/eclipse-jkube/jkube/commit/5da6068d7756784aef9569568ee80f98da97e296):
```java
cmd;
```
has been changed to:
```java
cmd
```

Issue #3613: Fix/unnecessary semicolon 

---

jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java

Fixes #3611 
Removed Unnecessary call to 'toString()' in [VertxHealthCheckEnricher.java](https://github.com/eclipse-jkube/jkube/blob/a0a3369d3e82a2ee56034b9ecfec70e8c957b289/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java#L281)
Line 281:
```
config.getKey(), input.getClass(), input.toString()));
```
has been changed to:
```
config.getKey(), input.getClass(), input));
```

fix: remove Unnecessary call to 'toString()' in VertxHealthCheckEnricher.java (#3611)

---

jkube-kit/generator/java-exec/src/test/java/org/eclipse/jkube/generator/javaexec/JavaExecGeneratorMainClassDeterminationTest.java

Fixes #3615
Removes an unnecessary semicolon.

Issue #3615: Fix/unnecessary semicolon 

---

jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileBuilder.java

Fixes #3610 
Remove unnecessary call to 'toString()' in DockerFileBuilder

Fixed issue #3610 remove unnecessary toString() call in DockerFileBuilder

---

jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/openshift/OpenShiftBuildServiceUtilsTest.java

This pull request introduces the following changes to the `OpenShiftBuildServiceUtilsTest.java`:
-   Refactored the lambda expression in the `assertBuildArgPresentInBuildStrategy` method to a more concise form.
-   Removed the braces around the single statement in the lambda expression.
Fixes #3686 

test: simplify lambda expression in OpenShiftBuildServiceUtilsTest
